// Code generated by "stringer -type THOST_TE_RESUME_TYPE -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_TERT_RESTART-0]
	_ = x[THOST_TERT_RESUME-1]
	_ = x[THOST_TERT_QUICK-2]
	_ = x[THOST_TERT_NONE-3]
	_ = x[THOST_TERT_RESUME_FROM_SEQ_NO-4]
}

const _THOST_TE_RESUME_TYPE_name = "RESTARTRESUMEQUICKNONERESUME_FROM_SEQ_NO"

var _THOST_TE_RESUME_TYPE_index = [...]uint8{0, 7, 13, 18, 22, 40}

func (i THOST_TE_RESUME_TYPE) String() string {
	if i < 0 || i >= THOST_TE_RESUME_TYPE(len(_THOST_TE_RESUME_TYPE_index)-1) {
		return "THOST_TE_RESUME_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _THOST_TE_RESUME_TYPE_name[_THOST_TE_RESUME_TYPE_index[i]:_THOST_TE_RESUME_TYPE_index[i+1]]
}
