// Code generated by "stringer -type TThostFtdcVirTradeStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VTS_NaturalDeal-48]
	_ = x[THOST_FTDC_VTS_SucceedEnd-49]
	_ = x[THOST_FTDC_VTS_FailedEND-50]
	_ = x[THOST_FTDC_VTS_Exception-51]
	_ = x[THOST_FTDC_VTS_ManualDeal-52]
	_ = x[THOST_FTDC_VTS_MesException-53]
	_ = x[THOST_FTDC_VTS_SysException-54]
}

const _TThostFtdcVirTradeStatusType_name = "正常处理中成功结束失败结束异常中已人工异常处理通讯异常 ，请人工处理系统出错，请人工处理"

var _TThostFtdcVirTradeStatusType_index = [...]uint8{0, 15, 27, 39, 48, 69, 100, 130}

func (i TThostFtdcVirTradeStatusType) String() string {
	i -= 48
	if i >= TThostFtdcVirTradeStatusType(len(_TThostFtdcVirTradeStatusType_index)-1) {
		return "TThostFtdcVirTradeStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcVirTradeStatusType_name[_TThostFtdcVirTradeStatusType_index[i]:_TThostFtdcVirTradeStatusType_index[i+1]]
}
