// Code generated by "stringer -type TThostFtdcFutureAccTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FAT_BankBook-49]
	_ = x[THOST_FTDC_FAT_SavingCard-50]
	_ = x[THOST_FTDC_FAT_CreditCard-51]
}

const _TThostFtdcFutureAccTypeType_name = "银行存折储蓄卡信用卡"

var _TThostFtdcFutureAccTypeType_index = [...]uint8{0, 12, 21, 30}

func (i TThostFtdcFutureAccTypeType) String() string {
	i -= 49
	if i >= TThostFtdcFutureAccTypeType(len(_TThostFtdcFutureAccTypeType_index)-1) {
		return "TThostFtdcFutureAccTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFutureAccTypeType_name[_TThostFtdcFutureAccTypeType_index[i]:_TThostFtdcFutureAccTypeType_index[i+1]]
}
