// Code generated by "stringer -type TThostFtdcInvestorTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CT_Person-48]
	_ = x[THOST_FTDC_CT_Company-49]
	_ = x[THOST_FTDC_CT_Fund-50]
	_ = x[THOST_FTDC_CT_SpecialOrgan-51]
	_ = x[THOST_FTDC_CT_Asset-52]
}

const _TThostFtdcInvestorTypeType_name = "自然人法人投资基金特殊法人资管户"

var _TThostFtdcInvestorTypeType_index = [...]uint8{0, 9, 15, 27, 39, 48}

func (i TThostFtdcInvestorTypeType) String() string {
	i -= 48
	if i >= TThostFtdcInvestorTypeType(len(_TThostFtdcInvestorTypeType_index)-1) {
		return "TThostFtdcInvestorTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcInvestorTypeType_name[_TThostFtdcInvestorTypeType_index[i]:_TThostFtdcInvestorTypeType_index[i+1]]
}
