// Code generated by "stringer -type TThostFtdcBankAccTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BAT_BankBook-49]
	_ = x[THOST_FTDC_BAT_SavingCard-50]
	_ = x[THOST_FTDC_BAT_CreditCard-51]
}

const _TThostFtdcBankAccTypeType_name = "银行存折储蓄卡信用卡"

var _TThostFtdcBankAccTypeType_index = [...]uint8{0, 12, 21, 30}

func (i TThostFtdcBankAccTypeType) String() string {
	i -= 49
	if i >= TThostFtdcBankAccTypeType(len(_TThostFtdcBankAccTypeType_index)-1) {
		return "TThostFtdcBankAccTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcBankAccTypeType_name[_TThostFtdcBankAccTypeType_index[i]:_TThostFtdcBankAccTypeType_index[i+1]]
}
