// Code generated by "stringer -type TThostFtdcCZCEUploadFileNameType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CUFN_CUFN_O-79]
	_ = x[THOST_FTDC_CUFN_CUFN_T-84]
	_ = x[THOST_FTDC_CUFN_CUFN_P-80]
	_ = x[THOST_FTDC_CUFN_CUFN_N-78]
	_ = x[THOST_FTDC_CUFN_CUFN_L-76]
	_ = x[THOST_FTDC_CUFN_CUFN_F-70]
	_ = x[THOST_FTDC_CUFN_CUFN_C-67]
	_ = x[THOST_FTDC_CUFN_CUFN_M-77]
}

const (
	_TThostFtdcCZCEUploadFileNameType_name_0 = "^\\d{8}组合持仓表"
	_TThostFtdcCZCEUploadFileNameType_name_1 = "^\\d{8}资金表"
	_TThostFtdcCZCEUploadFileNameType_name_2 = "^\\d{8}平仓表^\\d{8}保证金参数表^\\d{8}非平仓了结表^\\d{8}_zz_\\d{4}^\\d{8}单腿持仓表new"
	_TThostFtdcCZCEUploadFileNameType_name_3 = "^\\d{8}成交表"
)

var (
	_TThostFtdcCZCEUploadFileNameType_index_2 = [...]uint8{0, 15, 39, 63, 78, 102}
)

func (i TThostFtdcCZCEUploadFileNameType) String() string {
	switch {
	case i == 67:
		return _TThostFtdcCZCEUploadFileNameType_name_0
	case i == 70:
		return _TThostFtdcCZCEUploadFileNameType_name_1
	case 76 <= i && i <= 80:
		i -= 76
		return _TThostFtdcCZCEUploadFileNameType_name_2[_TThostFtdcCZCEUploadFileNameType_index_2[i]:_TThostFtdcCZCEUploadFileNameType_index_2[i+1]]
	case i == 84:
		return _TThostFtdcCZCEUploadFileNameType_name_3
	default:
		return "TThostFtdcCZCEUploadFileNameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
