// Code generated by "stringer -type TThostFtdcBatchStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BS_NoUpload-49]
	_ = x[THOST_FTDC_BS_Uploaded-50]
	_ = x[THOST_FTDC_BS_Failed-51]
}

const _TThostFtdcBatchStatusType_name = "未上传已上传审核失败"

var _TThostFtdcBatchStatusType_index = [...]uint8{0, 9, 18, 30}

func (i TThostFtdcBatchStatusType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcBatchStatusType_index)-1 {
		return "TThostFtdcBatchStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcBatchStatusType_name[_TThostFtdcBatchStatusType_index[idx]:_TThostFtdcBatchStatusType_index[idx+1]]
}
