// Code generated by "stringer -type TThostFtdcParkedOrderStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PAOS_NotSend-49]
	_ = x[THOST_FTDC_PAOS_Send-50]
	_ = x[THOST_FTDC_PAOS_Deleted-51]
}

const _TThostFtdcParkedOrderStatusType_name = "未发送已发送已删除"

var _TThostFtdcParkedOrderStatusType_index = [...]uint8{0, 9, 18, 27}

func (i TThostFtdcParkedOrderStatusType) String() string {
	i -= 49
	if i >= TThostFtdcParkedOrderStatusType(len(_TThostFtdcParkedOrderStatusType_index)-1) {
		return "TThostFtdcParkedOrderStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcParkedOrderStatusType_name[_TThostFtdcParkedOrderStatusType_index[i]:_TThostFtdcParkedOrderStatusType_index[i+1]]
}
