// Code generated by "stringer -type TThostFtdcResponseValueType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RV_Right-48]
	_ = x[THOST_FTDC_RV_Refuse-49]
}

const _TThostFtdcResponseValueType_name = "检查成功检查失败"

var _TThostFtdcResponseValueType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcResponseValueType) String() string {
	i -= 48
	if i >= TThostFtdcResponseValueType(len(_TThostFtdcResponseValueType_index)-1) {
		return "TThostFtdcResponseValueType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcResponseValueType_name[_TThostFtdcResponseValueType_index[i]:_TThostFtdcResponseValueType_index[i+1]]
}
