// Code generated by "stringer -type TThostFtdcFBEResultFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBERES_Success-48]
	_ = x[THOST_FTDC_FBERES_InsufficientBalance-49]
	_ = x[THOST_FTDC_FBERES_UnknownTrading-56]
	_ = x[THOST_FTDC_FBERES_Fail-120]
}

const (
	_TThostFtdcFBEResultFlagType_name_0 = "成功账户余额不足"
	_TThostFtdcFBEResultFlagType_name_1 = "交易结果未知"
	_TThostFtdcFBEResultFlagType_name_2 = "失败"
)

var (
	_TThostFtdcFBEResultFlagType_index_0 = [...]uint8{0, 6, 24}
)

func (i TThostFtdcFBEResultFlagType) String() string {
	switch {
	case 48 <= i && i <= 49:
		i -= 48
		return _TThostFtdcFBEResultFlagType_name_0[_TThostFtdcFBEResultFlagType_index_0[i]:_TThostFtdcFBEResultFlagType_index_0[i+1]]
	case i == 56:
		return _TThostFtdcFBEResultFlagType_name_1
	case i == 120:
		return _TThostFtdcFBEResultFlagType_name_2
	default:
		return "TThostFtdcFBEResultFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
