// Code generated by "stringer -type TThostFtdcSwapSourceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SST_Manual-48]
	_ = x[THOST_FTDC_SST_Automatic-49]
}

const _TThostFtdcSwapSourceTypeType_name = "手工自动生成"

var _TThostFtdcSwapSourceTypeType_index = [...]uint8{0, 6, 18}

func (i TThostFtdcSwapSourceTypeType) String() string {
	i -= 48
	if i >= TThostFtdcSwapSourceTypeType(len(_TThostFtdcSwapSourceTypeType_index)-1) {
		return "TThostFtdcSwapSourceTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSwapSourceTypeType_name[_TThostFtdcSwapSourceTypeType_index[i]:_TThostFtdcSwapSourceTypeType_index[i+1]]
}
