// Code generated by "stringer -type TThostFtdcWeakPasswordSourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_WPSR_Lib-49]
	_ = x[THOST_FTDC_WPSR_Manual-50]
}

const _TThostFtdcWeakPasswordSourceType_name = "弱密码库手工录入"

var _TThostFtdcWeakPasswordSourceType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcWeakPasswordSourceType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcWeakPasswordSourceType_index)-1 {
		return "TThostFtdcWeakPasswordSourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcWeakPasswordSourceType_name[_TThostFtdcWeakPasswordSourceType_index[idx]:_TThostFtdcWeakPasswordSourceType_index[idx+1]]
}
