// Code generated by "stringer -type TThostFtdcTimeRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ETR_USUAL-49]
	_ = x[THOST_FTDC_ETR_FNSP-50]
	_ = x[THOST_FTDC_ETR_BNSP-51]
	_ = x[THOST_FTDC_ETR_SPOT-52]
}

const _TThostFtdcTimeRangeType_name = "一般月份交割月前一个月上半月交割月前一个月下半月交割月份"

var _TThostFtdcTimeRangeType_index = [...]uint8{0, 12, 42, 72, 84}

func (i TThostFtdcTimeRangeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcTimeRangeType_index)-1 {
		return "TThostFtdcTimeRangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcTimeRangeType_name[_TThostFtdcTimeRangeType_index[idx]:_TThostFtdcTimeRangeType_index[idx+1]]
}
