// Code generated by "stringer -type TThostFtdcIdCardTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ICT_EID-48]
	_ = x[THOST_FTDC_ICT_IDCard-49]
	_ = x[THOST_FTDC_ICT_OfficerIDCard-50]
	_ = x[THOST_FTDC_ICT_PoliceIDCard-51]
	_ = x[THOST_FTDC_ICT_SoldierIDCard-52]
	_ = x[THOST_FTDC_ICT_HouseholdRegister-53]
	_ = x[THOST_FTDC_ICT_Passport-54]
	_ = x[THOST_FTDC_ICT_TaiwanCompatriotIDCard-55]
	_ = x[THOST_FTDC_ICT_HomeComingCard-56]
	_ = x[THOST_FTDC_ICT_LicenseNo-57]
	_ = x[THOST_FTDC_ICT_TaxNo-65]
	_ = x[THOST_FTDC_ICT_HMMainlandTravelPermit-66]
	_ = x[THOST_FTDC_ICT_TwMainlandTravelPermit-67]
	_ = x[THOST_FTDC_ICT_DrivingLicense-68]
	_ = x[THOST_FTDC_ICT_SocialID-70]
	_ = x[THOST_FTDC_ICT_LocalID-71]
	_ = x[THOST_FTDC_ICT_BusinessRegistration-72]
	_ = x[THOST_FTDC_ICT_HKMCIDCard-73]
	_ = x[THOST_FTDC_ICT_AccountsPermits-74]
	_ = x[THOST_FTDC_ICT_FrgPrmtRdCard-75]
	_ = x[THOST_FTDC_ICT_CptMngPrdLetter-76]
	_ = x[THOST_FTDC_ICT_HKMCTwResidencePermit-77]
	_ = x[THOST_FTDC_ICT_UniformSocialCreditCode-78]
	_ = x[THOST_FTDC_ICT_CorporationCertNo-79]
	_ = x[THOST_FTDC_ICT_OtherCard-120]
}

const (
	_TThostFtdcIdCardTypeType_name_0 = "组织机构代码中国公民身份证军官证警官证士兵证户口簿护照台胞证回乡证营业执照号"
	_TThostFtdcIdCardTypeType_name_1 = "税务登记号/当地纳税ID港澳居民来往内地通行证台湾居民来往大陆通行证驾照"
	_TThostFtdcIdCardTypeType_name_2 = "当地社保ID当地身份证商业登记证港澳永久性居民身份证人行开户许可证外国人永久居留证资管产品备案函港澳台居民居住证统一社会信用代码机构成立证明文件"
	_TThostFtdcIdCardTypeType_name_3 = "其他证件"
)

var (
	_TThostFtdcIdCardTypeType_index_0 = [...]uint8{0, 18, 39, 48, 57, 66, 75, 81, 90, 99, 114}
	_TThostFtdcIdCardTypeType_index_1 = [...]uint8{0, 30, 63, 96, 102}
	_TThostFtdcIdCardTypeType_index_2 = [...]uint8{0, 14, 29, 44, 74, 95, 119, 140, 164, 188, 212}
)

func (i TThostFtdcIdCardTypeType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcIdCardTypeType_name_0[_TThostFtdcIdCardTypeType_index_0[i]:_TThostFtdcIdCardTypeType_index_0[i+1]]
	case 65 <= i && i <= 68:
		i -= 65
		return _TThostFtdcIdCardTypeType_name_1[_TThostFtdcIdCardTypeType_index_1[i]:_TThostFtdcIdCardTypeType_index_1[i+1]]
	case 70 <= i && i <= 79:
		i -= 70
		return _TThostFtdcIdCardTypeType_name_2[_TThostFtdcIdCardTypeType_index_2[i]:_TThostFtdcIdCardTypeType_index_2[i+1]]
	case i == 120:
		return _TThostFtdcIdCardTypeType_name_3
	default:
		return "TThostFtdcIdCardTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
