// Code generated by "stringer -type TThostFtdcFBEUserEventTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBEUET_SignIn-48]
	_ = x[THOST_FTDC_FBEUET_Exchange-49]
	_ = x[THOST_FTDC_FBEUET_ReExchange-50]
	_ = x[THOST_FTDC_FBEUET_QueryBankAccount-51]
	_ = x[THOST_FTDC_FBEUET_QueryExchDetial-52]
	_ = x[THOST_FTDC_FBEUET_QueryExchSummary-53]
	_ = x[THOST_FTDC_FBEUET_QueryExchRate-54]
	_ = x[THOST_FTDC_FBEUET_CheckBankAccount-55]
	_ = x[THOST_FTDC_FBEUET_SignOut-56]
	_ = x[THOST_FTDC_FBEUET_Other-90]
}

const (
	_TThostFtdcFBEUserEventTypeType_name_0 = "签到换汇换汇重发银行账户查询换汇明细查询换汇汇总查询换汇汇率查询对账文件通知签退"
	_TThostFtdcFBEUserEventTypeType_name_1 = "其他"
)

var (
	_TThostFtdcFBEUserEventTypeType_index_0 = [...]uint8{0, 6, 12, 24, 42, 60, 78, 96, 114, 120}
)

func (i TThostFtdcFBEUserEventTypeType) String() string {
	switch {
	case 48 <= i && i <= 56:
		i -= 48
		return _TThostFtdcFBEUserEventTypeType_name_0[_TThostFtdcFBEUserEventTypeType_index_0[i]:_TThostFtdcFBEUserEventTypeType_index_0[i+1]]
	case i == 90:
		return _TThostFtdcFBEUserEventTypeType_name_1
	default:
		return "TThostFtdcFBEUserEventTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
