// Code generated by "stringer -type TThostFtdcBusinessClassType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BT_Profit-48]
	_ = x[THOST_FTDC_BT_Loss-49]
	_ = x[THOST_FTDC_BT_Other-90]
}

const (
	_TThostFtdcBusinessClassType_name_0 = "盈利亏损"
	_TThostFtdcBusinessClassType_name_1 = "其他"
)

var (
	_TThostFtdcBusinessClassType_index_0 = [...]uint8{0, 6, 12}
)

func (i TThostFtdcBusinessClassType) String() string {
	switch {
	case 48 <= i && i <= 49:
		i -= 48
		return _TThostFtdcBusinessClassType_name_0[_TThostFtdcBusinessClassType_index_0[i]:_TThostFtdcBusinessClassType_index_0[i+1]]
	case i == 90:
		return _TThostFtdcBusinessClassType_name_1
	default:
		return "TThostFtdcBusinessClassType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
