// Code generated by "stringer -type TThostFtdcFBEAlreadyTradeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBEAT_NotTrade-48]
	_ = x[THOST_FTDC_FBEAT_Trade-49]
}

const _TThostFtdcFBEAlreadyTradeType_name = "未交易已交易"

var _TThostFtdcFBEAlreadyTradeType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcFBEAlreadyTradeType) String() string {
	i -= 48
	if i >= TThostFtdcFBEAlreadyTradeType(len(_TThostFtdcFBEAlreadyTradeType_index)-1) {
		return "TThostFtdcFBEAlreadyTradeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFBEAlreadyTradeType_name[_TThostFtdcFBEAlreadyTradeType_index[i]:_TThostFtdcFBEAlreadyTradeType_index[i+1]]
}
