// Code generated by "stringer -type TThostFtdcAmlCheckLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AMLCL_CheckLevel0-48]
	_ = x[THOST_FTDC_AMLCL_CheckLevel1-49]
	_ = x[THOST_FTDC_AMLCL_CheckLevel2-50]
	_ = x[THOST_FTDC_AMLCL_CheckLevel3-51]
}

const _TThostFtdcAmlCheckLevelType_name = "零级审核一级审核二级审核三级审核"

var _TThostFtdcAmlCheckLevelType_index = [...]uint8{0, 12, 24, 36, 48}

func (i TThostFtdcAmlCheckLevelType) String() string {
	i -= 48
	if i >= TThostFtdcAmlCheckLevelType(len(_TThostFtdcAmlCheckLevelType_index)-1) {
		return "TThostFtdcAmlCheckLevelType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcAmlCheckLevelType_name[_TThostFtdcAmlCheckLevelType_index[i]:_TThostFtdcAmlCheckLevelType_index[i+1]]
}
