// Code generated by "stringer -type TThostFtdcPortfTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EET_None-48]
	_ = x[THOST_FTDC_EET_SPBM_AddOnHedge-49]
}

const _TThostFtdcPortfTypeType_name = "使用初版交易所算法SPBM算法V1.1.0_附加保证金调整"

var _TThostFtdcPortfTypeType_index = [...]uint8{0, 27, 65}

func (i TThostFtdcPortfTypeType) String() string {
	i -= 48
	if i >= TThostFtdcPortfTypeType(len(_TThostFtdcPortfTypeType_index)-1) {
		return "TThostFtdcPortfTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcPortfTypeType_name[_TThostFtdcPortfTypeType_index[i]:_TThostFtdcPortfTypeType_index[i+1]]
}
