// Code generated by "stringer -type TThostFtdcInstStatusEnterReasonType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IER_Automatic-49]
	_ = x[THOST_FTDC_IER_Manual-50]
	_ = x[THOST_FTDC_IER_Fuse-51]
}

const _TThostFtdcInstStatusEnterReasonType_name = "自动切换手动切换熔断"

var _TThostFtdcInstStatusEnterReasonType_index = [...]uint8{0, 12, 24, 30}

func (i TThostFtdcInstStatusEnterReasonType) String() string {
	i -= 49
	if i >= TThostFtdcInstStatusEnterReasonType(len(_TThostFtdcInstStatusEnterReasonType_index)-1) {
		return "TThostFtdcInstStatusEnterReasonType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcInstStatusEnterReasonType_name[_TThostFtdcInstStatusEnterReasonType_index[i]:_TThostFtdcInstStatusEnterReasonType_index[i+1]]
}
