// Code generated by "stringer -type TThostFtdcSystemTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SYT_FutureBankTransfer-48]
	_ = x[THOST_FTDC_SYT_StockBankTransfer-49]
	_ = x[THOST_FTDC_SYT_TheThirdPartStore-50]
}

const _TThostFtdcSystemTypeType_name = "银期转帐银证转帐第三方存管"

var _TThostFtdcSystemTypeType_index = [...]uint8{0, 12, 24, 39}

func (i TThostFtdcSystemTypeType) String() string {
	i -= 48
	if i >= TThostFtdcSystemTypeType(len(_TThostFtdcSystemTypeType_index)-1) {
		return "TThostFtdcSystemTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSystemTypeType_name[_TThostFtdcSystemTypeType_index[i]:_TThostFtdcSystemTypeType_index[i+1]]
}
