// Code generated by "stringer -type TThostFtdcAMLCheckStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AMLCHS_Init-48]
	_ = x[THOST_FTDC_AMLCHS_Checking-49]
	_ = x[THOST_FTDC_AMLCHS_Checked-50]
	_ = x[THOST_FTDC_AMLCHS_RefuseReport-51]
}

const _TThostFtdcAMLCheckStatusType_name = "未复核复核中已复核拒绝上报"

var _TThostFtdcAMLCheckStatusType_index = [...]uint8{0, 9, 18, 27, 39}

func (i TThostFtdcAMLCheckStatusType) String() string {
	i -= 48
	if i >= TThostFtdcAMLCheckStatusType(len(_TThostFtdcAMLCheckStatusType_index)-1) {
		return "TThostFtdcAMLCheckStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcAMLCheckStatusType_name[_TThostFtdcAMLCheckStatusType_index[i]:_TThostFtdcAMLCheckStatusType_index[i+1]]
}
