// Code generated by "stringer -type TThostFtdcFileUploadStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FUS_SucceedUpload-49]
	_ = x[THOST_FTDC_FUS_FailedUpload-50]
	_ = x[THOST_FTDC_FUS_SucceedLoad-51]
	_ = x[THOST_FTDC_FUS_PartSucceedLoad-52]
	_ = x[THOST_FTDC_FUS_FailedLoad-53]
}

const _TThostFtdcFileUploadStatusType_name = "上传成功上传失败导入成功导入部分成功导入失败"

var _TThostFtdcFileUploadStatusType_index = [...]uint8{0, 12, 24, 36, 54, 66}

func (i TThostFtdcFileUploadStatusType) String() string {
	i -= 49
	if i >= TThostFtdcFileUploadStatusType(len(_TThostFtdcFileUploadStatusType_index)-1) {
		return "TThostFtdcFileUploadStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFileUploadStatusType_name[_TThostFtdcFileUploadStatusType_index[i]:_TThostFtdcFileUploadStatusType_index[i+1]]
}
