// Code generated by "stringer -type TThostFtdcRateTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RATETYPE_MarginRate-50]
}

const _TThostFtdcRateTypeType_name = "保证金率"

var _TThostFtdcRateTypeType_index = [...]uint8{0, 12}

func (i TThostFtdcRateTypeType) String() string {
	i -= 50
	if i >= TThostFtdcRateTypeType(len(_TThostFtdcRateTypeType_index)-1) {
		return "TThostFtdcRateTypeType(" + strconv.FormatInt(int64(i+50), 10) + ")"
	}
	return _TThostFtdcRateTypeType_name[_TThostFtdcRateTypeType_index[i]:_TThostFtdcRateTypeType_index[i+1]]
}
