// Code generated by "stringer -type TThostFtdcRateInvestorRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RIR_All-49]
	_ = x[THOST_FTDC_RIR_Model-50]
	_ = x[THOST_FTDC_RIR_Single-51]
}

const _TThostFtdcRateInvestorRangeType_name = "公司标准模板单一投资者"

var _TThostFtdcRateInvestorRangeType_index = [...]uint8{0, 12, 18, 33}

func (i TThostFtdcRateInvestorRangeType) String() string {
	i -= 49
	if i >= TThostFtdcRateInvestorRangeType(len(_TThostFtdcRateInvestorRangeType_index)-1) {
		return "TThostFtdcRateInvestorRangeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcRateInvestorRangeType_name[_TThostFtdcRateInvestorRangeType_index[i]:_TThostFtdcRateInvestorRangeType_index[i+1]]
}
