// Code generated by "stringer -type TThostFtdcTradingRoleType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ER_Broker-49]
	_ = x[THOST_FTDC_ER_Host-50]
	_ = x[THOST_FTDC_ER_Maker-51]
}

const _TThostFtdcTradingRoleType_name = "代理自营做市商"

var _TThostFtdcTradingRoleType_index = [...]uint8{0, 6, 12, 21}

func (i TThostFtdcTradingRoleType) String() string {
	i -= 49
	if i >= TThostFtdcTradingRoleType(len(_TThostFtdcTradingRoleType_index)-1) {
		return "TThostFtdcTradingRoleType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcTradingRoleType_name[_TThostFtdcTradingRoleType_index[i]:_TThostFtdcTradingRoleType_index[i+1]]
}
