// Code generated by "stringer -type TThostFtdcFundTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FT_Deposite-49]
	_ = x[THOST_FTDC_FT_ItemFund-50]
	_ = x[THOST_FTDC_FT_Company-51]
	_ = x[THOST_FTDC_FT_InnerTransfer-52]
}

const _TThostFtdcFundTypeType_name = "银行存款分项资金公司调整资金内转"

var _TThostFtdcFundTypeType_index = [...]uint8{0, 12, 24, 36, 48}

func (i TThostFtdcFundTypeType) String() string {
	i -= 49
	if i >= TThostFtdcFundTypeType(len(_TThostFtdcFundTypeType_index)-1) {
		return "TThostFtdcFundTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundTypeType_name[_TThostFtdcFundTypeType_index[i]:_TThostFtdcFundTypeType_index[i+1]]
}
