// Code generated by "stringer -type TThostFtdcPwdRcdSrcType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PRS_Init-48]
	_ = x[THOST_FTDC_PRS_Sync-49]
	_ = x[THOST_FTDC_PRS_UserUpd-50]
	_ = x[THOST_FTDC_PRS_SuperUserUpd-51]
	_ = x[THOST_FTDC_PRS_SecUpd-52]
}

const _TThostFtdcPwdRcdSrcType_name = "来源于Sync初始化数据来源于实时上场数据来源于用户修改来源于超户修改，很可能来自主席同步数据来源于次席同步的修改"

var _TThostFtdcPwdRcdSrcType_index = [...]uint8{0, 28, 55, 76, 133, 163}

func (i TThostFtdcPwdRcdSrcType) String() string {
	i -= 48
	if i >= TThostFtdcPwdRcdSrcType(len(_TThostFtdcPwdRcdSrcType_index)-1) {
		return "TThostFtdcPwdRcdSrcType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcPwdRcdSrcType_name[_TThostFtdcPwdRcdSrcType_index[i]:_TThostFtdcPwdRcdSrcType_index[i+1]]
}
