// Code generated by "stringer -type TThostFtdcSysOperModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SoM_Add-49]
	_ = x[THOST_FTDC_SoM_Update-50]
	_ = x[THOST_FTDC_SoM_Delete-51]
	_ = x[THOST_FTDC_SoM_Copy-52]
	_ = x[THOST_FTDC_SoM_AcTive-53]
	_ = x[THOST_FTDC_SoM_CanCel-54]
	_ = x[THOST_FTDC_SoM_ReSet-55]
}

const _TThostFtdcSysOperModeType_name = "增加修改删除复制激活注销重置"

var _TThostFtdcSysOperModeType_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42}

func (i TThostFtdcSysOperModeType) String() string {
	i -= 49
	if i >= TThostFtdcSysOperModeType(len(_TThostFtdcSysOperModeType_index)-1) {
		return "TThostFtdcSysOperModeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSysOperModeType_name[_TThostFtdcSysOperModeType_index[i]:_TThostFtdcSysOperModeType_index[i+1]]
}
