// Code generated by "stringer -type TThostFtdcPropertyInvestorRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PIR_All-49]
	_ = x[THOST_FTDC_PIR_Property-50]
	_ = x[THOST_FTDC_PIR_Single-51]
}

const _TThostFtdcPropertyInvestorRangeType_name = "所有投资者属性单一投资者"

var _TThostFtdcPropertyInvestorRangeType_index = [...]uint8{0, 6, 21, 36}

func (i TThostFtdcPropertyInvestorRangeType) String() string {
	i -= 49
	if i >= TThostFtdcPropertyInvestorRangeType(len(_TThostFtdcPropertyInvestorRangeType_index)-1) {
		return "TThostFtdcPropertyInvestorRangeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcPropertyInvestorRangeType_name[_TThostFtdcPropertyInvestorRangeType_index[i]:_TThostFtdcPropertyInvestorRangeType_index[i+1]]
}
