// Code generated by "stringer -type TThostFtdcMonthBillTradeSumType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MBTS_ByInstrument-48]
	_ = x[THOST_FTDC_MBTS_ByDayInsPrc-49]
	_ = x[THOST_FTDC_MBTS_ByDayIns-50]
}

const _TThostFtdcMonthBillTradeSumType_name = "同日同合约同日同合约同价格同合约"

var _TThostFtdcMonthBillTradeSumType_index = [...]uint8{0, 15, 39, 48}

func (i TThostFtdcMonthBillTradeSumType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcMonthBillTradeSumType_index)-1 {
		return "TThostFtdcMonthBillTradeSumType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcMonthBillTradeSumType_name[_TThostFtdcMonthBillTradeSumType_index[idx]:_TThostFtdcMonthBillTradeSumType_index[idx+1]]
}
