// Code generated by "stringer -type TThostFtdcCertificationTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CFT_IDCard-48]
	_ = x[THOST_FTDC_CFT_Passport-49]
	_ = x[THOST_FTDC_CFT_OfficerIDCard-50]
	_ = x[THOST_FTDC_CFT_SoldierIDCard-51]
	_ = x[THOST_FTDC_CFT_HomeComingCard-52]
	_ = x[THOST_FTDC_CFT_HouseholdRegister-53]
	_ = x[THOST_FTDC_CFT_LicenseNo-54]
	_ = x[THOST_FTDC_CFT_InstitutionCodeCard-55]
	_ = x[THOST_FTDC_CFT_TempLicenseNo-56]
	_ = x[THOST_FTDC_CFT_NoEnterpriseLicenseNo-57]
	_ = x[THOST_FTDC_CFT_OtherCard-120]
	_ = x[THOST_FTDC_CFT_SuperDepAgree-97]
}

const (
	_TThostFtdcCertificationTypeType_name_0 = "身份证护照军官证士兵证回乡证户口簿营业执照号组织机构代码证临时营业执照号民办非企业登记证书"
	_TThostFtdcCertificationTypeType_name_1 = "主管部门批文"
	_TThostFtdcCertificationTypeType_name_2 = "其他证件"
)

var (
	_TThostFtdcCertificationTypeType_index_0 = [...]uint8{0, 9, 15, 24, 33, 42, 51, 66, 87, 108, 135}
)

func (i TThostFtdcCertificationTypeType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcCertificationTypeType_name_0[_TThostFtdcCertificationTypeType_index_0[i]:_TThostFtdcCertificationTypeType_index_0[i+1]]
	case i == 97:
		return _TThostFtdcCertificationTypeType_name_1
	case i == 120:
		return _TThostFtdcCertificationTypeType_name_2
	default:
		return "TThostFtdcCertificationTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
