// Code generated by "stringer -type TThostFtdcClassTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_INS_ALL-48]
	_ = x[THOST_FTDC_INS_FUTURE-49]
	_ = x[THOST_FTDC_INS_OPTION-50]
	_ = x[THOST_FTDC_INS_COMB-51]
}

const _TThostFtdcClassTypeType_name = "所有合约期货、即期、期转现、Tas、金属指数合约期货、现货期权合约组合合约"

var _TThostFtdcClassTypeType_index = [...]uint8{0, 12, 66, 93, 105}

func (i TThostFtdcClassTypeType) String() string {
	i -= 48
	if i >= TThostFtdcClassTypeType(len(_TThostFtdcClassTypeType_index)-1) {
		return "TThostFtdcClassTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcClassTypeType_name[_TThostFtdcClassTypeType_index[i]:_TThostFtdcClassTypeType_index[i+1]]
}
