// Code generated by "stringer -type TThostFtdcFBEReqFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBERF_UnProcessed-48]
	_ = x[THOST_FTDC_FBERF_WaitSend-49]
	_ = x[THOST_FTDC_FBERF_SendSuccess-50]
	_ = x[THOST_FTDC_FBERF_SendFailed-51]
	_ = x[THOST_FTDC_FBERF_WaitReSend-52]
}

const _TThostFtdcFBEReqFlagType_name = "未处理等待发送发送成功发送失败等待重发"

var _TThostFtdcFBEReqFlagType_index = [...]uint8{0, 9, 21, 33, 45, 57}

func (i TThostFtdcFBEReqFlagType) String() string {
	i -= 48
	if i >= TThostFtdcFBEReqFlagType(len(_TThostFtdcFBEReqFlagType_index)-1) {
		return "TThostFtdcFBEReqFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFBEReqFlagType_name[_TThostFtdcFBEReqFlagType_index[i]:_TThostFtdcFBEReqFlagType_index[i+1]]
}
