// Code generated by "stringer -type TThostFtdcFreezeStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FRS_Normal-49]
	_ = x[THOST_FTDC_FRS_Freeze-48]
}

const _TThostFtdcFreezeStatusType_name = "休眠活跃"

var _TThostFtdcFreezeStatusType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcFreezeStatusType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcFreezeStatusType_index)-1 {
		return "TThostFtdcFreezeStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcFreezeStatusType_name[_TThostFtdcFreezeStatusType_index[idx]:_TThostFtdcFreezeStatusType_index[idx+1]]
}
