// Code generated by "stringer -type TThostFtdcByInvestorRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BIR_Property-49]
	_ = x[THOST_FTDC_BIR_All-50]
}

const _TThostFtdcByInvestorRangeType_name = "属性统计统计所有"

var _TThostFtdcByInvestorRangeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcByInvestorRangeType) String() string {
	i -= 49
	if i >= TThostFtdcByInvestorRangeType(len(_TThostFtdcByInvestorRangeType_index)-1) {
		return "TThostFtdcByInvestorRangeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcByInvestorRangeType_name[_TThostFtdcByInvestorRangeType_index[i]:_TThostFtdcByInvestorRangeType_index[i+1]]
}
