// Code generated by "stringer -type TThostFtdcCheckStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CHS_Init-48]
	_ = x[THOST_FTDC_CHS_Checking-49]
	_ = x[THOST_FTDC_CHS_Checked-50]
	_ = x[THOST_FTDC_CHS_Refuse-51]
	_ = x[THOST_FTDC_CHS_Cancel-52]
}

const _TThostFtdcCheckStatusType_name = "未复核复核中已复核拒绝作废"

var _TThostFtdcCheckStatusType_index = [...]uint8{0, 9, 18, 27, 33, 39}

func (i TThostFtdcCheckStatusType) String() string {
	i -= 48
	if i >= TThostFtdcCheckStatusType(len(_TThostFtdcCheckStatusType_index)-1) {
		return "TThostFtdcCheckStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCheckStatusType_name[_TThostFtdcCheckStatusType_index[i]:_TThostFtdcCheckStatusType_index[i+1]]
}
