// Code generated by "stringer -type TThostFtdcClientIDStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UOACS_NoApply-49]
	_ = x[THOST_FTDC_UOACS_Submited-50]
	_ = x[THOST_FTDC_UOACS_Sended-51]
	_ = x[THOST_FTDC_UOACS_Success-52]
	_ = x[THOST_FTDC_UOACS_Refuse-53]
	_ = x[THOST_FTDC_UOACS_Cancel-54]
}

const _TThostFtdcClientIDStatusType_name = "未申请已提交申请已发送申请完成拒绝已撤销编码"

var _TThostFtdcClientIDStatusType_index = [...]uint8{0, 9, 24, 39, 45, 51, 66}

func (i TThostFtdcClientIDStatusType) String() string {
	i -= 49
	if i >= TThostFtdcClientIDStatusType(len(_TThostFtdcClientIDStatusType_index)-1) {
		return "TThostFtdcClientIDStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcClientIDStatusType_name[_TThostFtdcClientIDStatusType_index[i]:_TThostFtdcClientIDStatusType_index[i+1]]
}
