// Code generated by "stringer -type TThostFtdcQueryInvestorRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_QIR_All-49]
	_ = x[THOST_FTDC_QIR_Group-50]
	_ = x[THOST_FTDC_QIR_Single-51]
}

const _TThostFtdcQueryInvestorRangeType_name = "所有查询分类单一投资者"

var _TThostFtdcQueryInvestorRangeType_index = [...]uint8{0, 6, 18, 33}

func (i TThostFtdcQueryInvestorRangeType) String() string {
	i -= 49
	if i >= TThostFtdcQueryInvestorRangeType(len(_TThostFtdcQueryInvestorRangeType_index)-1) {
		return "TThostFtdcQueryInvestorRangeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcQueryInvestorRangeType_name[_TThostFtdcQueryInvestorRangeType_index[i]:_TThostFtdcQueryInvestorRangeType_index[i+1]]
}
