// Code generated by "stringer -type TThostFtdcSettArchiveStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SAS_UnArchived-48]
	_ = x[THOST_FTDC_SAS_Archiving-49]
	_ = x[THOST_FTDC_SAS_Archived-50]
	_ = x[THOST_FTDC_SAS_ArchiveFail-51]
}

const _TThostFtdcSettArchiveStatusType_name = "未归档数据数据归档中已归档数据归档数据失败"

var _TThostFtdcSettArchiveStatusType_index = [...]uint8{0, 15, 30, 45, 63}

func (i TThostFtdcSettArchiveStatusType) String() string {
	i -= 48
	if i >= TThostFtdcSettArchiveStatusType(len(_TThostFtdcSettArchiveStatusType_index)-1) {
		return "TThostFtdcSettArchiveStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSettArchiveStatusType_name[_TThostFtdcSettArchiveStatusType_index[i]:_TThostFtdcSettArchiveStatusType_index[i+1]]
}
