// Code generated by "stringer -type TThostFtdcDataSyncStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DS_Asynchronous-49]
	_ = x[THOST_FTDC_DS_Synchronizing-50]
	_ = x[THOST_FTDC_DS_Synchronized-51]
}

const _TThostFtdcDataSyncStatusType_name = "未同步同步中已同步"

var _TThostFtdcDataSyncStatusType_index = [...]uint8{0, 9, 18, 27}

func (i TThostFtdcDataSyncStatusType) String() string {
	i -= 49
	if i >= TThostFtdcDataSyncStatusType(len(_TThostFtdcDataSyncStatusType_index)-1) {
		return "TThostFtdcDataSyncStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcDataSyncStatusType_name[_TThostFtdcDataSyncStatusType_index[i]:_TThostFtdcDataSyncStatusType_index[i+1]]
}
