// Code generated by "stringer -type TThostFtdcQuestionTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_QT_Radio-49]
	_ = x[THOST_FTDC_QT_Option-50]
	_ = x[THOST_FTDC_QT_Blank-51]
}

const _TThostFtdcQuestionTypeType_name = "单选多选填空"

var _TThostFtdcQuestionTypeType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcQuestionTypeType) String() string {
	i -= 49
	if i >= TThostFtdcQuestionTypeType(len(_TThostFtdcQuestionTypeType_index)-1) {
		return "TThostFtdcQuestionTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcQuestionTypeType_name[_TThostFtdcQuestionTypeType_index[i]:_TThostFtdcQuestionTypeType_index[i+1]]
}
