// Code generated by "stringer -type TThostFtdcSHFEUploadFileNameType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SUFN_SUFN_O-79]
	_ = x[THOST_FTDC_SUFN_SUFN_T-84]
	_ = x[THOST_FTDC_SUFN_SUFN_P-80]
	_ = x[THOST_FTDC_SUFN_SUFN_F-70]
}

const (
	_TThostFtdcSHFEUploadFileNameType_name_0 = "^\\d{4}_\\d{8}_\\d{8}_Capital"
	_TThostFtdcSHFEUploadFileNameType_name_1 = "^\\d{4}_\\d{8}_\\d{8}_DailyFundChg^\\d{4}_\\d{8}_\\d{8}_SettlementDetail"
	_TThostFtdcSHFEUploadFileNameType_name_2 = "^\\d{4}_\\d{8}_\\d{8}_Trade"
)

var (
	_TThostFtdcSHFEUploadFileNameType_index_1 = [...]uint8{0, 31, 66}
)

func (i TThostFtdcSHFEUploadFileNameType) String() string {
	switch {
	case i == 70:
		return _TThostFtdcSHFEUploadFileNameType_name_0
	case 79 <= i && i <= 80:
		i -= 79
		return _TThostFtdcSHFEUploadFileNameType_name_1[_TThostFtdcSHFEUploadFileNameType_index_1[i]:_TThostFtdcSHFEUploadFileNameType_index_1[i+1]]
	case i == 84:
		return _TThostFtdcSHFEUploadFileNameType_name_2
	default:
		return "TThostFtdcSHFEUploadFileNameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
