// Code generated by "stringer -type TThostFtdcBrokerDataSyncStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BDS_Synchronized-49]
	_ = x[THOST_FTDC_BDS_Synchronizing-50]
}

const _TThostFtdcBrokerDataSyncStatusType_name = "已同步同步中"

var _TThostFtdcBrokerDataSyncStatusType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcBrokerDataSyncStatusType) String() string {
	i -= 49
	if i >= TThostFtdcBrokerDataSyncStatusType(len(_TThostFtdcBrokerDataSyncStatusType_index)-1) {
		return "TThostFtdcBrokerDataSyncStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcBrokerDataSyncStatusType_name[_TThostFtdcBrokerDataSyncStatusType_index[i]:_TThostFtdcBrokerDataSyncStatusType_index[i+1]]
}
