// Code generated by "stringer -type TThostFtdcSettleManagerGroupType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SMG_Exhcange-49]
	_ = x[THOST_FTDC_SMG_ASP-50]
	_ = x[THOST_FTDC_SMG_CSRC-51]
}

const _TThostFtdcSettleManagerGroupType_name = "交易所核对内部核对上报数据核对"

var _TThostFtdcSettleManagerGroupType_index = [...]uint8{0, 15, 27, 45}

func (i TThostFtdcSettleManagerGroupType) String() string {
	i -= 49
	if i >= TThostFtdcSettleManagerGroupType(len(_TThostFtdcSettleManagerGroupType_index)-1) {
		return "TThostFtdcSettleManagerGroupType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSettleManagerGroupType_name[_TThostFtdcSettleManagerGroupType_index[i]:_TThostFtdcSettleManagerGroupType_index[i+1]]
}
