// Code generated by "stringer -type TThostFtdcBasisPriceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IPT_LastSettlement-49]
	_ = x[THOST_FTDC_IPT_LaseClose-50]
}

const _TThostFtdcBasisPriceTypeType_name = "上一合约结算价上一合约收盘价"

var _TThostFtdcBasisPriceTypeType_index = [...]uint8{0, 21, 42}

func (i TThostFtdcBasisPriceTypeType) String() string {
	i -= 49
	if i >= TThostFtdcBasisPriceTypeType(len(_TThostFtdcBasisPriceTypeType_index)-1) {
		return "TThostFtdcBasisPriceTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcBasisPriceTypeType_name[_TThostFtdcBasisPriceTypeType_index[i]:_TThostFtdcBasisPriceTypeType_index[i+1]]
}
