// Code generated by "stringer -type TThostFtdcUOAAutoSendType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UOAA_ASR-49]
	_ = x[THOST_FTDC_UOAA_ASNR-50]
	_ = x[THOST_FTDC_UOAA_NSAR-51]
	_ = x[THOST_FTDC_UOAA_NSR-52]
}

const _TThostFtdcUOAAutoSendType_name = "自动发送并接收自动发送，不自动接收不自动发送，自动接收不自动发送，也不自动接收"

var _TThostFtdcUOAAutoSendType_index = [...]uint8{0, 21, 51, 81, 117}

func (i TThostFtdcUOAAutoSendType) String() string {
	i -= 49
	if i >= TThostFtdcUOAAutoSendType(len(_TThostFtdcUOAAutoSendType_index)-1) {
		return "TThostFtdcUOAAutoSendType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcUOAAutoSendType_name[_TThostFtdcUOAAutoSendType_index[i]:_TThostFtdcUOAAutoSendType_index[i+1]]
}
