// Code generated by "stringer -type TThostFtdcMortgageTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MT_Out-48]
	_ = x[THOST_FTDC_MT_In-49]
}

const _TThostFtdcMortgageTypeType_name = "质出质入"

var _TThostFtdcMortgageTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcMortgageTypeType) String() string {
	i -= 48
	if i >= TThostFtdcMortgageTypeType(len(_TThostFtdcMortgageTypeType_index)-1) {
		return "TThostFtdcMortgageTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcMortgageTypeType_name[_TThostFtdcMortgageTypeType_index[i]:_TThostFtdcMortgageTypeType_index[i+1]]
}
