// Code generated by "stringer -type TThostFtdcSyncDataStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SDS_Initialize-48]
	_ = x[THOST_FTDC_SDS_Settlementing-49]
	_ = x[THOST_FTDC_SDS_Settlemented-50]
}

const _TThostFtdcSyncDataStatusType_name = "未同步同步中已同步"

var _TThostFtdcSyncDataStatusType_index = [...]uint8{0, 9, 18, 27}

func (i TThostFtdcSyncDataStatusType) String() string {
	i -= 48
	if i >= TThostFtdcSyncDataStatusType(len(_TThostFtdcSyncDataStatusType_index)-1) {
		return "TThostFtdcSyncDataStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSyncDataStatusType_name[_TThostFtdcSyncDataStatusType_index[i]:_TThostFtdcSyncDataStatusType_index[i+1]]
}
