// Code generated by "stringer -type TThostFtdcOrganStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OS_Ready-48]
	_ = x[THOST_FTDC_OS_CheckIn-49]
	_ = x[THOST_FTDC_OS_CheckOut-50]
	_ = x[THOST_FTDC_OS_CheckFileArrived-51]
	_ = x[THOST_FTDC_OS_CheckDetail-52]
	_ = x[THOST_FTDC_OS_DayEndClean-53]
	_ = x[THOST_FTDC_OS_Invalid-57]
}

const (
	_TThostFtdcOrganStatusType_name_0 = "启用签到签退对帐文件到达对帐日终清理"
	_TThostFtdcOrganStatusType_name_1 = "注销"
)

var (
	_TThostFtdcOrganStatusType_index_0 = [...]uint8{0, 6, 12, 18, 36, 42, 54}
)

func (i TThostFtdcOrganStatusType) String() string {
	switch {
	case 48 <= i && i <= 53:
		i -= 48
		return _TThostFtdcOrganStatusType_name_0[_TThostFtdcOrganStatusType_index_0[i]:_TThostFtdcOrganStatusType_index_0[i+1]]
	case i == 57:
		return _TThostFtdcOrganStatusType_name_1
	default:
		return "TThostFtdcOrganStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
