// Code generated by "stringer -type TThostFtdcLimitUseTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_LUT_Repeatable-49]
	_ = x[THOST_FTDC_LUT_Unrepeatable-50]
}

const _TThostFtdcLimitUseTypeType_name = "可重复使用不可重复使用"

var _TThostFtdcLimitUseTypeType_index = [...]uint8{0, 15, 33}

func (i TThostFtdcLimitUseTypeType) String() string {
	i -= 49
	if i >= TThostFtdcLimitUseTypeType(len(_TThostFtdcLimitUseTypeType_index)-1) {
		return "TThostFtdcLimitUseTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcLimitUseTypeType_name[_TThostFtdcLimitUseTypeType_index[i]:_TThostFtdcLimitUseTypeType_index[i+1]]
}
