// Code generated by "stringer -type TThostFtdcSendTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UOAST_NoSend-48]
	_ = x[THOST_FTDC_UOAST_Sended-49]
	_ = x[THOST_FTDC_UOAST_Generated-50]
	_ = x[THOST_FTDC_UOAST_SendFail-51]
	_ = x[THOST_FTDC_UOAST_Success-52]
	_ = x[THOST_FTDC_UOAST_Fail-53]
	_ = x[THOST_FTDC_UOAST_Cancel-54]
}

const _TThostFtdcSendTypeType_name = "未发送已发送已生成报送失败接收成功接收失败取消报送"

var _TThostFtdcSendTypeType_index = [...]uint8{0, 9, 18, 27, 39, 51, 63, 75}

func (i TThostFtdcSendTypeType) String() string {
	i -= 48
	if i >= TThostFtdcSendTypeType(len(_TThostFtdcSendTypeType_index)-1) {
		return "TThostFtdcSendTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSendTypeType_name[_TThostFtdcSendTypeType_index[i]:_TThostFtdcSendTypeType_index[i+1]]
}
