// Code generated by "stringer -type TThostFtdcBalanceAlgorithmType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BLAG_Default-49]
	_ = x[THOST_FTDC_BLAG_IncludeOptValLost-50]
}

const _TThostFtdcBalanceAlgorithmType_name = "不计算期权市值盈亏计算期权市值亏损"

var _TThostFtdcBalanceAlgorithmType_index = [...]uint8{0, 27, 51}

func (i TThostFtdcBalanceAlgorithmType) String() string {
	i -= 49
	if i >= TThostFtdcBalanceAlgorithmType(len(_TThostFtdcBalanceAlgorithmType_index)-1) {
		return "TThostFtdcBalanceAlgorithmType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcBalanceAlgorithmType_name[_TThostFtdcBalanceAlgorithmType_index[i]:_TThostFtdcBalanceAlgorithmType_index[i+1]]
}
