// Code generated by "stringer -type TThostFtdcCusAccountTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CAT_Futures-49]
	_ = x[THOST_FTDC_CAT_AssetmgrFuture-50]
	_ = x[THOST_FTDC_CAT_AssetmgrTrustee-51]
	_ = x[THOST_FTDC_CAT_AssetmgrTransfer-52]
}

const _TThostFtdcCusAccountTypeType_name = "期货结算账户纯期货资管业务下的资管结算账户综合类资管业务下的期货资管托管账户综合类资管业务下的资金中转账户"

var _TThostFtdcCusAccountTypeType_index = [...]uint8{0, 18, 63, 114, 159}

func (i TThostFtdcCusAccountTypeType) String() string {
	i -= 49
	if i >= TThostFtdcCusAccountTypeType(len(_TThostFtdcCusAccountTypeType_index)-1) {
		return "TThostFtdcCusAccountTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcCusAccountTypeType_name[_TThostFtdcCusAccountTypeType_index[i]:_TThostFtdcCusAccountTypeType_index[i+1]]
}
