// Code generated by "stringer -type TThostFtdcCheckInstrTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CIT_HasExch-48]
	_ = x[THOST_FTDC_CIT_HasATP-49]
	_ = x[THOST_FTDC_CIT_HasDiff-50]
}

const _TThostFtdcCheckInstrTypeType_name = "合约交易所不存在合约本系统不存在合约比较不一致"

var _TThostFtdcCheckInstrTypeType_index = [...]uint8{0, 24, 48, 69}

func (i TThostFtdcCheckInstrTypeType) String() string {
	i -= 48
	if i >= TThostFtdcCheckInstrTypeType(len(_TThostFtdcCheckInstrTypeType_index)-1) {
		return "TThostFtdcCheckInstrTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCheckInstrTypeType_name[_TThostFtdcCheckInstrTypeType_index[i]:_TThostFtdcCheckInstrTypeType_index[i+1]]
}
