// Code generated by "stringer -type TThostFtdcOpenOrDestroyType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OOD_Open-49]
	_ = x[THOST_FTDC_OOD_Destroy-48]
}

const _TThostFtdcOpenOrDestroyType_name = "销户开户"

var _TThostFtdcOpenOrDestroyType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcOpenOrDestroyType) String() string {
	i -= 48
	if i >= TThostFtdcOpenOrDestroyType(len(_TThostFtdcOpenOrDestroyType_index)-1) {
		return "TThostFtdcOpenOrDestroyType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOpenOrDestroyType_name[_TThostFtdcOpenOrDestroyType_index[i]:_TThostFtdcOpenOrDestroyType_index[i+1]]
}
