// Code generated by "stringer -type TThostFtdcDBOperationType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DBOP_Insert-48]
	_ = x[THOST_FTDC_DBOP_Update-49]
	_ = x[THOST_FTDC_DBOP_Delete-50]
}

const _TThostFtdcDBOperationType_name = "插入更新删除"

var _TThostFtdcDBOperationType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcDBOperationType) String() string {
	i -= 48
	if i >= TThostFtdcDBOperationType(len(_TThostFtdcDBOperationType_index)-1) {
		return "TThostFtdcDBOperationType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcDBOperationType_name[_TThostFtdcDBOperationType_index[i]:_TThostFtdcDBOperationType_index[i+1]]
}
