// Code generated by "stringer -type TThostFtdcVirementAvailAbilityType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VAA_NoAvailAbility-48]
	_ = x[THOST_FTDC_VAA_AvailAbility-49]
	_ = x[THOST_FTDC_VAA_Repeal-50]
}

const _TThostFtdcVirementAvailAbilityType_name = "未确认有效冲正"

var _TThostFtdcVirementAvailAbilityType_index = [...]uint8{0, 9, 15, 21}

func (i TThostFtdcVirementAvailAbilityType) String() string {
	i -= 48
	if i >= TThostFtdcVirementAvailAbilityType(len(_TThostFtdcVirementAvailAbilityType_index)-1) {
		return "TThostFtdcVirementAvailAbilityType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcVirementAvailAbilityType_name[_TThostFtdcVirementAvailAbilityType_index[i]:_TThostFtdcVirementAvailAbilityType_index[i+1]]
}
