// Code generated by "stringer -type TThostFtdcOrgSystemIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ORGS_Standard-48]
	_ = x[THOST_FTDC_ORGS_ESunny-49]
	_ = x[THOST_FTDC_ORGS_KingStarV6-50]
}

const _TThostFtdcOrgSystemIDType_name = "综合交易平台易盛系统金仕达V6系统"

var _TThostFtdcOrgSystemIDType_index = [...]uint8{0, 18, 30, 47}

func (i TThostFtdcOrgSystemIDType) String() string {
	i -= 48
	if i >= TThostFtdcOrgSystemIDType(len(_TThostFtdcOrgSystemIDType_index)-1) {
		return "TThostFtdcOrgSystemIDType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOrgSystemIDType_name[_TThostFtdcOrgSystemIDType_index[i]:_TThostFtdcOrgSystemIDType_index[i+1]]
}
