// Code generated by "stringer -type TThostFtdcBankRepealFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BRF_BankNotNeedRepeal-48]
	_ = x[THOST_FTDC_BRF_BankWaitingRepeal-49]
	_ = x[THOST_FTDC_BRF_BankBeenRepealed-50]
}

const _TThostFtdcBankRepealFlagType_name = "银行无需自动冲正银行待自动冲正银行已自动冲正"

var _TThostFtdcBankRepealFlagType_index = [...]uint8{0, 24, 45, 66}

func (i TThostFtdcBankRepealFlagType) String() string {
	i -= 48
	if i >= TThostFtdcBankRepealFlagType(len(_TThostFtdcBankRepealFlagType_index)-1) {
		return "TThostFtdcBankRepealFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcBankRepealFlagType_name[_TThostFtdcBankRepealFlagType_index[i]:_TThostFtdcBankRepealFlagType_index[i+1]]
}
