// Code generated by "stringer -type TThostFtdcOrderSubmitStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OSS_InsertSubmitted-48]
	_ = x[THOST_FTDC_OSS_CancelSubmitted-49]
	_ = x[THOST_FTDC_OSS_ModifySubmitted-50]
	_ = x[THOST_FTDC_OSS_Accepted-51]
	_ = x[THOST_FTDC_OSS_InsertRejected-52]
	_ = x[THOST_FTDC_OSS_CancelRejected-53]
	_ = x[THOST_FTDC_OSS_ModifyRejected-54]
}

const _TThostFtdcOrderSubmitStatusType_name = "已经提交撤单已经提交修改已经提交已经接受报单已经被拒绝撤单已经被拒绝改单已经被拒绝"

var _TThostFtdcOrderSubmitStatusType_index = [...]uint8{0, 12, 30, 48, 60, 81, 102, 123}

func (i TThostFtdcOrderSubmitStatusType) String() string {
	i -= 48
	if i >= TThostFtdcOrderSubmitStatusType(len(_TThostFtdcOrderSubmitStatusType_index)-1) {
		return "TThostFtdcOrderSubmitStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOrderSubmitStatusType_name[_TThostFtdcOrderSubmitStatusType_index[i]:_TThostFtdcOrderSubmitStatusType_index[i+1]]
}
