// Code generated by "stringer -type TThostFtdcWithDrawParamIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_WDPID_CashIn-67]
}

const _TThostFtdcWithDrawParamIDType_name = "权利金收支是否可提 1 代表可提 0 不可提"

var _TThostFtdcWithDrawParamIDType_index = [...]uint8{0, 54}

func (i TThostFtdcWithDrawParamIDType) String() string {
	i -= 67
	if i >= TThostFtdcWithDrawParamIDType(len(_TThostFtdcWithDrawParamIDType_index)-1) {
		return "TThostFtdcWithDrawParamIDType(" + strconv.FormatInt(int64(i+67), 10) + ")"
	}
	return _TThostFtdcWithDrawParamIDType_name[_TThostFtdcWithDrawParamIDType_index[i]:_TThostFtdcWithDrawParamIDType_index[i+1]]
}
