// Code generated by "stringer -type TThostFtdcVirementStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VMS_Natural-48]
	_ = x[THOST_FTDC_VMS_Canceled-57]
}

const (
	_TThostFtdcVirementStatusType_name_0 = "正常"
	_TThostFtdcVirementStatusType_name_1 = "销户"
)

func (i TThostFtdcVirementStatusType) String() string {
	switch {
	case i == 48:
		return _TThostFtdcVirementStatusType_name_0
	case i == 57:
		return _TThostFtdcVirementStatusType_name_1
	default:
		return "TThostFtdcVirementStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
