// Code generated by "stringer -type TThostFtdcBankAccStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BAS_Normal-48]
	_ = x[THOST_FTDC_BAS_Freeze-49]
	_ = x[THOST_FTDC_BAS_ReportLoss-50]
}

const _TThostFtdcBankAccStatusType_name = "正常冻结挂失"

var _TThostFtdcBankAccStatusType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcBankAccStatusType) String() string {
	i -= 48
	if i >= TThostFtdcBankAccStatusType(len(_TThostFtdcBankAccStatusType_index)-1) {
		return "TThostFtdcBankAccStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcBankAccStatusType_name[_TThostFtdcBankAccStatusType_index[i]:_TThostFtdcBankAccStatusType_index[i+1]]
}
