// Code generated by "stringer -type TThostFtdcTxnEndFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TEF_NormalProcessing-48]
	_ = x[THOST_FTDC_TEF_Success-49]
	_ = x[THOST_FTDC_TEF_Failed-50]
	_ = x[THOST_FTDC_TEF_Abnormal-51]
	_ = x[THOST_FTDC_TEF_ManualProcessedForException-52]
	_ = x[THOST_FTDC_TEF_CommuFailedNeedManualProcess-53]
	_ = x[THOST_FTDC_TEF_SysErrorNeedManualProcess-54]
}

const _TThostFtdcTxnEndFlagType_name = "正常处理中成功结束失败结束异常中已人工异常处理通讯异常 ，请人工处理系统出错，请人工处理"

var _TThostFtdcTxnEndFlagType_index = [...]uint8{0, 15, 27, 39, 48, 69, 100, 130}

func (i TThostFtdcTxnEndFlagType) String() string {
	i -= 48
	if i >= TThostFtdcTxnEndFlagType(len(_TThostFtdcTxnEndFlagType_index)-1) {
		return "TThostFtdcTxnEndFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcTxnEndFlagType_name[_TThostFtdcTxnEndFlagType_index[i]:_TThostFtdcTxnEndFlagType_index[i+1]]
}
