// Code generated by "stringer -type TThostFtdcBackUpStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BUS_UnBak-48]
	_ = x[THOST_FTDC_BUS_BakUp-49]
	_ = x[THOST_FTDC_BUS_BakUped-50]
	_ = x[THOST_FTDC_BUS_BakFail-51]
}

const _TThostFtdcBackUpStatusType_name = "未生成备份数据备份数据生成中已生成备份数据备份数据失败"

var _TThostFtdcBackUpStatusType_index = [...]uint8{0, 21, 42, 63, 81}

func (i TThostFtdcBackUpStatusType) String() string {
	i -= 48
	if i >= TThostFtdcBackUpStatusType(len(_TThostFtdcBackUpStatusType_index)-1) {
		return "TThostFtdcBackUpStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcBackUpStatusType_name[_TThostFtdcBackUpStatusType_index[i]:_TThostFtdcBackUpStatusType_index[i+1]]
}
