// Code generated by "stringer -type TThostFtdcYesNoIndicatorType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_YNI_Yes-48]
	_ = x[THOST_FTDC_YNI_No-49]
}

const _TThostFtdcYesNoIndicatorType_name = "是否"

var _TThostFtdcYesNoIndicatorType_index = [...]uint8{0, 3, 6}

func (i TThostFtdcYesNoIndicatorType) String() string {
	i -= 48
	if i >= TThostFtdcYesNoIndicatorType(len(_TThostFtdcYesNoIndicatorType_index)-1) {
		return "TThostFtdcYesNoIndicatorType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcYesNoIndicatorType_name[_TThostFtdcYesNoIndicatorType_index[i]:_TThostFtdcYesNoIndicatorType_index[i+1]]
}
