// Code generated by "stringer -type TThostFtdcExecOrderPositionFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EOPF_Reserve-48]
	_ = x[THOST_FTDC_EOPF_UnReserve-49]
}

const _TThostFtdcExecOrderPositionFlagType_name = "保留不保留"

var _TThostFtdcExecOrderPositionFlagType_index = [...]uint8{0, 6, 15}

func (i TThostFtdcExecOrderPositionFlagType) String() string {
	i -= 48
	if i >= TThostFtdcExecOrderPositionFlagType(len(_TThostFtdcExecOrderPositionFlagType_index)-1) {
		return "TThostFtdcExecOrderPositionFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcExecOrderPositionFlagType_name[_TThostFtdcExecOrderPositionFlagType_index[i]:_TThostFtdcExecOrderPositionFlagType_index[i+1]]
}
