// Code generated by "stringer -type TThostFtdcFileGenStyleType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FGS_FileTransmit-48]
	_ = x[THOST_FTDC_FGS_FileGen-49]
}

const _TThostFtdcFileGenStyleType_name = "下发生成"

var _TThostFtdcFileGenStyleType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcFileGenStyleType) String() string {
	i -= 48
	if i >= TThostFtdcFileGenStyleType(len(_TThostFtdcFileGenStyleType_index)-1) {
		return "TThostFtdcFileGenStyleType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFileGenStyleType_name[_TThostFtdcFileGenStyleType_index[i]:_TThostFtdcFileGenStyleType_index[i+1]]
}
