// Code generated by "stringer -type TThostFtdcApplyStatusIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ASID_NoComplete-49]
	_ = x[THOST_FTDC_ASID_Submited-50]
	_ = x[THOST_FTDC_ASID_Checked-51]
	_ = x[THOST_FTDC_ASID_Refused-52]
	_ = x[THOST_FTDC_ASID_Deleted-53]
}

const _TThostFtdcApplyStatusIDType_name = "未补全已提交已审核已拒绝已删除"

var _TThostFtdcApplyStatusIDType_index = [...]uint8{0, 9, 18, 27, 36, 45}

func (i TThostFtdcApplyStatusIDType) String() string {
	i -= 49
	if i >= TThostFtdcApplyStatusIDType(len(_TThostFtdcApplyStatusIDType_index)-1) {
		return "TThostFtdcApplyStatusIDType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcApplyStatusIDType_name[_TThostFtdcApplyStatusIDType_index[i]:_TThostFtdcApplyStatusIDType_index[i+1]]
}
