// Code generated by "stringer -type TThostFtdcExchangeIDTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EIDT_SHFE-83]
	_ = x[THOST_FTDC_EIDT_CZCE-90]
	_ = x[THOST_FTDC_EIDT_DCE-68]
	_ = x[THOST_FTDC_EIDT_CFFEX-74]
	_ = x[THOST_FTDC_EIDT_INE-78]
}

const (
	_TThostFtdcExchangeIDTypeType_name_0 = "大连商品交易所"
	_TThostFtdcExchangeIDTypeType_name_1 = "中国金融期货交易所"
	_TThostFtdcExchangeIDTypeType_name_2 = "上海国际能源交易中心股份有限公司"
	_TThostFtdcExchangeIDTypeType_name_3 = "上海期货交易所"
	_TThostFtdcExchangeIDTypeType_name_4 = "郑州商品交易所"
)

func (i TThostFtdcExchangeIDTypeType) String() string {
	switch {
	case i == 68:
		return _TThostFtdcExchangeIDTypeType_name_0
	case i == 74:
		return _TThostFtdcExchangeIDTypeType_name_1
	case i == 78:
		return _TThostFtdcExchangeIDTypeType_name_2
	case i == 83:
		return _TThostFtdcExchangeIDTypeType_name_3
	case i == 90:
		return _TThostFtdcExchangeIDTypeType_name_4
	default:
		return "TThostFtdcExchangeIDTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
