// Code generated by "stringer -type TThostFtdcOTPStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OTPS_Unused-48]
	_ = x[THOST_FTDC_OTPS_Used-49]
	_ = x[THOST_FTDC_OTPS_Disuse-50]
}

const _TThostFtdcOTPStatusType_name = "未使用已使用注销"

var _TThostFtdcOTPStatusType_index = [...]uint8{0, 9, 18, 24}

func (i TThostFtdcOTPStatusType) String() string {
	i -= 48
	if i >= TThostFtdcOTPStatusType(len(_TThostFtdcOTPStatusType_index)-1) {
		return "TThostFtdcOTPStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOTPStatusType_name[_TThostFtdcOTPStatusType_index[i]:_TThostFtdcOTPStatusType_index[i+1]]
}
