// Code generated by "stringer -type TThostFtdcMarginPriceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MPT_PreSettlementPrice-49]
	_ = x[THOST_FTDC_MPT_SettlementPrice-50]
	_ = x[THOST_FTDC_MPT_AveragePrice-51]
	_ = x[THOST_FTDC_MPT_OpenPrice-52]
}

const _TThostFtdcMarginPriceTypeType_name = "昨结算价最新价成交均价开仓价"

var _TThostFtdcMarginPriceTypeType_index = [...]uint8{0, 12, 21, 33, 42}

func (i TThostFtdcMarginPriceTypeType) String() string {
	i -= 49
	if i >= TThostFtdcMarginPriceTypeType(len(_TThostFtdcMarginPriceTypeType_index)-1) {
		return "TThostFtdcMarginPriceTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcMarginPriceTypeType_name[_TThostFtdcMarginPriceTypeType_index[i]:_TThostFtdcMarginPriceTypeType_index[i+1]]
}
