// Code generated by "stringer -type TThostFtdcClientTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CfMMCCT_All-48]
	_ = x[THOST_FTDC_CfMMCCT_Person-49]
	_ = x[THOST_FTDC_CfMMCCT_Company-50]
	_ = x[THOST_FTDC_CfMMCCT_Other-51]
	_ = x[THOST_FTDC_CfMMCCT_SpecialOrgan-52]
	_ = x[THOST_FTDC_CfMMCCT_Asset-53]
}

const _TThostFtdcClientTypeType_name = "所有个人单位其他特殊法人资管户"

var _TThostFtdcClientTypeType_index = [...]uint8{0, 6, 12, 18, 24, 36, 45}

func (i TThostFtdcClientTypeType) String() string {
	i -= 48
	if i >= TThostFtdcClientTypeType(len(_TThostFtdcClientTypeType_index)-1) {
		return "TThostFtdcClientTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcClientTypeType_name[_TThostFtdcClientTypeType_index[i]:_TThostFtdcClientTypeType_index[i+1]]
}
