// Code generated by "stringer -type TThostFtdcSyncModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SRM_ASync-48]
	_ = x[THOST_FTDC_SRM_Sync-49]
}

const _TThostFtdcSyncModeType_name = "异步同步"

var _TThostFtdcSyncModeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcSyncModeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcSyncModeType_index)-1 {
		return "TThostFtdcSyncModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcSyncModeType_name[_TThostFtdcSyncModeType_index[idx]:_TThostFtdcSyncModeType_index[idx+1]]
}
