// Code generated by "stringer -type TThostFtdcFundIOTypeEnType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FIOTEN_FundIO-49]
	_ = x[THOST_FTDC_FIOTEN_Transfer-50]
	_ = x[THOST_FTDC_FIOTEN_SwapCurrency-51]
}

const _TThostFtdcFundIOTypeEnType_name = "DepositWithdrawalBank-Futures TransferBank-Futures FX Exchange"

var _TThostFtdcFundIOTypeEnType_index = [...]uint8{0, 17, 38, 62}

func (i TThostFtdcFundIOTypeEnType) String() string {
	i -= 49
	if i >= TThostFtdcFundIOTypeEnType(len(_TThostFtdcFundIOTypeEnType_index)-1) {
		return "TThostFtdcFundIOTypeEnType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundIOTypeEnType_name[_TThostFtdcFundIOTypeEnType_index[i]:_TThostFtdcFundIOTypeEnType_index[i+1]]
}
