// Code generated by "stringer -type TThostFtdcAddrVerType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ADV_V4-48]
	_ = x[THOST_FTDC_ADV_V6-49]
}

const _TThostFtdcAddrVerType_name = "IPV4IPV6"

var _TThostFtdcAddrVerType_index = [...]uint8{0, 4, 8}

func (i TThostFtdcAddrVerType) String() string {
	i -= 48
	if i >= TThostFtdcAddrVerType(len(_TThostFtdcAddrVerType_index)-1) {
		return "TThostFtdcAddrVerType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcAddrVerType_name[_TThostFtdcAddrVerType_index[i]:_TThostFtdcAddrVerType_index[i+1]]
}
