// Code generated by "stringer -type TThostFtdcFBTEncryModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EM_NoEncry-48]
	_ = x[THOST_FTDC_EM_DES-49]
	_ = x[THOST_FTDC_EM_3DES-50]
}

const _TThostFtdcFBTEncryModeType_name = "不加密DES3DES"

var _TThostFtdcFBTEncryModeType_index = [...]uint8{0, 9, 12, 16}

func (i TThostFtdcFBTEncryModeType) String() string {
	i -= 48
	if i >= TThostFtdcFBTEncryModeType(len(_TThostFtdcFBTEncryModeType_index)-1) {
		return "TThostFtdcFBTEncryModeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFBTEncryModeType_name[_TThostFtdcFBTEncryModeType_index[i]:_TThostFtdcFBTEncryModeType_index[i+1]]
}
