// Code generated by "stringer -type TThostFtdcDataStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AMLDS_Normal-48]
	_ = x[THOST_FTDC_AMLDS_Deleted-49]
}

const _TThostFtdcDataStatusType_name = "正常已删除"

var _TThostFtdcDataStatusType_index = [...]uint8{0, 6, 15}

func (i TThostFtdcDataStatusType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcDataStatusType_index)-1 {
		return "TThostFtdcDataStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcDataStatusType_name[_TThostFtdcDataStatusType_index[idx]:_TThostFtdcDataStatusType_index[idx+1]]
}
