// Code generated by "stringer -type TThostFtdcExStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EXS_Before-48]
	_ = x[THOST_FTDC_EXS_After-49]
}

const _TThostFtdcExStatusType_name = "修改前修改后"

var _TThostFtdcExStatusType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcExStatusType) String() string {
	i -= 48
	if i >= TThostFtdcExStatusType(len(_TThostFtdcExStatusType_index)-1) {
		return "TThostFtdcExStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcExStatusType_name[_TThostFtdcExStatusType_index[i]:_TThostFtdcExStatusType_index[i+1]]
}
