// Code generated by "stringer -type TThostFtdcSpecialCreateRuleType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SC_NoSpecialRule-48]
	_ = x[THOST_FTDC_SC_NoSpringFestival-49]
}

const _TThostFtdcSpecialCreateRuleType_name = "没有特殊创建规则不包含春节"

var _TThostFtdcSpecialCreateRuleType_index = [...]uint8{0, 24, 39}

func (i TThostFtdcSpecialCreateRuleType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcSpecialCreateRuleType_index)-1 {
		return "TThostFtdcSpecialCreateRuleType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcSpecialCreateRuleType_name[_TThostFtdcSpecialCreateRuleType_index[idx]:_TThostFtdcSpecialCreateRuleType_index[idx+1]]
}
