// Code generated by "stringer -type TThostFtdcFundMortDirectionEnType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FMDEN_In-49]
	_ = x[THOST_FTDC_FMDEN_Out-50]
}

const _TThostFtdcFundMortDirectionEnType_name = "PledgeRedemption"

var _TThostFtdcFundMortDirectionEnType_index = [...]uint8{0, 6, 16}

func (i TThostFtdcFundMortDirectionEnType) String() string {
	i -= 49
	if i >= TThostFtdcFundMortDirectionEnType(len(_TThostFtdcFundMortDirectionEnType_index)-1) {
		return "TThostFtdcFundMortDirectionEnType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundMortDirectionEnType_name[_TThostFtdcFundMortDirectionEnType_index[i]:_TThostFtdcFundMortDirectionEnType_index[i+1]]
}
