// Code generated by "stringer -type TThostFtdcMoneyAccountStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MAS_Normal-48]
	_ = x[THOST_FTDC_MAS_Cancel-49]
}

const _TThostFtdcMoneyAccountStatusType_name = "正常销户"

var _TThostFtdcMoneyAccountStatusType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcMoneyAccountStatusType) String() string {
	i -= 48
	if i >= TThostFtdcMoneyAccountStatusType(len(_TThostFtdcMoneyAccountStatusType_index)-1) {
		return "TThostFtdcMoneyAccountStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcMoneyAccountStatusType_name[_TThostFtdcMoneyAccountStatusType_index[i]:_TThostFtdcMoneyAccountStatusType_index[i+1]]
}
