// Code generated by "stringer -type TThostFtdcContingentConditionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CC_Immediately-49]
	_ = x[THOST_FTDC_CC_Touch-50]
	_ = x[THOST_FTDC_CC_TouchProfit-51]
	_ = x[THOST_FTDC_CC_ParkedOrder-52]
	_ = x[THOST_FTDC_CC_LastPriceGreaterThanStopPrice-53]
	_ = x[THOST_FTDC_CC_LastPriceGreaterEqualStopPrice-54]
	_ = x[THOST_FTDC_CC_LastPriceLesserThanStopPrice-55]
	_ = x[THOST_FTDC_CC_LastPriceLesserEqualStopPrice-56]
	_ = x[THOST_FTDC_CC_AskPriceGreaterThanStopPrice-57]
	_ = x[THOST_FTDC_CC_AskPriceGreaterEqualStopPrice-65]
	_ = x[THOST_FTDC_CC_AskPriceLesserThanStopPrice-66]
	_ = x[THOST_FTDC_CC_AskPriceLesserEqualStopPrice-67]
	_ = x[THOST_FTDC_CC_BidPriceGreaterThanStopPrice-68]
	_ = x[THOST_FTDC_CC_BidPriceGreaterEqualStopPrice-69]
	_ = x[THOST_FTDC_CC_BidPriceLesserThanStopPrice-70]
	_ = x[THOST_FTDC_CC_BidPriceLesserEqualStopPrice-72]
}

const (
	_TThostFtdcContingentConditionType_name_0 = "立即止损止赢预埋单最新价大于条件价最新价大于等于条件价最新价小于条件价最新价小于等于条件价卖一价大于条件价"
	_TThostFtdcContingentConditionType_name_1 = "卖一价大于等于条件价卖一价小于条件价卖一价小于等于条件价买一价大于条件价买一价大于等于条件价买一价小于条件价"
	_TThostFtdcContingentConditionType_name_2 = "买一价小于等于条件价"
)

var (
	_TThostFtdcContingentConditionType_index_0 = [...]uint8{0, 6, 12, 18, 27, 51, 81, 105, 135, 159}
	_TThostFtdcContingentConditionType_index_1 = [...]uint8{0, 30, 54, 84, 108, 138, 162}
)

func (i TThostFtdcContingentConditionType) String() string {
	switch {
	case 49 <= i && i <= 57:
		i -= 49
		return _TThostFtdcContingentConditionType_name_0[_TThostFtdcContingentConditionType_index_0[i]:_TThostFtdcContingentConditionType_index_0[i+1]]
	case 65 <= i && i <= 70:
		i -= 65
		return _TThostFtdcContingentConditionType_name_1[_TThostFtdcContingentConditionType_index_1[i]:_TThostFtdcContingentConditionType_index_1[i+1]]
	case i == 72:
		return _TThostFtdcContingentConditionType_name_2
	default:
		return "TThostFtdcContingentConditionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
