// Code generated by "stringer -type TThostFtdcFlowIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EvM_InvestorGroupFlow-49]
	_ = x[THOST_FTDC_EvM_InvestorRate-50]
	_ = x[THOST_FTDC_EvM_InvestorCommRateModel-51]
}

const _TThostFtdcFlowIDType_name = "投资者对应投资者组设置投资者手续费率设置投资者手续费率模板关系设置"

var _TThostFtdcFlowIDType_index = [...]uint8{0, 33, 60, 99}

func (i TThostFtdcFlowIDType) String() string {
	i -= 49
	if i >= TThostFtdcFlowIDType(len(_TThostFtdcFlowIDType_index)-1) {
		return "TThostFtdcFlowIDType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFlowIDType_name[_TThostFtdcFlowIDType_index[i]:_TThostFtdcFlowIDType_index[i+1]]
}
