// Code generated by "stringer -type TThostFtdcPortfolioType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EPF_None-48]
	_ = x[THOST_FTDC_EPF_SPBM-49]
	_ = x[THOST_FTDC_EPF_RULE-50]
	_ = x[THOST_FTDC_EPF_SPMM-51]
	_ = x[THOST_FTDC_EPF_RCAMS-52]
}

const _TThostFtdcPortfolioType_name = "不使用新型组保算法SPBM算法RULE算法SPMM算法RCAMS算法"

var _TThostFtdcPortfolioType_index = [...]uint8{0, 27, 37, 47, 57, 68}

func (i TThostFtdcPortfolioType) String() string {
	i -= 48
	if i >= TThostFtdcPortfolioType(len(_TThostFtdcPortfolioType_index)-1) {
		return "TThostFtdcPortfolioType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcPortfolioType_name[_TThostFtdcPortfolioType_index[i]:_TThostFtdcPortfolioType_index[i+1]]
}
