// Code generated by "stringer -type TThostFtdcLoginModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_LM_Trade-48]
	_ = x[THOST_FTDC_LM_Transfer-49]
}

const _TThostFtdcLoginModeType_name = "交易转账"

var _TThostFtdcLoginModeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcLoginModeType) String() string {
	i -= 48
	if i >= TThostFtdcLoginModeType(len(_TThostFtdcLoginModeType_index)-1) {
		return "TThostFtdcLoginModeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcLoginModeType_name[_TThostFtdcLoginModeType_index[i]:_TThostFtdcLoginModeType_index[i+1]]
}
