// Code generated by "stringer -type TThostFtdcOrderFreqControlLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OFCL_None-48]
	_ = x[THOST_FTDC_OFCL_Product-49]
	_ = x[THOST_FTDC_OFCL_Inst-50]
}

const _TThostFtdcOrderFreqControlLevelType_name = "不控制产品级别合约级别"

var _TThostFtdcOrderFreqControlLevelType_index = [...]uint8{0, 9, 21, 33}

func (i TThostFtdcOrderFreqControlLevelType) String() string {
	i -= 48
	if i >= TThostFtdcOrderFreqControlLevelType(len(_TThostFtdcOrderFreqControlLevelType_index)-1) {
		return "TThostFtdcOrderFreqControlLevelType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOrderFreqControlLevelType_name[_TThostFtdcOrderFreqControlLevelType_index[i]:_TThostFtdcOrderFreqControlLevelType_index[i+1]]
}
