// Code generated by "stringer -type TThostFtdcOptSelfCloseFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OSCF_CloseSelfOptionPosition-49]
	_ = x[THOST_FTDC_OSCF_ReserveOptionPosition-50]
	_ = x[THOST_FTDC_OSCF_SellCloseSelfFuturePosition-51]
	_ = x[THOST_FTDC_OSCF_ReserveFuturePosition-52]
}

const _TThostFtdcOptSelfCloseFlagType_name = "自对冲期权仓位保留期权仓位自对冲卖方履约后的期货仓位保留卖方履约后的期货仓位"

var _TThostFtdcOptSelfCloseFlagType_index = [...]uint8{0, 21, 39, 78, 114}

func (i TThostFtdcOptSelfCloseFlagType) String() string {
	i -= 49
	if i >= TThostFtdcOptSelfCloseFlagType(len(_TThostFtdcOptSelfCloseFlagType_index)-1) {
		return "TThostFtdcOptSelfCloseFlagType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcOptSelfCloseFlagType_name[_TThostFtdcOptSelfCloseFlagType_index[i]:_TThostFtdcOptSelfCloseFlagType_index[i+1]]
}
