// Code generated by "stringer -type TThostFtdcSystemStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ES_NonActive-49]
	_ = x[THOST_FTDC_ES_Startup-50]
	_ = x[THOST_FTDC_ES_Initialize-51]
	_ = x[THOST_FTDC_ES_Initialized-52]
	_ = x[THOST_FTDC_ES_Close-53]
	_ = x[THOST_FTDC_ES_Closed-54]
	_ = x[THOST_FTDC_ES_Settlement-55]
}

const _TThostFtdcSystemStatusType_name = "不活跃启动交易开始初始化交易完成初始化收市开始收市完成结算"

var _TThostFtdcSystemStatusType_index = [...]uint8{0, 9, 15, 36, 57, 69, 81, 87}

func (i TThostFtdcSystemStatusType) String() string {
	i -= 49
	if i >= TThostFtdcSystemStatusType(len(_TThostFtdcSystemStatusType_index)-1) {
		return "TThostFtdcSystemStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSystemStatusType_name[_TThostFtdcSystemStatusType_index[i]:_TThostFtdcSystemStatusType_index[i+1]]
}
