// Code generated by "stringer -type TThostFtdcHasBoardType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_HB_No-48]
	_ = x[THOST_FTDC_HB_Yes-49]
}

const _TThostFtdcHasBoardType_name = "没有有"

var _TThostFtdcHasBoardType_index = [...]uint8{0, 6, 9}

func (i TThostFtdcHasBoardType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcHasBoardType_index)-1 {
		return "TThostFtdcHasBoardType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcHasBoardType_name[_TThostFtdcHasBoardType_index[idx]:_TThostFtdcHasBoardType_index[idx+1]]
}
