// Code generated by "stringer -type TThostFtdcFundStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FS_Record-49]
	_ = x[THOST_FTDC_FS_Check-50]
	_ = x[THOST_FTDC_FS_Charge-51]
}

const _TThostFtdcFundStatusType_name = "已录入已复核已冲销"

var _TThostFtdcFundStatusType_index = [...]uint8{0, 9, 18, 27}

func (i TThostFtdcFundStatusType) String() string {
	i -= 49
	if i >= TThostFtdcFundStatusType(len(_TThostFtdcFundStatusType_index)-1) {
		return "TThostFtdcFundStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundStatusType_name[_TThostFtdcFundStatusType_index[i]:_TThostFtdcFundStatusType_index[i+1]]
}
