// Code generated by "stringer -type TThostFtdcVolumeConditionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VC_AV-49]
	_ = x[THOST_FTDC_VC_MV-50]
	_ = x[THOST_FTDC_VC_CV-51]
}

const _TThostFtdcVolumeConditionType_name = "任何数量最小数量全部数量"

var _TThostFtdcVolumeConditionType_index = [...]uint8{0, 12, 24, 36}

func (i TThostFtdcVolumeConditionType) String() string {
	i -= 49
	if i >= TThostFtdcVolumeConditionType(len(_TThostFtdcVolumeConditionType_index)-1) {
		return "TThostFtdcVolumeConditionType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcVolumeConditionType_name[_TThostFtdcVolumeConditionType_index[i]:_TThostFtdcVolumeConditionType_index[i+1]]
}
