// Code generated by "stringer -type TThostFtdcGiveUpDataSourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_GUDS_Gen-48]
	_ = x[THOST_FTDC_GUDS_Hand-49]
}

const _TThostFtdcGiveUpDataSourceType_name = "系统生成手工添加"

var _TThostFtdcGiveUpDataSourceType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcGiveUpDataSourceType) String() string {
	i -= 48
	if i >= TThostFtdcGiveUpDataSourceType(len(_TThostFtdcGiveUpDataSourceType_index)-1) {
		return "TThostFtdcGiveUpDataSourceType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcGiveUpDataSourceType_name[_TThostFtdcGiveUpDataSourceType_index[i]:_TThostFtdcGiveUpDataSourceType_index[i+1]]
}
