// Code generated by "stringer -type TThostFtdcSettleManagerTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SMT_Before-49]
	_ = x[THOST_FTDC_SMT_Settlement-50]
	_ = x[THOST_FTDC_SMT_After-51]
	_ = x[THOST_FTDC_SMT_Settlemented-52]
}

const _TThostFtdcSettleManagerTypeType_name = "结算前准备结算结算后核对结算后处理"

var _TThostFtdcSettleManagerTypeType_index = [...]uint8{0, 15, 21, 36, 51}

func (i TThostFtdcSettleManagerTypeType) String() string {
	i -= 49
	if i >= TThostFtdcSettleManagerTypeType(len(_TThostFtdcSettleManagerTypeType_index)-1) {
		return "TThostFtdcSettleManagerTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSettleManagerTypeType_name[_TThostFtdcSettleManagerTypeType_index[i]:_TThostFtdcSettleManagerTypeType_index[i+1]]
}
