// Code generated by "stringer -type TThostFtdcExecOrderCloseFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EOCF_AutoClose-48]
	_ = x[THOST_FTDC_EOCF_NotToClose-49]
}

const _TThostFtdcExecOrderCloseFlagType_name = "自动平仓免于自动平仓"

var _TThostFtdcExecOrderCloseFlagType_index = [...]uint8{0, 12, 30}

func (i TThostFtdcExecOrderCloseFlagType) String() string {
	i -= 48
	if i >= TThostFtdcExecOrderCloseFlagType(len(_TThostFtdcExecOrderCloseFlagType_index)-1) {
		return "TThostFtdcExecOrderCloseFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcExecOrderCloseFlagType_name[_TThostFtdcExecOrderCloseFlagType_index[i]:_TThostFtdcExecOrderCloseFlagType_index[i+1]]
}
