// Code generated by "stringer -type TThostFtdcPositionTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PT_Net-49]
	_ = x[THOST_FTDC_PT_Gross-50]
}

const _TThostFtdcPositionTypeType_name = "净持仓综合持仓"

var _TThostFtdcPositionTypeType_index = [...]uint8{0, 9, 21}

func (i TThostFtdcPositionTypeType) String() string {
	i -= 49
	if i >= TThostFtdcPositionTypeType(len(_TThostFtdcPositionTypeType_index)-1) {
		return "TThostFtdcPositionTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcPositionTypeType_name[_TThostFtdcPositionTypeType_index[i]:_TThostFtdcPositionTypeType_index[i+1]]
}
