// Code generated by "stringer -type TThostFtdcRatioAttrType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RA_Trade-48]
	_ = x[THOST_FTDC_RA_Settlement-49]
}

const _TThostFtdcRatioAttrType_name = "交易费率结算费率"

var _TThostFtdcRatioAttrType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcRatioAttrType) String() string {
	i -= 48
	if i >= TThostFtdcRatioAttrType(len(_TThostFtdcRatioAttrType_index)-1) {
		return "TThostFtdcRatioAttrType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcRatioAttrType_name[_TThostFtdcRatioAttrType_index[i]:_TThostFtdcRatioAttrType_index[i+1]]
}
