// Code generated by "stringer -type TThostFtdcStartModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SM_Normal-49]
	_ = x[THOST_FTDC_SM_Emerge-50]
	_ = x[THOST_FTDC_SM_Restore-51]
}

const _TThostFtdcStartModeType_name = "正常应急恢复"

var _TThostFtdcStartModeType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcStartModeType) String() string {
	i -= 49
	if i >= TThostFtdcStartModeType(len(_TThostFtdcStartModeType_index)-1) {
		return "TThostFtdcStartModeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcStartModeType_name[_TThostFtdcStartModeType_index[i]:_TThostFtdcStartModeType_index[i+1]]
}
