// Code generated by "stringer -type TThostFtdcForceCloseTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FCT_Manual-48]
	_ = x[THOST_FTDC_FCT_Single-49]
	_ = x[THOST_FTDC_FCT_Group-50]
}

const _TThostFtdcForceCloseTypeType_name = "手工强平单一投资者辅助强平批量投资者辅助强平"

var _TThostFtdcForceCloseTypeType_index = [...]uint8{0, 12, 39, 66}

func (i TThostFtdcForceCloseTypeType) String() string {
	i -= 48
	if i >= TThostFtdcForceCloseTypeType(len(_TThostFtdcForceCloseTypeType_index)-1) {
		return "TThostFtdcForceCloseTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcForceCloseTypeType_name[_TThostFtdcForceCloseTypeType_index[i]:_TThostFtdcForceCloseTypeType_index[i+1]]
}
