// Code generated by "stringer -type TThostFtdcCustTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CUSTT_Person-48]
	_ = x[THOST_FTDC_CUSTT_Institution-49]
}

const _TThostFtdcCustTypeType_name = "自然人机构户"

var _TThostFtdcCustTypeType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcCustTypeType) String() string {
	i -= 48
	if i >= TThostFtdcCustTypeType(len(_TThostFtdcCustTypeType_index)-1) {
		return "TThostFtdcCustTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCustTypeType_name[_TThostFtdcCustTypeType_index[i]:_TThostFtdcCustTypeType_index[i+1]]
}
