// Code generated by "stringer -type TThostFtdcFileStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FIS_NoCreate-48]
	_ = x[THOST_FTDC_FIS_Created-49]
	_ = x[THOST_FTDC_FIS_Failed-50]
}

const _TThostFtdcFileStatusType_name = "未生成已生成生成失败"

var _TThostFtdcFileStatusType_index = [...]uint8{0, 9, 18, 30}

func (i TThostFtdcFileStatusType) String() string {
	i -= 48
	if i >= TThostFtdcFileStatusType(len(_TThostFtdcFileStatusType_index)-1) {
		return "TThostFtdcFileStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFileStatusType_name[_TThostFtdcFileStatusType_index[i]:_TThostFtdcFileStatusType_index[i+1]]
}
