// Code generated by "stringer -type TThostFtdcVirDealStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VDS_Dealing-49]
	_ = x[THOST_FTDC_VDS_DeaclSucceed-50]
}

const _TThostFtdcVirDealStatusType_name = "正在处理处理成功"

var _TThostFtdcVirDealStatusType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcVirDealStatusType) String() string {
	i -= 49
	if i >= TThostFtdcVirDealStatusType(len(_TThostFtdcVirDealStatusType_index)-1) {
		return "TThostFtdcVirDealStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcVirDealStatusType_name[_TThostFtdcVirDealStatusType_index[i]:_TThostFtdcVirDealStatusType_index[i+1]]
}
