// Code generated by "stringer -type TThostFtdcOptionsTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CP_CallOptions-49]
	_ = x[THOST_FTDC_CP_PutOptions-50]
}

const _TThostFtdcOptionsTypeType_name = "看涨看跌"

var _TThostFtdcOptionsTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcOptionsTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcOptionsTypeType_index)-1 {
		return "TThostFtdcOptionsTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcOptionsTypeType_name[_TThostFtdcOptionsTypeType_index[idx]:_TThostFtdcOptionsTypeType_index[idx+1]]
}
