// Code generated by "stringer -type TThostFtdcAvailabilityFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AVAF_Invalid-48]
	_ = x[THOST_FTDC_AVAF_Valid-49]
	_ = x[THOST_FTDC_AVAF_Repeal-50]
}

const _TThostFtdcAvailabilityFlagType_name = "未确认有效冲正"

var _TThostFtdcAvailabilityFlagType_index = [...]uint8{0, 9, 15, 21}

func (i TThostFtdcAvailabilityFlagType) String() string {
	i -= 48
	if i >= TThostFtdcAvailabilityFlagType(len(_TThostFtdcAvailabilityFlagType_index)-1) {
		return "TThostFtdcAvailabilityFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcAvailabilityFlagType_name[_TThostFtdcAvailabilityFlagType_index[i]:_TThostFtdcAvailabilityFlagType_index[i+1]]
}
