// Code generated by "stringer -type TThostFtdcOTCTradeTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OTC_TRDT_Block-48]
	_ = x[THOST_FTDC_OTC_TRDT_EFP-49]
	_ = x[THOST_FTDC_OTC_MT_DV01-49]
	_ = x[THOST_FTDC_OTC_MT_ParValue-50]
}

const _TThostFtdcOTCTradeTypeType_name = "大宗交易期转现面值"

var _TThostFtdcOTCTradeTypeType_index = [...]uint8{0, 12, 21, 27}

func (i TThostFtdcOTCTradeTypeType) String() string {
	i -= 48
	if i >= TThostFtdcOTCTradeTypeType(len(_TThostFtdcOTCTradeTypeType_index)-1) {
		return "TThostFtdcOTCTradeTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOTCTradeTypeType_name[_TThostFtdcOTCTradeTypeType_index[i]:_TThostFtdcOTCTradeTypeType_index[i+1]]
}
