// Code generated by "stringer -type TThostFtdcOrderSourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OSRC_Participant-48]
	_ = x[THOST_FTDC_OSRC_Administrator-49]
}

const _TThostFtdcOrderSourceType_name = "来自参与者来自管理员"

var _TThostFtdcOrderSourceType_index = [...]uint8{0, 15, 30}

func (i TThostFtdcOrderSourceType) String() string {
	i -= 48
	if i >= TThostFtdcOrderSourceType(len(_TThostFtdcOrderSourceType_index)-1) {
		return "TThostFtdcOrderSourceType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOrderSourceType_name[_TThostFtdcOrderSourceType_index[i]:_TThostFtdcOrderSourceType_index[i+1]]
}
