// Code generated by "stringer -type TThostFtdcOrganLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OL_HeadQuarters-49]
	_ = x[THOST_FTDC_OL_Branch-50]
}

const _TThostFtdcOrganLevelType_name = "银行总行或期商总部银行分中心或期货公司营业部"

var _TThostFtdcOrganLevelType_index = [...]uint8{0, 27, 66}

func (i TThostFtdcOrganLevelType) String() string {
	i -= 49
	if i >= TThostFtdcOrganLevelType(len(_TThostFtdcOrganLevelType_index)-1) {
		return "TThostFtdcOrganLevelType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcOrganLevelType_name[_TThostFtdcOrganLevelType_index[i]:_TThostFtdcOrganLevelType_index[i+1]]
}
