// Code generated by "stringer -type TThostFtdcExprSetModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ESM_Relative-49]
	_ = x[THOST_FTDC_ESM_Typical-50]
}

const _TThostFtdcExprSetModeType_name = "相对已有规则设置典型设置"

var _TThostFtdcExprSetModeType_index = [...]uint8{0, 24, 36}

func (i TThostFtdcExprSetModeType) String() string {
	i -= 49
	if i >= TThostFtdcExprSetModeType(len(_TThostFtdcExprSetModeType_index)-1) {
		return "TThostFtdcExprSetModeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcExprSetModeType_name[_TThostFtdcExprSetModeType_index[i]:_TThostFtdcExprSetModeType_index[i+1]]
}
