// Code generated by "stringer -type TThostFtdcFeeAcceptStyleType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FAS_ByTrade-49]
	_ = x[THOST_FTDC_FAS_ByDeliv-50]
	_ = x[THOST_FTDC_FAS_None-51]
	_ = x[THOST_FTDC_FAS_FixFee-52]
}

const _TThostFtdcFeeAcceptStyleType_name = "按交易收取按交割收取不收按指定手续费收取"

var _TThostFtdcFeeAcceptStyleType_index = [...]uint8{0, 15, 30, 36, 60}

func (i TThostFtdcFeeAcceptStyleType) String() string {
	i -= 49
	if i >= TThostFtdcFeeAcceptStyleType(len(_TThostFtdcFeeAcceptStyleType_index)-1) {
		return "TThostFtdcFeeAcceptStyleType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFeeAcceptStyleType_name[_TThostFtdcFeeAcceptStyleType_index[i]:_TThostFtdcFeeAcceptStyleType_index[i+1]]
}
