// Code generated by "stringer -type TThostFtdcHedgeFlagEnType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_HFEN_Speculation-49]
	_ = x[THOST_FTDC_HFEN_Arbitrage-50]
	_ = x[THOST_FTDC_HFEN_Hedge-51]
}

const _TThostFtdcHedgeFlagEnType_name = "SpeculationArbitrageHedge"

var _TThostFtdcHedgeFlagEnType_index = [...]uint8{0, 11, 20, 25}

func (i TThostFtdcHedgeFlagEnType) String() string {
	i -= 49
	if i >= TThostFtdcHedgeFlagEnType(len(_TThostFtdcHedgeFlagEnType_index)-1) {
		return "TThostFtdcHedgeFlagEnType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcHedgeFlagEnType_name[_TThostFtdcHedgeFlagEnType_index[i]:_TThostFtdcHedgeFlagEnType_index[i+1]]
}
