// Code generated by "stringer -type TThostFtdcUserTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UT_Investor-48]
	_ = x[THOST_FTDC_UT_Operator-49]
	_ = x[THOST_FTDC_UT_SuperUser-50]
}

const _TThostFtdcUserTypeType_name = "投资者操作员管理员"

var _TThostFtdcUserTypeType_index = [...]uint8{0, 9, 18, 27}

func (i TThostFtdcUserTypeType) String() string {
	i -= 48
	if i >= TThostFtdcUserTypeType(len(_TThostFtdcUserTypeType_index)-1) {
		return "TThostFtdcUserTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcUserTypeType_name[_TThostFtdcUserTypeType_index[i]:_TThostFtdcUserTypeType_index[i+1]]
}
