// Code generated by "stringer -type TThostFtdcConditionalOrderSortTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_COST_LastPriceAsc-48]
	_ = x[THOST_FTDC_COST_LastPriceDesc-49]
	_ = x[THOST_FTDC_COST_AskPriceAsc-50]
	_ = x[THOST_FTDC_COST_AskPriceDesc-51]
	_ = x[THOST_FTDC_COST_BidPriceAsc-52]
	_ = x[THOST_FTDC_COST_BidPriceDesc-53]
}

const _TThostFtdcConditionalOrderSortTypeType_name = "使用最新价升序使用最新价降序使用卖价升序使用卖价降序使用买价升序使用买价降序"

var _TThostFtdcConditionalOrderSortTypeType_index = [...]uint8{0, 21, 42, 60, 78, 96, 114}

func (i TThostFtdcConditionalOrderSortTypeType) String() string {
	i -= 48
	if i >= TThostFtdcConditionalOrderSortTypeType(len(_TThostFtdcConditionalOrderSortTypeType_index)-1) {
		return "TThostFtdcConditionalOrderSortTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcConditionalOrderSortTypeType_name[_TThostFtdcConditionalOrderSortTypeType_index[i]:_TThostFtdcConditionalOrderSortTypeType_index[i+1]]
}
