// Code generated by "stringer -type TThostFtdcSyncFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SYNF_Yes-48]
	_ = x[THOST_FTDC_SYNF_No-49]
}

const _TThostFtdcSyncFlagType_name = "已同步未同步"

var _TThostFtdcSyncFlagType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcSyncFlagType) String() string {
	i -= 48
	if i >= TThostFtdcSyncFlagType(len(_TThostFtdcSyncFlagType_index)-1) {
		return "TThostFtdcSyncFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSyncFlagType_name[_TThostFtdcSyncFlagType_index[i]:_TThostFtdcSyncFlagType_index[i+1]]
}
