// Code generated by "stringer -type TThostFtdcEventModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EvM_ADD-49]
	_ = x[THOST_FTDC_EvM_UPDATE-50]
	_ = x[THOST_FTDC_EvM_DELETE-51]
	_ = x[THOST_FTDC_EvM_CHECK-52]
	_ = x[THOST_FTDC_EvM_COPY-53]
	_ = x[THOST_FTDC_EvM_CANCEL-54]
	_ = x[THOST_FTDC_EvM_Reverse-55]
	_ = x[THOST_FTDC_EvM_InvestorGroupFlow-49]
	_ = x[THOST_FTDC_EvM_InvestorRate-50]
	_ = x[THOST_FTDC_EvM_InvestorCommRateModel-51]
}

const _TThostFtdcEventModeType_name = "增加修改删除复核复制注销冲销"

var _TThostFtdcEventModeType_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42}

func (i TThostFtdcEventModeType) String() string {
	i -= 49
	if i >= TThostFtdcEventModeType(len(_TThostFtdcEventModeType_index)-1) {
		return "TThostFtdcEventModeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcEventModeType_name[_TThostFtdcEventModeType_index[i]:_TThostFtdcEventModeType_index[i+1]]
}
