// Code generated by "stringer -type TThostFtdcMarginRateTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MRT_Exchange-49]
	_ = x[THOST_FTDC_MRT_Investor-50]
	_ = x[THOST_FTDC_MRT_InvestorTrade-51]
}

const _TThostFtdcMarginRateTypeType_name = "交易所保证金率投资者保证金率投资者交易保证金率"

var _TThostFtdcMarginRateTypeType_index = [...]uint8{0, 21, 42, 69}

func (i TThostFtdcMarginRateTypeType) String() string {
	i -= 49
	if i >= TThostFtdcMarginRateTypeType(len(_TThostFtdcMarginRateTypeType_index)-1) {
		return "TThostFtdcMarginRateTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcMarginRateTypeType_name[_TThostFtdcMarginRateTypeType_index[i]:_TThostFtdcMarginRateTypeType_index[i+1]]
}
