// Code generated by "stringer -type TThostFtdcFundDirectionEnType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FDEN_In-49]
	_ = x[THOST_FTDC_FDEN_Out-50]
}

const _TThostFtdcFundDirectionEnType_name = "DepositWithdrawal"

var _TThostFtdcFundDirectionEnType_index = [...]uint8{0, 7, 17}

func (i TThostFtdcFundDirectionEnType) String() string {
	i -= 49
	if i >= TThostFtdcFundDirectionEnType(len(_TThostFtdcFundDirectionEnType_index)-1) {
		return "TThostFtdcFundDirectionEnType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundDirectionEnType_name[_TThostFtdcFundDirectionEnType_index[i]:_TThostFtdcFundDirectionEnType_index[i+1]]
}
