// Code generated by "stringer -type TThostFtdcBusinessTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BT_Request-49]
	_ = x[THOST_FTDC_BT_Response-50]
	_ = x[THOST_FTDC_BT_Notice-51]
}

const _TThostFtdcBusinessTypeType_name = "请求应答通知"

var _TThostFtdcBusinessTypeType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcBusinessTypeType) String() string {
	i -= 49
	if i >= TThostFtdcBusinessTypeType(len(_TThostFtdcBusinessTypeType_index)-1) {
		return "TThostFtdcBusinessTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcBusinessTypeType_name[_TThostFtdcBusinessTypeType_index[i]:_TThostFtdcBusinessTypeType_index[i+1]]
}
