// Code generated by "stringer -type TThostFtdcExClientIDTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ECIDT_Hedge-49]
	_ = x[THOST_FTDC_ECIDT_Arbitrage-50]
	_ = x[THOST_FTDC_ECIDT_Speculation-51]
}

const _TThostFtdcExClientIDTypeType_name = "套保套利投机"

var _TThostFtdcExClientIDTypeType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcExClientIDTypeType) String() string {
	i -= 49
	if i >= TThostFtdcExClientIDTypeType(len(_TThostFtdcExClientIDTypeType_index)-1) {
		return "TThostFtdcExClientIDTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcExClientIDTypeType_name[_TThostFtdcExClientIDTypeType_index[i]:_TThostFtdcExClientIDTypeType_index[i+1]]
}
