// Code generated by "stringer -type TThostFtdcStandardStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_STST_Standard-48]
	_ = x[THOST_FTDC_STST_NonStandard-49]
}

const _TThostFtdcStandardStatusType_name = "已规范未规范"

var _TThostFtdcStandardStatusType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcStandardStatusType) String() string {
	i -= 48
	if i >= TThostFtdcStandardStatusType(len(_TThostFtdcStandardStatusType_index)-1) {
		return "TThostFtdcStandardStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcStandardStatusType_name[_TThostFtdcStandardStatusType_index[i]:_TThostFtdcStandardStatusType_index[i+1]]
}
