// Code generated by "stringer -type TThostFtdcSpecProductTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SPT_CzceHedge-49]
	_ = x[THOST_FTDC_SPT_IneForeignCurrency-50]
	_ = x[THOST_FTDC_SPT_DceOpenClose-51]
}

const _TThostFtdcSpecProductTypeType_name = "郑商所套保产品货币质押产品大连短线开平仓产品"

var _TThostFtdcSpecProductTypeType_index = [...]uint8{0, 21, 39, 66}

func (i TThostFtdcSpecProductTypeType) String() string {
	i -= 49
	if i >= TThostFtdcSpecProductTypeType(len(_TThostFtdcSpecProductTypeType_index)-1) {
		return "TThostFtdcSpecProductTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSpecProductTypeType_name[_TThostFtdcSpecProductTypeType_index[i]:_TThostFtdcSpecProductTypeType_index[i+1]]
}
