// Code generated by "stringer -type TThostFtdcSecuAccTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SAT_AccountID-49]
	_ = x[THOST_FTDC_SAT_CardID-50]
	_ = x[THOST_FTDC_SAT_SHStockholderID-51]
	_ = x[THOST_FTDC_SAT_SZStockholderID-52]
}

const _TThostFtdcSecuAccTypeType_name = "资金帐号资金卡号上海股东帐号深圳股东帐号"

var _TThostFtdcSecuAccTypeType_index = [...]uint8{0, 12, 24, 42, 60}

func (i TThostFtdcSecuAccTypeType) String() string {
	i -= 49
	if i >= TThostFtdcSecuAccTypeType(len(_TThostFtdcSecuAccTypeType_index)-1) {
		return "TThostFtdcSecuAccTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSecuAccTypeType_name[_TThostFtdcSecuAccTypeType_index[i]:_TThostFtdcSecuAccTypeType_index[i+1]]
}
