// Code generated by "stringer -type TThostFtdcOrderCancelAlgType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OAC_Balance-49]
	_ = x[THOST_FTDC_OAC_OrigFirst-50]
}

const _TThostFtdcOrderCancelAlgType_name = "轮询席位撤单优先原报单席位撤单"

var _TThostFtdcOrderCancelAlgType_index = [...]uint8{0, 18, 45}

func (i TThostFtdcOrderCancelAlgType) String() string {
	i -= 49
	if i >= TThostFtdcOrderCancelAlgType(len(_TThostFtdcOrderCancelAlgType_index)-1) {
		return "TThostFtdcOrderCancelAlgType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcOrderCancelAlgType_name[_TThostFtdcOrderCancelAlgType_index[i]:_TThostFtdcOrderCancelAlgType_index[i+1]]
}
