// Code generated by "stringer -type TThostFtdcPositionDateType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PSD_Today-49]
	_ = x[THOST_FTDC_PSD_History-50]
}

const _TThostFtdcPositionDateType_name = "今日持仓历史持仓"

var _TThostFtdcPositionDateType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcPositionDateType) String() string {
	i -= 49
	if i >= TThostFtdcPositionDateType(len(_TThostFtdcPositionDateType_index)-1) {
		return "TThostFtdcPositionDateType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcPositionDateType_name[_TThostFtdcPositionDateType_index[i]:_TThostFtdcPositionDateType_index[i+1]]
}
