// Code generated by "stringer -type TThostFtdcUsedStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CHU_Unused-48]
	_ = x[THOST_FTDC_CHU_Used-49]
	_ = x[THOST_FTDC_CHU_Fail-50]
}

const _TThostFtdcUsedStatusType_name = "未生效已生效生效失败"

var _TThostFtdcUsedStatusType_index = [...]uint8{0, 9, 18, 30}

func (i TThostFtdcUsedStatusType) String() string {
	i -= 48
	if i >= TThostFtdcUsedStatusType(len(_TThostFtdcUsedStatusType_index)-1) {
		return "TThostFtdcUsedStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcUsedStatusType_name[_TThostFtdcUsedStatusType_index[i]:_TThostFtdcUsedStatusType_index[i+1]]
}
