// Code generated by "stringer -type TThostFtdcReasonType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RN_CD-48]
	_ = x[THOST_FTDC_RN_ZT-49]
	_ = x[THOST_FTDC_RN_QT-50]
}

const _TThostFtdcReasonType_name = "错单资金在途其它"

var _TThostFtdcReasonType_index = [...]uint8{0, 6, 18, 24}

func (i TThostFtdcReasonType) String() string {
	i -= 48
	if i >= TThostFtdcReasonType(len(_TThostFtdcReasonType_index)-1) {
		return "TThostFtdcReasonType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcReasonType_name[_TThostFtdcReasonType_index[i]:_TThostFtdcReasonType_index[i+1]]
}
