// Code generated by "stringer -type TThostFtdcValueMethodType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VM_Absolute-48]
	_ = x[THOST_FTDC_VM_Ratio-49]
}

const _TThostFtdcValueMethodType_name = "按绝对值按比率"

var _TThostFtdcValueMethodType_index = [...]uint8{0, 12, 21}

func (i TThostFtdcValueMethodType) String() string {
	i -= 48
	if i >= TThostFtdcValueMethodType(len(_TThostFtdcValueMethodType_index)-1) {
		return "TThostFtdcValueMethodType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcValueMethodType_name[_TThostFtdcValueMethodType_index[i]:_TThostFtdcValueMethodType_index[i+1]]
}
