// Code generated by "stringer -type TThostFtdcSexType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SEX_None-48]
	_ = x[THOST_FTDC_SEX_Man-49]
	_ = x[THOST_FTDC_SEX_Woman-50]
}

const _TThostFtdcSexType_name = "未知男女"

var _TThostFtdcSexType_index = [...]uint8{0, 6, 9, 12}

func (i TThostFtdcSexType) String() string {
	i -= 48
	if i >= TThostFtdcSexType(len(_TThostFtdcSexType_index)-1) {
		return "TThostFtdcSexType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSexType_name[_TThostFtdcSexType_index[i]:_TThostFtdcSexType_index[i+1]]
}
