// Code generated by "stringer -type TThostFtdcActiveTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ACT_Intraday-49]
	_ = x[THOST_FTDC_ACT_Long-50]
}

const _TThostFtdcActiveTypeType_name = "仅当日生效长期生效"

var _TThostFtdcActiveTypeType_index = [...]uint8{0, 15, 27}

func (i TThostFtdcActiveTypeType) String() string {
	i -= 49
	if i >= TThostFtdcActiveTypeType(len(_TThostFtdcActiveTypeType_index)-1) {
		return "TThostFtdcActiveTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcActiveTypeType_name[_TThostFtdcActiveTypeType_index[i]:_TThostFtdcActiveTypeType_index[i+1]]
}
