// Code generated by "stringer -type TThostFtdcTransferDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TD_Out-48]
	_ = x[THOST_FTDC_TD_In-49]
	_ = x[THOST_FTDC_TD_ALL-48]
	_ = x[THOST_FTDC_TD_TRADE-49]
	_ = x[THOST_FTDC_TD_UNTRADE-50]
}

const _TThostFtdcTransferDirectionType_name = "移出移入非交易"

var _TThostFtdcTransferDirectionType_index = [...]uint8{0, 6, 12, 21}

func (i TThostFtdcTransferDirectionType) String() string {
	i -= 48
	if i >= TThostFtdcTransferDirectionType(len(_TThostFtdcTransferDirectionType_index)-1) {
		return "TThostFtdcTransferDirectionType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcTransferDirectionType_name[_TThostFtdcTransferDirectionType_index[i]:_TThostFtdcTransferDirectionType_index[i+1]]
}
