// Code generated by "stringer -type TThostFtdcProcessStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PSS_NotProcess-48]
	_ = x[THOST_FTDC_PSS_StartProcess-49]
	_ = x[THOST_FTDC_PSS_Finished-50]
}

const _TThostFtdcProcessStatusType_name = "未处理开始处理处理完成"

var _TThostFtdcProcessStatusType_index = [...]uint8{0, 9, 21, 33}

func (i TThostFtdcProcessStatusType) String() string {
	i -= 48
	if i >= TThostFtdcProcessStatusType(len(_TThostFtdcProcessStatusType_index)-1) {
		return "TThostFtdcProcessStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcProcessStatusType_name[_TThostFtdcProcessStatusType_index[i]:_TThostFtdcProcessStatusType_index[i+1]]
}
