// Code generated by "stringer -type TThostFtdcCloseStyleType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ICS_Close-48]
	_ = x[THOST_FTDC_ICS_CloseToday-49]
}

const _TThostFtdcCloseStyleType_name = "先开先平先平今再平昨"

var _TThostFtdcCloseStyleType_index = [...]uint8{0, 12, 30}

func (i TThostFtdcCloseStyleType) String() string {
	i -= 48
	if i >= TThostFtdcCloseStyleType(len(_TThostFtdcCloseStyleType_index)-1) {
		return "TThostFtdcCloseStyleType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCloseStyleType_name[_TThostFtdcCloseStyleType_index[i]:_TThostFtdcCloseStyleType_index[i+1]]
}
