// Code generated by "stringer -type TThostFtdcCheckLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CL_Zero-48]
	_ = x[THOST_FTDC_CL_One-49]
	_ = x[THOST_FTDC_CL_Two-50]
}

const _TThostFtdcCheckLevelType_name = "零级复核一级复核二级复核"

var _TThostFtdcCheckLevelType_index = [...]uint8{0, 12, 24, 36}

func (i TThostFtdcCheckLevelType) String() string {
	i -= 48
	if i >= TThostFtdcCheckLevelType(len(_TThostFtdcCheckLevelType_index)-1) {
		return "TThostFtdcCheckLevelType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCheckLevelType_name[_TThostFtdcCheckLevelType_index[i]:_TThostFtdcCheckLevelType_index[i+1]]
}
