// Code generated by "stringer -type TThostFtdcProductLifePhaseType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PLP_Active-49]
	_ = x[THOST_FTDC_PLP_NonActive-50]
	_ = x[THOST_FTDC_PLP_Canceled-51]
}

const _TThostFtdcProductLifePhaseType_name = "活跃不活跃注销"

var _TThostFtdcProductLifePhaseType_index = [...]uint8{0, 6, 15, 21}

func (i TThostFtdcProductLifePhaseType) String() string {
	i -= 49
	if i >= TThostFtdcProductLifePhaseType(len(_TThostFtdcProductLifePhaseType_index)-1) {
		return "TThostFtdcProductLifePhaseType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcProductLifePhaseType_name[_TThostFtdcProductLifePhaseType_index[i]:_TThostFtdcProductLifePhaseType_index[i+1]]
}
