// Code generated by "stringer -type TThostFtdcTradeParamIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TPID_EncryptionStandard-69]
	_ = x[THOST_FTDC_TPID_RiskMode-82]
	_ = x[THOST_FTDC_TPID_RiskModeGlobal-71]
	_ = x[THOST_FTDC_TPID_modeEncode-80]
	_ = x[THOST_FTDC_TPID_tickMode-84]
	_ = x[THOST_FTDC_TPID_SingleUserSessionMaxNum-83]
	_ = x[THOST_FTDC_TPID_LoginFailMaxNum-76]
	_ = x[THOST_FTDC_TPID_IsAuthForce-65]
	_ = x[THOST_FTDC_TPID_IsPosiFreeze-70]
	_ = x[THOST_FTDC_TPID_IsPosiLimit-77]
	_ = x[THOST_FTDC_TPID_ForQuoteTimeInterval-81]
	_ = x[THOST_FTDC_TPID_IsFuturePosiLimit-66]
	_ = x[THOST_FTDC_TPID_IsFutureOrderFreq-67]
	_ = x[THOST_FTDC_TPID_IsExecOrderProfit-72]
	_ = x[THOST_FTDC_TPID_IsCheckBankAcc-73]
	_ = x[THOST_FTDC_TPID_PasswordDeadLine-74]
	_ = x[THOST_FTDC_TPID_IsStrongPassword-75]
	_ = x[THOST_FTDC_TPID_BalanceMorgage-97]
	_ = x[THOST_FTDC_TPID_MinPwdLen-79]
	_ = x[THOST_FTDC_TPID_LoginFailMaxNumForIP-85]
	_ = x[THOST_FTDC_TPID_PasswordPeriod-86]
	_ = x[THOST_FTDC_TPID_PwdHistoryCmp-88]
	_ = x[THOST_FTDC_TPID_TranferChkProperty-105]
	_ = x[THOST_FTDC_TPID_TradeChkPhase-106]
	_ = x[THOST_FTDC_TPID_TradeChkPriceVol-107]
	_ = x[THOST_FTDC_TPID_NewBESMarginAlgo-108]
}

const (
	_TThostFtdcTradeParamIDType_name_0 = "是否强制认证是否期货限仓是否期货下单频率限制"
	_TThostFtdcTradeParamIDType_name_1 = "系统加密算法是否冻结证券持仓系统风险算法是否全局 0-否 1-是行权冻结是否计算盈利银期开户是否验证开户银行卡号是否是预留银行账户弱密码最后修改日期强密码校验最大连续登录失败数是否限仓"
	_TThostFtdcTradeParamIDType_name_2 = "最小密码长度密码加密算法郑商所询价时间间隔系统风险算法用户最大会话数价格小数位数参数IP当日最大登陆失败次数密码有效期"
	_TThostFtdcTradeParamIDType_name_3 = "历史密码重复限制次数"
	_TThostFtdcTradeParamIDType_name_4 = "自有资金质押比"
	_TThostFtdcTradeParamIDType_name_5 = "转账是否验证预留银行账户非交易时间异常报单校验参数其他异常报单校验参数（价格和手数）卖出垂直价差组合新算法"
)

var (
	_TThostFtdcTradeParamIDType_index_0 = [...]uint8{0, 18, 36, 66}
	_TThostFtdcTradeParamIDType_index_1 = [...]uint16{0, 18, 42, 84, 114, 183, 210, 225, 252, 264}
	_TThostFtdcTradeParamIDType_index_2 = [...]uint8{0, 18, 36, 63, 81, 102, 126, 158, 173}
	_TThostFtdcTradeParamIDType_index_5 = [...]uint8{0, 36, 75, 126, 159}
)

func (i TThostFtdcTradeParamIDType) String() string {
	switch {
	case 65 <= i && i <= 67:
		i -= 65
		return _TThostFtdcTradeParamIDType_name_0[_TThostFtdcTradeParamIDType_index_0[i]:_TThostFtdcTradeParamIDType_index_0[i+1]]
	case 69 <= i && i <= 77:
		i -= 69
		return _TThostFtdcTradeParamIDType_name_1[_TThostFtdcTradeParamIDType_index_1[i]:_TThostFtdcTradeParamIDType_index_1[i+1]]
	case 79 <= i && i <= 86:
		i -= 79
		return _TThostFtdcTradeParamIDType_name_2[_TThostFtdcTradeParamIDType_index_2[i]:_TThostFtdcTradeParamIDType_index_2[i+1]]
	case i == 88:
		return _TThostFtdcTradeParamIDType_name_3
	case i == 97:
		return _TThostFtdcTradeParamIDType_name_4
	case 105 <= i && i <= 108:
		i -= 105
		return _TThostFtdcTradeParamIDType_name_5[_TThostFtdcTradeParamIDType_index_5[i]:_TThostFtdcTradeParamIDType_index_5[i+1]]
	default:
		return "TThostFtdcTradeParamIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
