// Code generated by "stringer -type TThostFtdcExchangePropertyType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EXP_Normal-48]
	_ = x[THOST_FTDC_EXP_GenOrderByTrade-49]
}

const _TThostFtdcExchangePropertyType_name = "正常根据成交生成报单"

var _TThostFtdcExchangePropertyType_index = [...]uint8{0, 6, 30}

func (i TThostFtdcExchangePropertyType) String() string {
	i -= 48
	if i >= TThostFtdcExchangePropertyType(len(_TThostFtdcExchangePropertyType_index)-1) {
		return "TThostFtdcExchangePropertyType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcExchangePropertyType_name[_TThostFtdcExchangePropertyType_index[i]:_TThostFtdcExchangePropertyType_index[i+1]]
}
