// Code generated by "stringer -type TThostFtdcProductStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PS_tradeable-49]
	_ = x[THOST_FTDC_PS_untradeable-50]
}

const _TThostFtdcProductStatusType_name = "可交易不可交易"

var _TThostFtdcProductStatusType_index = [...]uint8{0, 9, 21}

func (i TThostFtdcProductStatusType) String() string {
	i -= 49
	if i >= TThostFtdcProductStatusType(len(_TThostFtdcProductStatusType_index)-1) {
		return "TThostFtdcProductStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcProductStatusType_name[_TThostFtdcProductStatusType_index[i]:_TThostFtdcProductStatusType_index[i+1]]
}
