// Code generated by "stringer -type TThostFtdcSponsorTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SPTYPE_Broker-48]
	_ = x[THOST_FTDC_SPTYPE_Bank-49]
}

const _TThostFtdcSponsorTypeType_name = "期商银行"

var _TThostFtdcSponsorTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcSponsorTypeType) String() string {
	i -= 48
	if i >= TThostFtdcSponsorTypeType(len(_TThostFtdcSponsorTypeType_index)-1) {
		return "TThostFtdcSponsorTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSponsorTypeType_name[_TThostFtdcSponsorTypeType_index[i]:_TThostFtdcSponsorTypeType_index[i+1]]
}
