// Code generated by "stringer -type TThostFtdcCommApiTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CAPIT_Client-49]
	_ = x[THOST_FTDC_CAPIT_Server-50]
	_ = x[THOST_FTDC_CAPIT_UserApi-51]
}

const _TThostFtdcCommApiTypeType_name = "客户端服务端交易系统的UserApi"

var _TThostFtdcCommApiTypeType_index = [...]uint8{0, 9, 18, 40}

func (i TThostFtdcCommApiTypeType) String() string {
	i -= 49
	if i >= TThostFtdcCommApiTypeType(len(_TThostFtdcCommApiTypeType_index)-1) {
		return "TThostFtdcCommApiTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcCommApiTypeType_name[_TThostFtdcCommApiTypeType_index[i]:_TThostFtdcCommApiTypeType_index[i+1]]
}
