// Code generated by "stringer -type TThostFtdcAlgoTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AT_HandlePositionAlgo-49]
	_ = x[THOST_FTDC_AT_FindMarginRateAlgo-50]
}

const _TThostFtdcAlgoTypeType_name = "持仓处理算法寻找保证金率算法"

var _TThostFtdcAlgoTypeType_index = [...]uint8{0, 18, 42}

func (i TThostFtdcAlgoTypeType) String() string {
	i -= 49
	if i >= TThostFtdcAlgoTypeType(len(_TThostFtdcAlgoTypeType_index)-1) {
		return "TThostFtdcAlgoTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcAlgoTypeType_name[_TThostFtdcAlgoTypeType_index[i]:_TThostFtdcAlgoTypeType_index[i+1]]
}
