// Code generated by "stringer -type TThostFtdcFundEventTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FET_Restriction-48]
	_ = x[THOST_FTDC_FET_TodayRestriction-49]
	_ = x[THOST_FTDC_FET_Transfer-50]
	_ = x[THOST_FTDC_FET_Credit-51]
	_ = x[THOST_FTDC_FET_InvestorWithdrawAlm-52]
	_ = x[THOST_FTDC_FET_BankRestriction-53]
	_ = x[THOST_FTDC_FET_Accountregister-54]
	_ = x[THOST_FTDC_FET_ExchangeFundIO-55]
	_ = x[THOST_FTDC_FET_InvestorFundIO-56]
}

const _TThostFtdcFundEventTypeType_name = "转账限额当日转账限额期商流水资金冻结投资者可提资金比例单个银行帐户转账限额银期签约账户交易所出入金投资者出入金"

var _TThostFtdcFundEventTypeType_index = [...]uint8{0, 12, 30, 42, 54, 81, 111, 129, 147, 165}

func (i TThostFtdcFundEventTypeType) String() string {
	i -= 48
	if i >= TThostFtdcFundEventTypeType(len(_TThostFtdcFundEventTypeType_index)-1) {
		return "TThostFtdcFundEventTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFundEventTypeType_name[_TThostFtdcFundEventTypeType_index[i]:_TThostFtdcFundEventTypeType_index[i+1]]
}
