// Code generated by "stringer -type TThostFtdcReportStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SRS_NoCreate-48]
	_ = x[THOST_FTDC_SRS_Create-49]
	_ = x[THOST_FTDC_SRS_Created-50]
	_ = x[THOST_FTDC_SRS_CreateFail-51]
}

const _TThostFtdcReportStatusType_name = "未生成报表数据报表数据生成中已生成报表数据生成报表数据失败"

var _TThostFtdcReportStatusType_index = [...]uint8{0, 21, 42, 63, 87}

func (i TThostFtdcReportStatusType) String() string {
	i -= 48
	if i >= TThostFtdcReportStatusType(len(_TThostFtdcReportStatusType_index)-1) {
		return "TThostFtdcReportStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcReportStatusType_name[_TThostFtdcReportStatusType_index[i]:_TThostFtdcReportStatusType_index[i+1]]
}
