// Code generated by "stringer -type TThostFtdcTradeSumStatModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TSSM_Instrument-49]
	_ = x[THOST_FTDC_TSSM_Product-50]
	_ = x[THOST_FTDC_TSSM_Exchange-51]
}

const _TThostFtdcTradeSumStatModeType_name = "按合约统计按产品统计按交易所统计"

var _TThostFtdcTradeSumStatModeType_index = [...]uint8{0, 15, 30, 48}

func (i TThostFtdcTradeSumStatModeType) String() string {
	i -= 49
	if i >= TThostFtdcTradeSumStatModeType(len(_TThostFtdcTradeSumStatModeType_index)-1) {
		return "TThostFtdcTradeSumStatModeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcTradeSumStatModeType_name[_TThostFtdcTradeSumStatModeType_index[i]:_TThostFtdcTradeSumStatModeType_index[i+1]]
}
