// Code generated by "stringer -type TThostFtdcStrikeTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_STT_Hedge-48]
	_ = x[THOST_FTDC_STT_Match-49]
}

const _TThostFtdcStrikeTypeType_name = "自身对冲匹配执行"

var _TThostFtdcStrikeTypeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcStrikeTypeType) String() string {
	i -= 48
	if i >= TThostFtdcStrikeTypeType(len(_TThostFtdcStrikeTypeType_index)-1) {
		return "TThostFtdcStrikeTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcStrikeTypeType_name[_TThostFtdcStrikeTypeType_index[i]:_TThostFtdcStrikeTypeType_index[i+1]]
}
