// Code generated by "stringer -type TThostFtdcOrderActionStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OAS_Submitted-97]
	_ = x[THOST_FTDC_OAS_Accepted-98]
	_ = x[THOST_FTDC_OAS_Rejected-99]
}

const _TThostFtdcOrderActionStatusType_name = "已经提交已经接受已经被拒绝"

var _TThostFtdcOrderActionStatusType_index = [...]uint8{0, 12, 24, 39}

func (i TThostFtdcOrderActionStatusType) String() string {
	i -= 97
	if i >= TThostFtdcOrderActionStatusType(len(_TThostFtdcOrderActionStatusType_index)-1) {
		return "TThostFtdcOrderActionStatusType(" + strconv.FormatInt(int64(i+97), 10) + ")"
	}
	return _TThostFtdcOrderActionStatusType_name[_TThostFtdcOrderActionStatusType_index[i]:_TThostFtdcOrderActionStatusType_index[i+1]]
}
