// Code generated by "stringer -type TThostFtdcClientIDTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CIDT_Speculation-49]
	_ = x[THOST_FTDC_CIDT_Arbitrage-50]
	_ = x[THOST_FTDC_CIDT_Hedge-51]
	_ = x[THOST_FTDC_CIDT_MarketMaker-53]
}

const (
	_TThostFtdcClientIDTypeType_name_0 = "投机套利套保"
	_TThostFtdcClientIDTypeType_name_1 = "做市商"
)

var (
	_TThostFtdcClientIDTypeType_index_0 = [...]uint8{0, 6, 12, 18}
)

func (i TThostFtdcClientIDTypeType) String() string {
	switch {
	case 49 <= i && i <= 51:
		i -= 49
		return _TThostFtdcClientIDTypeType_name_0[_TThostFtdcClientIDTypeType_index_0[i]:_TThostFtdcClientIDTypeType_index_0[i+1]]
	case i == 53:
		return _TThostFtdcClientIDTypeType_name_1
	default:
		return "TThostFtdcClientIDTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
