// Code generated by "stringer -type TThostFtdcFlexStatModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FSM_Product-49]
	_ = x[THOST_FTDC_FSM_Exchange-50]
	_ = x[THOST_FTDC_FSM_All-51]
}

const _TThostFtdcFlexStatModeType_name = "产品统计交易所统计统计所有"

var _TThostFtdcFlexStatModeType_index = [...]uint8{0, 12, 27, 39}

func (i TThostFtdcFlexStatModeType) String() string {
	i -= 49
	if i >= TThostFtdcFlexStatModeType(len(_TThostFtdcFlexStatModeType_index)-1) {
		return "TThostFtdcFlexStatModeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFlexStatModeType_name[_TThostFtdcFlexStatModeType_index[i]:_TThostFtdcFlexStatModeType_index[i+1]]
}
