// Code generated by "stringer -type TThostFtdcReturnStandardType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RSD_ByPeriod-49]
	_ = x[THOST_FTDC_RSD_ByStandard-50]
}

const _TThostFtdcReturnStandardType_name = "分阶段返还按某一标准"

var _TThostFtdcReturnStandardType_index = [...]uint8{0, 15, 30}

func (i TThostFtdcReturnStandardType) String() string {
	i -= 49
	if i >= TThostFtdcReturnStandardType(len(_TThostFtdcReturnStandardType_index)-1) {
		return "TThostFtdcReturnStandardType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcReturnStandardType_name[_TThostFtdcReturnStandardType_index[i]:_TThostFtdcReturnStandardType_index[i+1]]
}
