// Code generated by "stringer -type TThostFtdcFuturePwdFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FPWD_UnCheck-48]
	_ = x[THOST_FTDC_FPWD_Check-49]
}

const _TThostFtdcFuturePwdFlagType_name = "不核对核对"

var _TThostFtdcFuturePwdFlagType_index = [...]uint8{0, 9, 15}

func (i TThostFtdcFuturePwdFlagType) String() string {
	i -= 48
	if i >= TThostFtdcFuturePwdFlagType(len(_TThostFtdcFuturePwdFlagType_index)-1) {
		return "TThostFtdcFuturePwdFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFuturePwdFlagType_name[_TThostFtdcFuturePwdFlagType_index[i]:_TThostFtdcFuturePwdFlagType_index[i+1]]
}
