// Code generated by "stringer -type TThostFtdcInvestorRiskStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IRS_Normal-49]
	_ = x[THOST_FTDC_IRS_Warn-50]
	_ = x[THOST_FTDC_IRS_Call-51]
	_ = x[THOST_FTDC_IRS_Force-52]
	_ = x[THOST_FTDC_IRS_Exception-53]
}

const _TThostFtdcInvestorRiskStatusType_name = "正常警告追保强平异常"

var _TThostFtdcInvestorRiskStatusType_index = [...]uint8{0, 6, 12, 18, 24, 30}

func (i TThostFtdcInvestorRiskStatusType) String() string {
	i -= 49
	if i >= TThostFtdcInvestorRiskStatusType(len(_TThostFtdcInvestorRiskStatusType_index)-1) {
		return "TThostFtdcInvestorRiskStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcInvestorRiskStatusType_name[_TThostFtdcInvestorRiskStatusType_index[i]:_TThostFtdcInvestorRiskStatusType_index[i+1]]
}
