// Code generated by "stringer -type TThostFtdcResFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RESF_Success-48]
	_ = x[THOST_FTDC_RESF_InsuffiCient-49]
	_ = x[THOST_FTDC_RESF_UnKnown-56]
}

const (
	_TThostFtdcResFlagType_name_0 = "成功账户余额不足"
	_TThostFtdcResFlagType_name_1 = "交易结果未知"
)

var (
	_TThostFtdcResFlagType_index_0 = [...]uint8{0, 6, 24}
)

func (i TThostFtdcResFlagType) String() string {
	switch {
	case 48 <= i && i <= 49:
		i -= 48
		return _TThostFtdcResFlagType_name_0[_TThostFtdcResFlagType_index_0[i]:_TThostFtdcResFlagType_index_0[i+1]]
	case i == 56:
		return _TThostFtdcResFlagType_name_1
	default:
		return "TThostFtdcResFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
