// Code generated by "stringer -type TThostFtdcCCBFeeModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CCBFM_ByAmount-49]
	_ = x[THOST_FTDC_CCBFM_ByMonth-50]
}

const _TThostFtdcCCBFeeModeType_name = "按金额扣收按月扣收"

var _TThostFtdcCCBFeeModeType_index = [...]uint8{0, 15, 27}

func (i TThostFtdcCCBFeeModeType) String() string {
	i -= 49
	if i >= TThostFtdcCCBFeeModeType(len(_TThostFtdcCCBFeeModeType_index)-1) {
		return "TThostFtdcCCBFeeModeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcCCBFeeModeType_name[_TThostFtdcCCBFeeModeType_index[i]:_TThostFtdcCCBFeeModeType_index[i+1]]
}
