// Code generated by "stringer -type TThostFtdcPromptTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CPT_Instrument-49]
	_ = x[THOST_FTDC_CPT_Margin-50]
}

const _TThostFtdcPromptTypeType_name = "合约上下市保证金分段生效"

var _TThostFtdcPromptTypeType_index = [...]uint8{0, 15, 36}

func (i TThostFtdcPromptTypeType) String() string {
	i -= 49
	if i >= TThostFtdcPromptTypeType(len(_TThostFtdcPromptTypeType_index)-1) {
		return "TThostFtdcPromptTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcPromptTypeType_name[_TThostFtdcPromptTypeType_index[i]:_TThostFtdcPromptTypeType_index[i+1]]
}
