// Code generated by "stringer -type TThostFtdcTemplateTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TPT_Full-49]
	_ = x[THOST_FTDC_TPT_Increment-50]
	_ = x[THOST_FTDC_TPT_BackUp-51]
}

const _TThostFtdcTemplateTypeType_name = "全量增量备份"

var _TThostFtdcTemplateTypeType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcTemplateTypeType) String() string {
	i -= 49
	if i >= TThostFtdcTemplateTypeType(len(_TThostFtdcTemplateTypeType_index)-1) {
		return "TThostFtdcTemplateTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcTemplateTypeType_name[_TThostFtdcTemplateTypeType_index[i]:_TThostFtdcTemplateTypeType_index[i+1]]
}
