// Code generated by "stringer -type TThostFtdcAppTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_APP_TYPE_Investor-49]
	_ = x[THOST_FTDC_APP_TYPE_InvestorRelay-50]
	_ = x[THOST_FTDC_APP_TYPE_OperatorRelay-51]
	_ = x[THOST_FTDC_APP_TYPE_UnKnown-52]
}

const _TThostFtdcAppTypeType_name = "直连的投资者为每个投资者都创建连接的中继所有投资者共享一个操作员连接的中继未知"

var _TThostFtdcAppTypeType_index = [...]uint8{0, 18, 60, 111, 117}

func (i TThostFtdcAppTypeType) String() string {
	i -= 49
	if i >= TThostFtdcAppTypeType(len(_TThostFtdcAppTypeType_index)-1) {
		return "TThostFtdcAppTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcAppTypeType_name[_TThostFtdcAppTypeType_index[i]:_TThostFtdcAppTypeType_index[i+1]]
}
