// Code generated by "stringer -type TThostFtdcApplyStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AS2_Unknown-97]
	_ = x[THOST_FTDC_AS2_Canceled-48]
	_ = x[THOST_FTDC_AS2_Suspended-49]
	_ = x[THOST_FTDC_AS2_Accepted-51]
}

const (
	_TThostFtdcApplyStatusType_name_0 = "已撤销已挂起"
	_TThostFtdcApplyStatusType_name_1 = "申请成功"
	_TThostFtdcApplyStatusType_name_2 = "未知"
)

var (
	_TThostFtdcApplyStatusType_index_0 = [...]uint8{0, 9, 18}
)

func (i TThostFtdcApplyStatusType) String() string {
	switch {
	case 48 <= i && i <= 49:
		i -= 48
		return _TThostFtdcApplyStatusType_name_0[_TThostFtdcApplyStatusType_index_0[i]:_TThostFtdcApplyStatusType_index_0[i+1]]
	case i == 51:
		return _TThostFtdcApplyStatusType_name_1
	case i == 97:
		return _TThostFtdcApplyStatusType_name_2
	default:
		return "TThostFtdcApplyStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
