// Code generated by "stringer -type TThostFtdcAlgoTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AT_HandlePositionAlgo-49]
	_ = x[THOST_FTDC_AT_FindMarginRateAlgo-50]
}

const _TThostFtdcAlgoTypeType_name = "持仓处理算法寻找保证金率算法"

var _TThostFtdcAlgoTypeType_index = [...]uint8{0, 18, 42}

func (i TThostFtdcAlgoTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcAlgoTypeType_index)-1 {
		return "TThostFtdcAlgoTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcAlgoTypeType_name[_TThostFtdcAlgoTypeType_index[idx]:_TThostFtdcAlgoTypeType_index[idx+1]]
}
