// Code generated by "stringer -type TThostFtdcActionFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AF_Delete-48]
	_ = x[THOST_FTDC_AF_Modify-51]
}

const (
	_TThostFtdcActionFlagType_name_0 = "删除"
	_TThostFtdcActionFlagType_name_1 = "修改"
)

func (i TThostFtdcActionFlagType) String() string {
	switch {
	case i == 48:
		return _TThostFtdcActionFlagType_name_0
	case i == 51:
		return _TThostFtdcActionFlagType_name_1
	default:
		return "TThostFtdcActionFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
