// Code generated by "stringer -type TThostFtdcAccountSourceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AST_FBTransfer-48]
	_ = x[THOST_FTDC_AST_ManualEntry-49]
}

const _TThostFtdcAccountSourceTypeType_name = "银期同步手工录入"

var _TThostFtdcAccountSourceTypeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcAccountSourceTypeType) String() string {
	i -= 48
	if i >= TThostFtdcAccountSourceTypeType(len(_TThostFtdcAccountSourceTypeType_index)-1) {
		return "TThostFtdcAccountSourceTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcAccountSourceTypeType_name[_TThostFtdcAccountSourceTypeType_index[i]:_TThostFtdcAccountSourceTypeType_index[i+1]]
}
