// Code generated by "stringer -type TThostFtdcStrikeModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_STM_Continental-48]
	_ = x[THOST_FTDC_STM_American-49]
	_ = x[THOST_FTDC_STM_Bermuda-50]
}

const _TThostFtdcStrikeModeType_name = "欧式美式百慕大"

var _TThostFtdcStrikeModeType_index = [...]uint8{0, 6, 12, 21}

func (i TThostFtdcStrikeModeType) String() string {
	i -= 48
	if i >= TThostFtdcStrikeModeType(len(_TThostFtdcStrikeModeType_index)-1) {
		return "TThostFtdcStrikeModeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcStrikeModeType_name[_TThostFtdcStrikeModeType_index[i]:_TThostFtdcStrikeModeType_index[i+1]]
}
