// Code generated by "stringer -type TThostFtdcFBEExchStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBEES_Normal-48]
	_ = x[THOST_FTDC_FBEES_ReExchange-49]
}

const _TThostFtdcFBEExchStatusType_name = "正常交易重发"

var _TThostFtdcFBEExchStatusType_index = [...]uint8{0, 6, 18}

func (i TThostFtdcFBEExchStatusType) String() string {
	i -= 48
	if i >= TThostFtdcFBEExchStatusType(len(_TThostFtdcFBEExchStatusType_index)-1) {
		return "TThostFtdcFBEExchStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFBEExchStatusType_name[_TThostFtdcFBEExchStatusType_index[i]:_TThostFtdcFBEExchStatusType_index[i+1]]
}
