// Code generated by "stringer -type TThostFtdcExDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBEDIR_Settlement-48]
	_ = x[THOST_FTDC_FBEDIR_Sale-49]
}

const _TThostFtdcExDirectionType_name = "结汇售汇"

var _TThostFtdcExDirectionType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcExDirectionType) String() string {
	i -= 48
	if i >= TThostFtdcExDirectionType(len(_TThostFtdcExDirectionType_index)-1) {
		return "TThostFtdcExDirectionType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcExDirectionType_name[_TThostFtdcExDirectionType_index[i]:_TThostFtdcExDirectionType_index[i+1]]
}
