// Code generated by "stringer -type TThostFtdcFundMortDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FMD_In-49]
	_ = x[THOST_FTDC_FMD_Out-50]
}

const _TThostFtdcFundMortDirectionType_name = "货币质入货币质出"

var _TThostFtdcFundMortDirectionType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcFundMortDirectionType) String() string {
	i -= 49
	if i >= TThostFtdcFundMortDirectionType(len(_TThostFtdcFundMortDirectionType_index)-1) {
		return "TThostFtdcFundMortDirectionType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundMortDirectionType_name[_TThostFtdcFundMortDirectionType_index[i]:_TThostFtdcFundMortDirectionType_index[i+1]]
}
