// Code generated by "stringer -type TThostFtdcBrokerUserTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BUT_Investor-49]
	_ = x[THOST_FTDC_BUT_BrokerUser-50]
}

const _TThostFtdcBrokerUserTypeType_name = "投资者操作员"

var _TThostFtdcBrokerUserTypeType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcBrokerUserTypeType) String() string {
	i -= 49
	if i >= TThostFtdcBrokerUserTypeType(len(_TThostFtdcBrokerUserTypeType_index)-1) {
		return "TThostFtdcBrokerUserTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcBrokerUserTypeType_name[_TThostFtdcBrokerUserTypeType_index[i]:_TThostFtdcBrokerUserTypeType_index[i+1]]
}
