// Code generated by "stringer -type TThostFtdcOffsetTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OT_OPT_OFFSET-48]
	_ = x[THOST_FTDC_OT_FUT_OFFSET-49]
	_ = x[THOST_FTDC_OT_EXEC_OFFSET-50]
	_ = x[THOST_FTDC_OT_PERFORM_OFFSET-51]
}

const _TThostFtdcOffsetTypeType_name = "期权对冲期货对冲行权后期货对冲履约后期货对冲"

var _TThostFtdcOffsetTypeType_index = [...]uint8{0, 12, 24, 45, 66}

func (i TThostFtdcOffsetTypeType) String() string {
	i -= 48
	if i >= TThostFtdcOffsetTypeType(len(_TThostFtdcOffsetTypeType_index)-1) {
		return "TThostFtdcOffsetTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOffsetTypeType_name[_TThostFtdcOffsetTypeType_index[i]:_TThostFtdcOffsetTypeType_index[i+1]]
}
