// Code generated by "stringer -type TThostFtdcSettlementStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_STS_Initialize-48]
	_ = x[THOST_FTDC_STS_Settlementing-49]
	_ = x[THOST_FTDC_STS_Settlemented-50]
	_ = x[THOST_FTDC_STS_Finished-51]
}

const _TThostFtdcSettlementStatusType_name = "初始结算中已结算结算完成"

var _TThostFtdcSettlementStatusType_index = [...]uint8{0, 6, 15, 24, 36}

func (i TThostFtdcSettlementStatusType) String() string {
	i -= 48
	if i >= TThostFtdcSettlementStatusType(len(_TThostFtdcSettlementStatusType_index)-1) {
		return "TThostFtdcSettlementStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSettlementStatusType_name[_TThostFtdcSettlementStatusType_index[i]:_TThostFtdcSettlementStatusType_index[i+1]]
}
