// Code generated by "stringer -type TThostFtdcCfmmcReturnCodeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CRC_Success-48]
	_ = x[THOST_FTDC_CRC_Working-49]
	_ = x[THOST_FTDC_CRC_InfoFail-50]
	_ = x[THOST_FTDC_CRC_IDCardFail-51]
	_ = x[THOST_FTDC_CRC_OtherFail-52]
}

const _TThostFtdcCfmmcReturnCodeType_name = "成功该客户已经有流程在处理中监控中客户资料检查失败监控中实名制检查失败其他错误"

var _TThostFtdcCfmmcReturnCodeType_index = [...]uint8{0, 6, 42, 75, 105, 117}

func (i TThostFtdcCfmmcReturnCodeType) String() string {
	i -= 48
	if i >= TThostFtdcCfmmcReturnCodeType(len(_TThostFtdcCfmmcReturnCodeType_index)-1) {
		return "TThostFtdcCfmmcReturnCodeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCfmmcReturnCodeType_name[_TThostFtdcCfmmcReturnCodeType_index[i]:_TThostFtdcCfmmcReturnCodeType_index[i+1]]
}
