// Code generated by "stringer -type TThostFtdcInvstTradingRightType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ITR_CloseOnly-49]
	_ = x[THOST_FTDC_ITR_Forbidden-50]
}

const _TThostFtdcInvstTradingRightType_name = "只能平仓不能交易"

var _TThostFtdcInvstTradingRightType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcInvstTradingRightType) String() string {
	i -= 49
	if i >= TThostFtdcInvstTradingRightType(len(_TThostFtdcInvstTradingRightType_index)-1) {
		return "TThostFtdcInvstTradingRightType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcInvstTradingRightType_name[_TThostFtdcInvstTradingRightType_index[i]:_TThostFtdcInvstTradingRightType_index[i+1]]
}
