// Code generated by "stringer -type TThostFtdcCashExchangeCodeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CEC_Exchange-49]
	_ = x[THOST_FTDC_CEC_Cash-50]
}

const _TThostFtdcCashExchangeCodeType_name = "汇钞"

var _TThostFtdcCashExchangeCodeType_index = [...]uint8{0, 3, 6}

func (i TThostFtdcCashExchangeCodeType) String() string {
	i -= 49
	if i >= TThostFtdcCashExchangeCodeType(len(_TThostFtdcCashExchangeCodeType_index)-1) {
		return "TThostFtdcCashExchangeCodeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcCashExchangeCodeType_name[_TThostFtdcCashExchangeCodeType_index[i]:_TThostFtdcCashExchangeCodeType_index[i+1]]
}
