// Code generated by "stringer -type TThostFtdcUOAAssetmgrTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UOAAT_Futures-49]
	_ = x[THOST_FTDC_UOAAT_SpecialOrgan-50]
}

const _TThostFtdcUOAAssetmgrTypeType_name = "期货类综合类"

var _TThostFtdcUOAAssetmgrTypeType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcUOAAssetmgrTypeType) String() string {
	i -= 49
	if i >= TThostFtdcUOAAssetmgrTypeType(len(_TThostFtdcUOAAssetmgrTypeType_index)-1) {
		return "TThostFtdcUOAAssetmgrTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcUOAAssetmgrTypeType_name[_TThostFtdcUOAAssetmgrTypeType_index[i]:_TThostFtdcUOAAssetmgrTypeType_index[i+1]]
}
