// Code generated by "stringer -type TThostFtdcReturnStyleType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RS_All-49]
	_ = x[THOST_FTDC_RS_ByProduct-50]
}

const _TThostFtdcReturnStyleType_name = "按所有品种按品种"

var _TThostFtdcReturnStyleType_index = [...]uint8{0, 15, 24}

func (i TThostFtdcReturnStyleType) String() string {
	i -= 49
	if i >= TThostFtdcReturnStyleType(len(_TThostFtdcReturnStyleType_index)-1) {
		return "TThostFtdcReturnStyleType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcReturnStyleType_name[_TThostFtdcReturnStyleType_index[i]:_TThostFtdcReturnStyleType_index[i+1]]
}
