// Code generated by "stringer -type TThostFtdcSpecPosiTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SPOST_Common-35]
	_ = x[THOST_FTDC_SPOST_Tas-48]
}

const (
	_TThostFtdcSpecPosiTypeType_name_0 = "普通持仓明细"
	_TThostFtdcSpecPosiTypeType_name_1 = "TAS合约成交产生的标的合约持仓明细"
)

func (i TThostFtdcSpecPosiTypeType) String() string {
	switch {
	case i == 35:
		return _TThostFtdcSpecPosiTypeType_name_0
	case i == 48:
		return _TThostFtdcSpecPosiTypeType_name_1
	default:
		return "TThostFtdcSpecPosiTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
