// Code generated by "stringer -type TThostFtdcFundDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FD_In-49]
	_ = x[THOST_FTDC_FD_Out-50]
}

const _TThostFtdcFundDirectionType_name = "入金出金"

var _TThostFtdcFundDirectionType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcFundDirectionType) String() string {
	i -= 49
	if i >= TThostFtdcFundDirectionType(len(_TThostFtdcFundDirectionType_index)-1) {
		return "TThostFtdcFundDirectionType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundDirectionType_name[_TThostFtdcFundDirectionType_index[i]:_TThostFtdcFundDirectionType_index[i+1]]
}
