// Code generated by "stringer -type TThostFtdcSettleManagerLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SML_Must-49]
	_ = x[THOST_FTDC_SML_Alarm-50]
	_ = x[THOST_FTDC_SML_Prompt-51]
	_ = x[THOST_FTDC_SML_Ignore-52]
}

const _TThostFtdcSettleManagerLevelType_name = "必要警告提示不检查"

var _TThostFtdcSettleManagerLevelType_index = [...]uint8{0, 6, 12, 18, 27}

func (i TThostFtdcSettleManagerLevelType) String() string {
	i -= 49
	if i >= TThostFtdcSettleManagerLevelType(len(_TThostFtdcSettleManagerLevelType_index)-1) {
		return "TThostFtdcSettleManagerLevelType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSettleManagerLevelType_name[_TThostFtdcSettleManagerLevelType_index[i]:_TThostFtdcSettleManagerLevelType_index[i+1]]
}
