// Code generated by "stringer -type TThostFtdcApplySrcType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AS_Trade-48]
	_ = x[THOST_FTDC_AS_Member-49]
}

const _TThostFtdcApplySrcType_name = "交易会服"

var _TThostFtdcApplySrcType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcApplySrcType) String() string {
	i -= 48
	if i >= TThostFtdcApplySrcType(len(_TThostFtdcApplySrcType_index)-1) {
		return "TThostFtdcApplySrcType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcApplySrcType_name[_TThostFtdcApplySrcType_index[i]:_TThostFtdcApplySrcType_index[i+1]]
}
