// Code generated by "stringer -type TThostFtdcFunctionCodeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FC_DataAsync-49]
	_ = x[THOST_FTDC_FC_ForceUserLogout-50]
	_ = x[THOST_FTDC_FC_UserPasswordUpdate-51]
	_ = x[THOST_FTDC_FC_BrokerPasswordUpdate-52]
	_ = x[THOST_FTDC_FC_InvestorPasswordUpdate-53]
	_ = x[THOST_FTDC_FC_OrderInsert-54]
	_ = x[THOST_FTDC_FC_OrderAction-55]
	_ = x[THOST_FTDC_FC_SyncSystemData-56]
	_ = x[THOST_FTDC_FC_SyncBrokerData-57]
	_ = x[THOST_FTDC_FC_BachSyncBrokerData-65]
	_ = x[THOST_FTDC_FC_SuperQuery-66]
	_ = x[THOST_FTDC_FC_ParkedOrderInsert-67]
	_ = x[THOST_FTDC_FC_ParkedOrderAction-68]
	_ = x[THOST_FTDC_FC_SyncOTP-69]
	_ = x[THOST_FTDC_FC_DeleteOrder-70]
	_ = x[THOST_FTDC_FC_ExitEmergency-71]
}

const (
	_TThostFtdcFunctionCodeType_name_0 = "数据异步化强制用户登出变更管理用户口令变更经纪公司口令变更投资者口令报单插入报单操作同步系统数据同步经纪公司数据"
	_TThostFtdcFunctionCodeType_name_1 = "批量同步经纪公司数据超级查询预埋报单插入预埋报单操作同步动态令牌删除未知单退出紧急状态"
)

var (
	_TThostFtdcFunctionCodeType_index_0 = [...]uint8{0, 15, 33, 57, 81, 102, 114, 126, 144, 168}
	_TThostFtdcFunctionCodeType_index_1 = [...]uint8{0, 30, 42, 60, 78, 96, 111, 129}
)

func (i TThostFtdcFunctionCodeType) String() string {
	switch {
	case 49 <= i && i <= 57:
		i -= 49
		return _TThostFtdcFunctionCodeType_name_0[_TThostFtdcFunctionCodeType_index_0[i]:_TThostFtdcFunctionCodeType_index_0[i+1]]
	case 65 <= i && i <= 71:
		i -= 65
		return _TThostFtdcFunctionCodeType_name_1[_TThostFtdcFunctionCodeType_index_1[i]:_TThostFtdcFunctionCodeType_index_1[i+1]]
	default:
		return "TThostFtdcFunctionCodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
