// Code generated by "stringer -type TThostFtdcOTPTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OTP_NONE-48]
	_ = x[THOST_FTDC_OTP_TOTP-49]
}

const _TThostFtdcOTPTypeType_name = "无动态令牌时间令牌"

var _TThostFtdcOTPTypeType_index = [...]uint8{0, 15, 27}

func (i TThostFtdcOTPTypeType) String() string {
	i -= 48
	if i >= TThostFtdcOTPTypeType(len(_TThostFtdcOTPTypeType_index)-1) {
		return "TThostFtdcOTPTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOTPTypeType_name[_TThostFtdcOTPTypeType_index[i]:_TThostFtdcOTPTypeType_index[i+1]]
}
