// Code generated by "stringer -type TThostFtdcHandleTradingAccountAlgoIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_HTAA_Base-49]
	_ = x[THOST_FTDC_HTAA_DCE-50]
	_ = x[THOST_FTDC_HTAA_CZCE-51]
}

const _TThostFtdcHandleTradingAccountAlgoIDType_name = "基本大连商品交易所郑州商品交易所"

var _TThostFtdcHandleTradingAccountAlgoIDType_index = [...]uint8{0, 6, 27, 48}

func (i TThostFtdcHandleTradingAccountAlgoIDType) String() string {
	i -= 49
	if i >= TThostFtdcHandleTradingAccountAlgoIDType(len(_TThostFtdcHandleTradingAccountAlgoIDType_index)-1) {
		return "TThostFtdcHandleTradingAccountAlgoIDType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcHandleTradingAccountAlgoIDType_name[_TThostFtdcHandleTradingAccountAlgoIDType_index[i]:_TThostFtdcHandleTradingAccountAlgoIDType_index[i+1]]
}
