// Code generated by "stringer -type TThostFtdcFindMarginRateAlgoIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FMRA_Base-49]
	_ = x[THOST_FTDC_FMRA_DCE-50]
	_ = x[THOST_FTDC_FMRA_CZCE-51]
}

const _TThostFtdcFindMarginRateAlgoIDType_name = "基本大连商品交易所郑州商品交易所"

var _TThostFtdcFindMarginRateAlgoIDType_index = [...]uint8{0, 6, 27, 48}

func (i TThostFtdcFindMarginRateAlgoIDType) String() string {
	i -= 49
	if i >= TThostFtdcFindMarginRateAlgoIDType(len(_TThostFtdcFindMarginRateAlgoIDType_index)-1) {
		return "TThostFtdcFindMarginRateAlgoIDType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFindMarginRateAlgoIDType_name[_TThostFtdcFindMarginRateAlgoIDType_index[i]:_TThostFtdcFindMarginRateAlgoIDType_index[i+1]]
}
