// Code generated by "stringer -type TThostFtdcOrderTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ORDT_Normal-48]
	_ = x[THOST_FTDC_ORDT_DeriveFromQuote-49]
	_ = x[THOST_FTDC_ORDT_DeriveFromCombination-50]
	_ = x[THOST_FTDC_ORDT_Combination-51]
	_ = x[THOST_FTDC_ORDT_ConditionalOrder-52]
	_ = x[THOST_FTDC_ORDT_Swap-53]
	_ = x[THOST_FTDC_ORDT_DeriveFromBlockTrade-54]
	_ = x[THOST_FTDC_ORDT_DeriveFromEFPTrade-55]
}

const _TThostFtdcOrderTypeType_name = "正常报价衍生组合衍生组合报单条件单互换单大宗交易成交衍生期转现成交衍生"

var _TThostFtdcOrderTypeType_index = [...]uint8{0, 6, 18, 30, 42, 51, 60, 84, 105}

func (i TThostFtdcOrderTypeType) String() string {
	i -= 48
	if i >= TThostFtdcOrderTypeType(len(_TThostFtdcOrderTypeType_index)-1) {
		return "TThostFtdcOrderTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOrderTypeType_name[_TThostFtdcOrderTypeType_index[i]:_TThostFtdcOrderTypeType_index[i+1]]
}
