// Code generated by "stringer -type TThostFtdcAssetmgrTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ASST_Futures-51]
	_ = x[THOST_FTDC_ASST_SpecialOrgan-52]
}

const _TThostFtdcAssetmgrTypeType_name = "期货类综合类"

var _TThostFtdcAssetmgrTypeType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcAssetmgrTypeType) String() string {
	i -= 51
	if i >= TThostFtdcAssetmgrTypeType(len(_TThostFtdcAssetmgrTypeType_index)-1) {
		return "TThostFtdcAssetmgrTypeType(" + strconv.FormatInt(int64(i+51), 10) + ")"
	}
	return _TThostFtdcAssetmgrTypeType_name[_TThostFtdcAssetmgrTypeType_index[i]:_TThostFtdcAssetmgrTypeType_index[i+1]]
}
