// Code generated by "stringer -type TThostFtdcGenderType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_GD_Unknown-48]
	_ = x[THOST_FTDC_GD_Male-49]
	_ = x[THOST_FTDC_GD_Female-50]
}

const _TThostFtdcGenderType_name = "未知状态男女"

var _TThostFtdcGenderType_index = [...]uint8{0, 12, 15, 18}

func (i TThostFtdcGenderType) String() string {
	i -= 48
	if i >= TThostFtdcGenderType(len(_TThostFtdcGenderType_index)-1) {
		return "TThostFtdcGenderType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcGenderType_name[_TThostFtdcGenderType_index[i]:_TThostFtdcGenderType_index[i+1]]
}
