// Code generated by "stringer -type TThostFtdcFundMortgageTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FMT_Mortgage-49]
	_ = x[THOST_FTDC_FMT_Redemption-50]
}

const _TThostFtdcFundMortgageTypeType_name = "质押解质"

var _TThostFtdcFundMortgageTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcFundMortgageTypeType) String() string {
	i -= 49
	if i >= TThostFtdcFundMortgageTypeType(len(_TThostFtdcFundMortgageTypeType_index)-1) {
		return "TThostFtdcFundMortgageTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundMortgageTypeType_name[_TThostFtdcFundMortgageTypeType_index[i]:_TThostFtdcFundMortgageTypeType_index[i+1]]
}
