// Code generated by "stringer -type TThostFtdcSendMethodType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UOASM_ByAPI-49]
	_ = x[THOST_FTDC_UOASM_ByFile-50]
}

const _TThostFtdcSendMethodType_name = "文件发送电子发送"

var _TThostFtdcSendMethodType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcSendMethodType) String() string {
	i -= 49
	if i >= TThostFtdcSendMethodType(len(_TThostFtdcSendMethodType_index)-1) {
		return "TThostFtdcSendMethodType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSendMethodType_name[_TThostFtdcSendMethodType_index[i]:_TThostFtdcSendMethodType_index[i+1]]
}
