// Code generated by "stringer -type TThostFtdcManageStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MSS_Point-48]
	_ = x[THOST_FTDC_MSS_PrePoint-49]
	_ = x[THOST_FTDC_MSS_CancelPoint-50]
}

const _TThostFtdcManageStatusType_name = "指定存管预指定撤销指定"

var _TThostFtdcManageStatusType_index = [...]uint8{0, 12, 21, 33}

func (i TThostFtdcManageStatusType) String() string {
	i -= 48
	if i >= TThostFtdcManageStatusType(len(_TThostFtdcManageStatusType_index)-1) {
		return "TThostFtdcManageStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcManageStatusType_name[_TThostFtdcManageStatusType_index[i]:_TThostFtdcManageStatusType_index[i+1]]
}
