// Code generated by "stringer -type TThostFtdcFeePayFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FPF_BEN-48]
	_ = x[THOST_FTDC_FPF_OUR-49]
	_ = x[THOST_FTDC_FPF_SHA-50]
}

const _TThostFtdcFeePayFlagType_name = "由受益方支付费用由发送方支付费用由发送方支付发起的费用，受益方支付接受的费用"

var _TThostFtdcFeePayFlagType_index = [...]uint8{0, 24, 48, 114}

func (i TThostFtdcFeePayFlagType) String() string {
	i -= 48
	if i >= TThostFtdcFeePayFlagType(len(_TThostFtdcFeePayFlagType_index)-1) {
		return "TThostFtdcFeePayFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFeePayFlagType_name[_TThostFtdcFeePayFlagType_index[i]:_TThostFtdcFeePayFlagType_index[i+1]]
}
