// Code generated by "stringer -type TThostFtdcCTPTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CTPT_Unkown-48]
	_ = x[THOST_FTDC_CTPT_MainCenter-49]
	_ = x[THOST_FTDC_CTPT_BackUp-50]
}

const _TThostFtdcCTPTypeType_name = "未知类型主中心备中心"

var _TThostFtdcCTPTypeType_index = [...]uint8{0, 12, 21, 30}

func (i TThostFtdcCTPTypeType) String() string {
	i -= 48
	if i >= TThostFtdcCTPTypeType(len(_TThostFtdcCTPTypeType_index)-1) {
		return "TThostFtdcCTPTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCTPTypeType_name[_TThostFtdcCTPTypeType_index[i]:_TThostFtdcCTPTypeType_index[i+1]]
}
