// Code generated by "stringer -type TThostFtdcSyncDeltaStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SDS_Readable-49]
	_ = x[THOST_FTDC_SDS_Reading-50]
	_ = x[THOST_FTDC_SDS_Readend-51]
	_ = x[THOST_FTDC_SDS_OptErr-101]
}

const (
	_TThostFtdcSyncDeltaStatusType_name_0 = "交易可读交易在读交易读取完成"
	_TThostFtdcSyncDeltaStatusType_name_1 = "追平失败 交易本地状态结算不存在"
)

var (
	_TThostFtdcSyncDeltaStatusType_index_0 = [...]uint8{0, 12, 24, 42}
)

func (i TThostFtdcSyncDeltaStatusType) String() string {
	switch {
	case 49 <= i && i <= 51:
		i -= 49
		return _TThostFtdcSyncDeltaStatusType_name_0[_TThostFtdcSyncDeltaStatusType_index_0[i]:_TThostFtdcSyncDeltaStatusType_index_0[i+1]]
	case i == 101:
		return _TThostFtdcSyncDeltaStatusType_name_1
	default:
		return "TThostFtdcSyncDeltaStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
