// Code generated by "stringer -type TThostFtdcFBEFileFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBEFG_DataPackage-48]
	_ = x[THOST_FTDC_FBEFG_File-49]
}

const _TThostFtdcFBEFileFlagType_name = "数据包文件"

var _TThostFtdcFBEFileFlagType_index = [...]uint8{0, 9, 15}

func (i TThostFtdcFBEFileFlagType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcFBEFileFlagType_index)-1 {
		return "TThostFtdcFBEFileFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcFBEFileFlagType_name[_TThostFtdcFBEFileFlagType_index[idx]:_TThostFtdcFBEFileFlagType_index[idx+1]]
}
