// Code generated by "stringer -type TThostFtdcWeakPasswordSourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_WPSR_Lib-49]
	_ = x[THOST_FTDC_WPSR_Manual-50]
}

const _TThostFtdcWeakPasswordSourceType_name = "弱密码库手工录入"

var _TThostFtdcWeakPasswordSourceType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcWeakPasswordSourceType) String() string {
	i -= 49
	if i >= TThostFtdcWeakPasswordSourceType(len(_TThostFtdcWeakPasswordSourceType_index)-1) {
		return "TThostFtdcWeakPasswordSourceType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcWeakPasswordSourceType_name[_TThostFtdcWeakPasswordSourceType_index[i]:_TThostFtdcWeakPasswordSourceType_index[i+1]]
}
