// Code generated by "stringer -type TThostFtdcCombDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CMDR_Comb-48]
	_ = x[THOST_FTDC_CMDR_UnComb-49]
	_ = x[THOST_FTDC_CMDR_DelComb-50]
}

const _TThostFtdcCombDirectionType_name = "申请组合申请拆分操作员删组合单"

var _TThostFtdcCombDirectionType_index = [...]uint8{0, 12, 24, 45}

func (i TThostFtdcCombDirectionType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcCombDirectionType_index)-1 {
		return "TThostFtdcCombDirectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcCombDirectionType_name[_TThostFtdcCombDirectionType_index[idx]:_TThostFtdcCombDirectionType_index[idx+1]]
}
