// Code generated by "stringer -type TThostFtdcReqRspTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_REQRSP_Request-48]
	_ = x[THOST_FTDC_REQRSP_Response-49]
}

const _TThostFtdcReqRspTypeType_name = "请求响应"

var _TThostFtdcReqRspTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcReqRspTypeType) String() string {
	i -= 48
	if i >= TThostFtdcReqRspTypeType(len(_TThostFtdcReqRspTypeType_index)-1) {
		return "TThostFtdcReqRspTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcReqRspTypeType_name[_TThostFtdcReqRspTypeType_index[i]:_TThostFtdcReqRspTypeType_index[i+1]]
}
