// Code generated by "stringer -type TThostFtdcCloseDealTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CDT_Normal-48]
	_ = x[THOST_FTDC_CDT_SpecFirst-49]
}

const _TThostFtdcCloseDealTypeType_name = "正常投机平仓优先"

var _TThostFtdcCloseDealTypeType_index = [...]uint8{0, 6, 24}

func (i TThostFtdcCloseDealTypeType) String() string {
	i -= 48
	if i >= TThostFtdcCloseDealTypeType(len(_TThostFtdcCloseDealTypeType_index)-1) {
		return "TThostFtdcCloseDealTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCloseDealTypeType_name[_TThostFtdcCloseDealTypeType_index[i]:_TThostFtdcCloseDealTypeType_index[i+1]]
}
