// Code generated by "stringer -type TThostFtdcDAClientTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CACT_Person-48]
	_ = x[THOST_FTDC_CACT_Company-49]
	_ = x[THOST_FTDC_CACT_Other-50]
}

const _TThostFtdcDAClientTypeType_name = "自然人法人其他"

var _TThostFtdcDAClientTypeType_index = [...]uint8{0, 9, 15, 21}

func (i TThostFtdcDAClientTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcDAClientTypeType_index)-1 {
		return "TThostFtdcDAClientTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcDAClientTypeType_name[_TThostFtdcDAClientTypeType_index[idx]:_TThostFtdcDAClientTypeType_index[idx+1]]
}
