// Code generated by "stringer -type TThostFtdcCodeSourceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CST_UnifyAccount-48]
	_ = x[THOST_FTDC_CST_ManualEntry-49]
}

const _TThostFtdcCodeSourceTypeType_name = "统一开户(已规范)手工录入(未规范)"

var _TThostFtdcCodeSourceTypeType_index = [...]uint8{0, 23, 46}

func (i TThostFtdcCodeSourceTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcCodeSourceTypeType_index)-1 {
		return "TThostFtdcCodeSourceTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcCodeSourceTypeType_name[_TThostFtdcCodeSourceTypeType_index[idx]:_TThostFtdcCodeSourceTypeType_index[idx+1]]
}
