// Code generated by "stringer -type TThostFtdcReqFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_REQF_NoSend-48]
	_ = x[THOST_FTDC_REQF_SendSuccess-49]
	_ = x[THOST_FTDC_REQF_SendFailed-50]
	_ = x[THOST_FTDC_REQF_WaitReSend-51]
}

const _TThostFtdcReqFlagType_name = "未发送发送成功发送失败等待重发"

var _TThostFtdcReqFlagType_index = [...]uint8{0, 9, 21, 33, 45}

func (i TThostFtdcReqFlagType) String() string {
	i -= 48
	if i >= TThostFtdcReqFlagType(len(_TThostFtdcReqFlagType_index)-1) {
		return "TThostFtdcReqFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcReqFlagType_name[_TThostFtdcReqFlagType_index[i]:_TThostFtdcReqFlagType_index[i+1]]
}
