// Code generated by "stringer -type TThostFtdcNoteTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_NOTETYPE_TradeSettleBill-49]
	_ = x[THOST_FTDC_NOTETYPE_TradeSettleMonth-50]
	_ = x[THOST_FTDC_NOTETYPE_CallMarginNotes-51]
	_ = x[THOST_FTDC_NOTETYPE_ForceCloseNotes-52]
	_ = x[THOST_FTDC_NOTETYPE_TradeNotes-53]
	_ = x[THOST_FTDC_NOTETYPE_DelivNotes-54]
}

const _TThostFtdcNoteTypeType_name = "交易结算单交易结算月报追加保证金通知书强行平仓通知书成交通知书交割通知书"

var _TThostFtdcNoteTypeType_index = [...]uint8{0, 15, 33, 57, 78, 93, 108}

func (i TThostFtdcNoteTypeType) String() string {
	i -= 49
	if i >= TThostFtdcNoteTypeType(len(_TThostFtdcNoteTypeType_index)-1) {
		return "TThostFtdcNoteTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcNoteTypeType_name[_TThostFtdcNoteTypeType_index[i]:_TThostFtdcNoteTypeType_index[i+1]]
}
