// Code generated by "stringer -type TThostFtdcInstitutionTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TS_Bank-48]
	_ = x[THOST_FTDC_TS_Future-49]
	_ = x[THOST_FTDC_TS_Store-50]
}

const _TThostFtdcInstitutionTypeType_name = "银行期商券商"

var _TThostFtdcInstitutionTypeType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcInstitutionTypeType) String() string {
	i -= 48
	if i >= TThostFtdcInstitutionTypeType(len(_TThostFtdcInstitutionTypeType_index)-1) {
		return "TThostFtdcInstitutionTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcInstitutionTypeType_name[_TThostFtdcInstitutionTypeType_index[i]:_TThostFtdcInstitutionTypeType_index[i+1]]
}
