// Code generated by "stringer -type TThostFtdcMortgageFundUseRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MFUR_None-48]
	_ = x[THOST_FTDC_MFUR_Margin-49]
	_ = x[THOST_FTDC_MFUR_All-50]
	_ = x[THOST_FTDC_MFUR_CNY3-51]
}

const _TThostFtdcMortgageFundUseRangeType_name = "不能使用用于保证金用于手续费、盈亏、保证金人民币方案3"

var _TThostFtdcMortgageFundUseRangeType_index = [...]uint8{0, 12, 27, 63, 79}

func (i TThostFtdcMortgageFundUseRangeType) String() string {
	i -= 48
	if i >= TThostFtdcMortgageFundUseRangeType(len(_TThostFtdcMortgageFundUseRangeType_index)-1) {
		return "TThostFtdcMortgageFundUseRangeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcMortgageFundUseRangeType_name[_TThostFtdcMortgageFundUseRangeType_index[i]:_TThostFtdcMortgageFundUseRangeType_index[i+1]]
}
