// Code generated by "stringer -type TThostFtdcStrikeOffsetTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_STOV_RealValue-49]
	_ = x[THOST_FTDC_STOV_ProfitValue-50]
	_ = x[THOST_FTDC_STOV_RealRatio-51]
	_ = x[THOST_FTDC_STOV_ProfitRatio-52]
}

const _TThostFtdcStrikeOffsetTypeType_name = "实值额盈利额实值比例盈利比例"

var _TThostFtdcStrikeOffsetTypeType_index = [...]uint8{0, 9, 18, 30, 42}

func (i TThostFtdcStrikeOffsetTypeType) String() string {
	i -= 49
	if i >= TThostFtdcStrikeOffsetTypeType(len(_TThostFtdcStrikeOffsetTypeType_index)-1) {
		return "TThostFtdcStrikeOffsetTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcStrikeOffsetTypeType_name[_TThostFtdcStrikeOffsetTypeType_index[i]:_TThostFtdcStrikeOffsetTypeType_index[i+1]]
}
