// Code generated by "stringer -type TThostFtdcTraderConnectStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TCS_NotConnected-49]
	_ = x[THOST_FTDC_TCS_Connected-50]
	_ = x[THOST_FTDC_TCS_QryInstrumentSent-51]
	_ = x[THOST_FTDC_TCS_SubPrivateFlow-52]
}

const _TThostFtdcTraderConnectStatusType_name = "没有任何连接已经连接已经发出合约查询请求订阅私有流"

var _TThostFtdcTraderConnectStatusType_index = [...]uint8{0, 18, 30, 60, 75}

func (i TThostFtdcTraderConnectStatusType) String() string {
	i -= 49
	if i >= TThostFtdcTraderConnectStatusType(len(_TThostFtdcTraderConnectStatusType_index)-1) {
		return "TThostFtdcTraderConnectStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcTraderConnectStatusType_name[_TThostFtdcTraderConnectStatusType_index[i]:_TThostFtdcTraderConnectStatusType_index[i+1]]
}
