// Code generated by "stringer -type TThostFtdcAMLGenStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_GEN_Program-48]
	_ = x[THOST_FTDC_GEN_HandWork-49]
}

const _TThostFtdcAMLGenStatusType_name = "程序生成人工生成"

var _TThostFtdcAMLGenStatusType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcAMLGenStatusType) String() string {
	i -= 48
	if i >= TThostFtdcAMLGenStatusType(len(_TThostFtdcAMLGenStatusType_index)-1) {
		return "TThostFtdcAMLGenStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcAMLGenStatusType_name[_TThostFtdcAMLGenStatusType_index[i]:_TThostFtdcAMLGenStatusType_index[i+1]]
}
