// Code generated by "stringer -type TThostFtdcDataResourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DAR_Settle-49]
	_ = x[THOST_FTDC_DAR_Exchange-50]
	_ = x[THOST_FTDC_DAR_CSRC-51]
}

const _TThostFtdcDataResourceType_name = "本系统交易所报送数据"

var _TThostFtdcDataResourceType_index = [...]uint8{0, 9, 18, 30}

func (i TThostFtdcDataResourceType) String() string {
	i -= 49
	if i >= TThostFtdcDataResourceType(len(_TThostFtdcDataResourceType_index)-1) {
		return "TThostFtdcDataResourceType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcDataResourceType_name[_TThostFtdcDataResourceType_index[i]:_TThostFtdcDataResourceType_index[i+1]]
}
