// Code generated by "stringer -type TThostFtdcTradingTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TD_ALL-48]
	_ = x[THOST_FTDC_TD_TRADE-49]
	_ = x[THOST_FTDC_TD_UNTRADE-50]
}

const _TThostFtdcTradingTypeType_name = "所有状态交易非交易"

var _TThostFtdcTradingTypeType_index = [...]uint8{0, 12, 18, 27}

func (i TThostFtdcTradingTypeType) String() string {
	i -= 48
	if i >= TThostFtdcTradingTypeType(len(_TThostFtdcTradingTypeType_index)-1) {
		return "TThostFtdcTradingTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcTradingTypeType_name[_TThostFtdcTradingTypeType_index[i]:_TThostFtdcTradingTypeType_index[i+1]]
}
