// Code generated by "stringer -type TThostFtdcPasswordTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PWDT_Trade-49]
	_ = x[THOST_FTDC_PWDT_Account-50]
}

const _TThostFtdcPasswordTypeType_name = "交易密码资金密码"

var _TThostFtdcPasswordTypeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcPasswordTypeType) String() string {
	i -= 49
	if i >= TThostFtdcPasswordTypeType(len(_TThostFtdcPasswordTypeType_index)-1) {
		return "TThostFtdcPasswordTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcPasswordTypeType_name[_TThostFtdcPasswordTypeType_index[i]:_TThostFtdcPasswordTypeType_index[i+1]]
}
