// Code generated by "stringer -type TThostFtdcAuthTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AU_WHITE-48]
	_ = x[THOST_FTDC_AU_BLACK-49]
}

const _TThostFtdcAuthTypeType_name = "白名单校验黑名单校验"

var _TThostFtdcAuthTypeType_index = [...]uint8{0, 15, 30}

func (i TThostFtdcAuthTypeType) String() string {
	i -= 48
	if i >= TThostFtdcAuthTypeType(len(_TThostFtdcAuthTypeType_index)-1) {
		return "TThostFtdcAuthTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcAuthTypeType_name[_TThostFtdcAuthTypeType_index[i]:_TThostFtdcAuthTypeType_index[i+1]]
}
