// Code generated by "stringer -type TThostFtdcOffsetFlagEnType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OFEN_Open-48]
	_ = x[THOST_FTDC_OFEN_Close-49]
	_ = x[THOST_FTDC_OFEN_ForceClose-50]
	_ = x[THOST_FTDC_OFEN_CloseToday-51]
	_ = x[THOST_FTDC_OFEN_CloseYesterday-52]
	_ = x[THOST_FTDC_OFEN_ForceOff-53]
	_ = x[THOST_FTDC_OFEN_LocalForceClose-54]
}

const _TThostFtdcOffsetFlagEnType_name = "Position OpeningPosition CloseForced LiquidationClose TodayClose Prev.Forced ReductionLocal Forced Liquidation"

var _TThostFtdcOffsetFlagEnType_index = [...]uint8{0, 16, 30, 48, 59, 70, 86, 110}

func (i TThostFtdcOffsetFlagEnType) String() string {
	i -= 48
	if i >= TThostFtdcOffsetFlagEnType(len(_TThostFtdcOffsetFlagEnType_index)-1) {
		return "TThostFtdcOffsetFlagEnType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOffsetFlagEnType_name[_TThostFtdcOffsetFlagEnType_index[i]:_TThostFtdcOffsetFlagEnType_index[i+1]]
}
