// Code generated by "stringer -type TThostFtdcFileIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FI_SettlementFund-70]
	_ = x[THOST_FTDC_FI_Trade-84]
	_ = x[THOST_FTDC_FI_InvestorPosition-80]
	_ = x[THOST_FTDC_FI_SubEntryFund-79]
	_ = x[THOST_FTDC_FI_CZCECombinationPos-67]
	_ = x[THOST_FTDC_FI_CSRCData-82]
	_ = x[THOST_FTDC_FI_CZCEClose-76]
	_ = x[THOST_FTDC_FI_CZCENoClose-78]
	_ = x[THOST_FTDC_FI_PositionDtl-68]
	_ = x[THOST_FTDC_FI_OptionStrike-83]
	_ = x[THOST_FTDC_FI_SettlementPriceComparison-77]
	_ = x[THOST_FTDC_FI_NonTradePosChange-66]
}

const (
	_TThostFtdcFileIDType_name_0 = "上期所非持仓变动明细组合持仓数据持仓明细数据"
	_TThostFtdcFileIDType_name_1 = "资金数据"
	_TThostFtdcFileIDType_name_2 = "郑商所平仓了结数据结算价比对文件郑商所非平仓了结数据投资者分项资金数据投资者持仓数据"
	_TThostFtdcFileIDType_name_3 = "上报保证金监控中心数据期权执行文件成交数据"
)

var (
	_TThostFtdcFileIDType_index_0 = [...]uint8{0, 30, 48, 66}
	_TThostFtdcFileIDType_index_2 = [...]uint8{0, 27, 48, 78, 105, 126}
	_TThostFtdcFileIDType_index_3 = [...]uint8{0, 33, 51, 63}
)

func (i TThostFtdcFileIDType) String() string {
	switch {
	case 66 <= i && i <= 68:
		i -= 66
		return _TThostFtdcFileIDType_name_0[_TThostFtdcFileIDType_index_0[i]:_TThostFtdcFileIDType_index_0[i+1]]
	case i == 70:
		return _TThostFtdcFileIDType_name_1
	case 76 <= i && i <= 80:
		i -= 76
		return _TThostFtdcFileIDType_name_2[_TThostFtdcFileIDType_index_2[i]:_TThostFtdcFileIDType_index_2[i+1]]
	case 82 <= i && i <= 84:
		i -= 82
		return _TThostFtdcFileIDType_name_3[_TThostFtdcFileIDType_index_3[i]:_TThostFtdcFileIDType_index_3[i+1]]
	default:
		return "TThostFtdcFileIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
