// Code generated by "stringer -type TThostFtdcMaxMarginSideAlgorithmType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MMSA_NO-48]
	_ = x[THOST_FTDC_MMSA_YES-49]
}

const _TThostFtdcMaxMarginSideAlgorithmType_name = "不使用大额单边保证金算法使用大额单边保证金算法"

var _TThostFtdcMaxMarginSideAlgorithmType_index = [...]uint8{0, 36, 69}

func (i TThostFtdcMaxMarginSideAlgorithmType) String() string {
	i -= 48
	if i >= TThostFtdcMaxMarginSideAlgorithmType(len(_TThostFtdcMaxMarginSideAlgorithmType_index)-1) {
		return "TThostFtdcMaxMarginSideAlgorithmType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcMaxMarginSideAlgorithmType_name[_TThostFtdcMaxMarginSideAlgorithmType_index[i]:_TThostFtdcMaxMarginSideAlgorithmType_index[i+1]]
}
