// Code generated by "stringer -type TThostFtdcBizTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BZTP_Future-49]
	_ = x[THOST_FTDC_BZTP_Stock-50]
}

const _TThostFtdcBizTypeType_name = "期货证券"

var _TThostFtdcBizTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcBizTypeType) String() string {
	i -= 49
	if i >= TThostFtdcBizTypeType(len(_TThostFtdcBizTypeType_index)-1) {
		return "TThostFtdcBizTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcBizTypeType_name[_TThostFtdcBizTypeType_index[i]:_TThostFtdcBizTypeType_index[i+1]]
}
