// Code generated by "stringer -type TThostFtdcCurrencySwapStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CSS_Entry-49]
	_ = x[THOST_FTDC_CSS_Approve-50]
	_ = x[THOST_FTDC_CSS_Refuse-51]
	_ = x[THOST_FTDC_CSS_Revoke-52]
	_ = x[THOST_FTDC_CSS_Send-53]
	_ = x[THOST_FTDC_CSS_Success-54]
	_ = x[THOST_FTDC_CSS_Failure-55]
}

const _TThostFtdcCurrencySwapStatusType_name = "已录入已审核已拒绝已撤销已发送换汇成功换汇失败"

var _TThostFtdcCurrencySwapStatusType_index = [...]uint8{0, 9, 18, 27, 36, 45, 57, 69}

func (i TThostFtdcCurrencySwapStatusType) String() string {
	i -= 49
	if i >= TThostFtdcCurrencySwapStatusType(len(_TThostFtdcCurrencySwapStatusType_index)-1) {
		return "TThostFtdcCurrencySwapStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcCurrencySwapStatusType_name[_TThostFtdcCurrencySwapStatusType_index[i]:_TThostFtdcCurrencySwapStatusType_index[i+1]]
}
