// Code generated by "stringer -type TThostFtdcPwdFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BPWDF_NoCheck-48]
	_ = x[THOST_FTDC_BPWDF_BlankCheck-49]
	_ = x[THOST_FTDC_BPWDF_EncryptCheck-50]
}

const _TThostFtdcPwdFlagType_name = "不核对明文核对密文核对"

var _TThostFtdcPwdFlagType_index = [...]uint8{0, 9, 21, 33}

func (i TThostFtdcPwdFlagType) String() string {
	i -= 48
	if i >= TThostFtdcPwdFlagType(len(_TThostFtdcPwdFlagType_index)-1) {
		return "TThostFtdcPwdFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcPwdFlagType_name[_TThostFtdcPwdFlagType_index[i]:_TThostFtdcPwdFlagType_index[i+1]]
}
