// Code generated by "stringer -type TThostFtdcUserRightTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_URT_Logon-49]
	_ = x[THOST_FTDC_URT_Transfer-50]
	_ = x[THOST_FTDC_URT_EMail-51]
	_ = x[THOST_FTDC_URT_Fax-52]
	_ = x[THOST_FTDC_URT_ConditionOrder-53]
}

const _TThostFtdcUserRightTypeType_name = "登录银期转帐邮寄结算单传真结算单条件单"

var _TThostFtdcUserRightTypeType_index = [...]uint8{0, 6, 18, 33, 48, 57}

func (i TThostFtdcUserRightTypeType) String() string {
	i -= 49
	if i >= TThostFtdcUserRightTypeType(len(_TThostFtdcUserRightTypeType_index)-1) {
		return "TThostFtdcUserRightTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcUserRightTypeType_name[_TThostFtdcUserRightTypeType_index[i]:_TThostFtdcUserRightTypeType_index[i+1]]
}
