// Code generated by "stringer -type TThostFtdcRiskLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FAS_Low-49]
	_ = x[THOST_FTDC_FAS_Normal-50]
	_ = x[THOST_FTDC_FAS_Focus-51]
	_ = x[THOST_FTDC_FAS_Risk-52]
}

const _TThostFtdcRiskLevelType_name = "低风险客户普通客户关注客户风险客户"

var _TThostFtdcRiskLevelType_index = [...]uint8{0, 15, 27, 39, 51}

func (i TThostFtdcRiskLevelType) String() string {
	i -= 49
	if i >= TThostFtdcRiskLevelType(len(_TThostFtdcRiskLevelType_index)-1) {
		return "TThostFtdcRiskLevelType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcRiskLevelType_name[_TThostFtdcRiskLevelType_index[i]:_TThostFtdcRiskLevelType_index[i+1]]
}
