// Code generated by "stringer -type TThostFtdcSettlementStyleType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SBS_Day-49]
	_ = x[THOST_FTDC_SBS_Volume-50]
}

const _TThostFtdcSettlementStyleType_name = "逐日盯市逐笔对冲"

var _TThostFtdcSettlementStyleType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcSettlementStyleType) String() string {
	i -= 49
	if i >= TThostFtdcSettlementStyleType(len(_TThostFtdcSettlementStyleType_index)-1) {
		return "TThostFtdcSettlementStyleType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSettlementStyleType_name[_TThostFtdcSettlementStyleType_index[i]:_TThostFtdcSettlementStyleType_index[i+1]]
}
