// Code generated by "stringer -type TThostFtdcUpdateFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UF_NoUpdate-48]
	_ = x[THOST_FTDC_UF_Success-49]
	_ = x[THOST_FTDC_UF_Fail-50]
	_ = x[THOST_FTDC_UF_TCSuccess-51]
	_ = x[THOST_FTDC_UF_TCFail-52]
	_ = x[THOST_FTDC_UF_Cancel-53]
}

const _TThostFtdcUpdateFlagType_name = "未更新更新全部信息成功更新全部信息失败更新交易编码成功更新交易编码失败已丢弃"

var _TThostFtdcUpdateFlagType_index = [...]uint8{0, 9, 33, 57, 81, 105, 114}

func (i TThostFtdcUpdateFlagType) String() string {
	i -= 48
	if i >= TThostFtdcUpdateFlagType(len(_TThostFtdcUpdateFlagType_index)-1) {
		return "TThostFtdcUpdateFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcUpdateFlagType_name[_TThostFtdcUpdateFlagType_index[i]:_TThostFtdcUpdateFlagType_index[i+1]]
}
