// Code generated by "stringer -type TThostFtdcFutureTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FUTT_Commodity-49]
	_ = x[THOST_FTDC_FUTT_Financial-50]
}

const _TThostFtdcFutureTypeType_name = "商品期货金融期货"

var _TThostFtdcFutureTypeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcFutureTypeType) String() string {
	i -= 49
	if i >= TThostFtdcFutureTypeType(len(_TThostFtdcFutureTypeType_index)-1) {
		return "TThostFtdcFutureTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFutureTypeType_name[_TThostFtdcFutureTypeType_index[i]:_TThostFtdcFutureTypeType_index[i+1]]
}
