// Code generated by "stringer -type TThostFtdcSyncModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SRM_ASync-48]
	_ = x[THOST_FTDC_SRM_Sync-49]
}

const _TThostFtdcSyncModeType_name = "异步同步"

var _TThostFtdcSyncModeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcSyncModeType) String() string {
	i -= 48
	if i >= TThostFtdcSyncModeType(len(_TThostFtdcSyncModeType_index)-1) {
		return "TThostFtdcSyncModeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSyncModeType_name[_TThostFtdcSyncModeType_index[i]:_TThostFtdcSyncModeType_index[i+1]]
}
