// Code generated by "stringer -type TThostFtdcHedgeFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_HF_Speculation-49]
	_ = x[THOST_FTDC_HF_Arbitrage-50]
	_ = x[THOST_FTDC_HF_Hedge-51]
	_ = x[THOST_FTDC_HF_MarketMaker-53]
	_ = x[THOST_FTDC_HF_SpecHedge-54]
	_ = x[THOST_FTDC_HF_HedgeSpec-55]
}

const (
	_TThostFtdcHedgeFlagType_name_0 = "投机套利套保"
	_TThostFtdcHedgeFlagType_name_1 = "做市商第一腿投机第二腿套保第一腿套保第二腿投机"
)

var (
	_TThostFtdcHedgeFlagType_index_0 = [...]uint8{0, 6, 12, 18}
	_TThostFtdcHedgeFlagType_index_1 = [...]uint8{0, 9, 39, 69}
)

func (i TThostFtdcHedgeFlagType) String() string {
	switch {
	case 49 <= i && i <= 51:
		i -= 49
		return _TThostFtdcHedgeFlagType_name_0[_TThostFtdcHedgeFlagType_index_0[i]:_TThostFtdcHedgeFlagType_index_0[i+1]]
	case 53 <= i && i <= 55:
		i -= 53
		return _TThostFtdcHedgeFlagType_name_1[_TThostFtdcHedgeFlagType_index_1[i]:_TThostFtdcHedgeFlagType_index_1[i+1]]
	default:
		return "TThostFtdcHedgeFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
