// Code generated by "stringer -type TThostFtdcTransferValidFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TVF_Invalid-48]
	_ = x[THOST_FTDC_TVF_Valid-49]
	_ = x[THOST_FTDC_TVF_Reverse-50]
}

const _TThostFtdcTransferValidFlagType_name = "无效或失败有效冲正"

var _TThostFtdcTransferValidFlagType_index = [...]uint8{0, 15, 21, 27}

func (i TThostFtdcTransferValidFlagType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcTransferValidFlagType_index)-1 {
		return "TThostFtdcTransferValidFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcTransferValidFlagType_name[_TThostFtdcTransferValidFlagType_index[idx]:_TThostFtdcTransferValidFlagType_index[idx+1]]
}
