// Code generated by "stringer -type TThostFtdcPassWordKeyTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PWKT_ExchangeKey-48]
	_ = x[THOST_FTDC_PWKT_PassWordKey-49]
	_ = x[THOST_FTDC_PWKT_MACKey-50]
	_ = x[THOST_FTDC_PWKT_MessageKey-51]
}

const _TThostFtdcPassWordKeyTypeType_name = "交换密钥密码密钥MAC密钥报文密钥"

var _TThostFtdcPassWordKeyTypeType_index = [...]uint8{0, 12, 24, 33, 45}

func (i TThostFtdcPassWordKeyTypeType) String() string {
	i -= 48
	if i >= TThostFtdcPassWordKeyTypeType(len(_TThostFtdcPassWordKeyTypeType_index)-1) {
		return "TThostFtdcPassWordKeyTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcPassWordKeyTypeType_name[_TThostFtdcPassWordKeyTypeType_index[i]:_TThostFtdcPassWordKeyTypeType_index[i+1]]
}
