// Code generated by "stringer -type TThostFtdcNotifyClassType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_NC_NOERROR-48]
	_ = x[THOST_FTDC_NC_Warn-49]
	_ = x[THOST_FTDC_NC_Call-50]
	_ = x[THOST_FTDC_NC_Force-51]
	_ = x[THOST_FTDC_NC_CHUANCANG-52]
	_ = x[THOST_FTDC_NC_Exception-53]
}

const _TThostFtdcNotifyClassType_name = "正常警示追保强平穿仓异常"

var _TThostFtdcNotifyClassType_index = [...]uint8{0, 6, 12, 18, 24, 30, 36}

func (i TThostFtdcNotifyClassType) String() string {
	i -= 48
	if i >= TThostFtdcNotifyClassType(len(_TThostFtdcNotifyClassType_index)-1) {
		return "TThostFtdcNotifyClassType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcNotifyClassType_name[_TThostFtdcNotifyClassType_index[i]:_TThostFtdcNotifyClassType_index[i+1]]
}
