// Code generated by "stringer -type TThostFtdcTimeConditionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TC_IOC-49]
	_ = x[THOST_FTDC_TC_GFS-50]
	_ = x[THOST_FTDC_TC_GFD-51]
	_ = x[THOST_FTDC_TC_GTD-52]
	_ = x[THOST_FTDC_TC_GTC-53]
	_ = x[THOST_FTDC_TC_GFA-54]
}

const _TThostFtdcTimeConditionType_name = "立即完成，否则撤销本节有效当日有效指定日期前有效撤销前有效集合竞价有效"

var _TThostFtdcTimeConditionType_index = [...]uint8{0, 27, 39, 51, 72, 87, 105}

func (i TThostFtdcTimeConditionType) String() string {
	i -= 49
	if i >= TThostFtdcTimeConditionType(len(_TThostFtdcTimeConditionType_index)-1) {
		return "TThostFtdcTimeConditionType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcTimeConditionType_name[_TThostFtdcTimeConditionType_index[i]:_TThostFtdcTimeConditionType_index[i+1]]
}
