// Code generated by "stringer -type TThostFtdcMarginTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MGT_ExchMarginRate-48]
	_ = x[THOST_FTDC_MGT_InstrMarginRate-49]
	_ = x[THOST_FTDC_MGT_InstrMarginRateTrade-50]
}

const _TThostFtdcMarginTypeType_name = "交易所保证金率投资者保证金率投资者交易保证金率"

var _TThostFtdcMarginTypeType_index = [...]uint8{0, 21, 42, 69}

func (i TThostFtdcMarginTypeType) String() string {
	i -= 48
	if i >= TThostFtdcMarginTypeType(len(_TThostFtdcMarginTypeType_index)-1) {
		return "TThostFtdcMarginTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcMarginTypeType_name[_TThostFtdcMarginTypeType_index[i]:_TThostFtdcMarginTypeType_index[i+1]]
}
