// Code generated by "stringer -type TThostFtdcInstrumentClassType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EIC_Usual-49]
	_ = x[THOST_FTDC_EIC_Delivery-50]
	_ = x[THOST_FTDC_EIC_NonComb-51]
}

const _TThostFtdcInstrumentClassType_name = "一般月份合约临近交割合约非组合合约"

var _TThostFtdcInstrumentClassType_index = [...]uint8{0, 18, 36, 51}

func (i TThostFtdcInstrumentClassType) String() string {
	i -= 49
	if i >= TThostFtdcInstrumentClassType(len(_TThostFtdcInstrumentClassType_index)-1) {
		return "TThostFtdcInstrumentClassType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcInstrumentClassType_name[_TThostFtdcInstrumentClassType_index[i]:_TThostFtdcInstrumentClassType_index[i+1]]
}
