// Code generated by "stringer -type TThostFtdcLanguageTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_LT_Chinese-49]
	_ = x[THOST_FTDC_LT_English-50]
}

const _TThostFtdcLanguageTypeType_name = "中文英文"

var _TThostFtdcLanguageTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcLanguageTypeType) String() string {
	i -= 49
	if i >= TThostFtdcLanguageTypeType(len(_TThostFtdcLanguageTypeType_index)-1) {
		return "TThostFtdcLanguageTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcLanguageTypeType_name[_TThostFtdcLanguageTypeType_index[i]:_TThostFtdcLanguageTypeType_index[i+1]]
}
