// Code generated by "stringer -type TThostFtdcFundTypeEnType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FTEN_Deposite-49]
	_ = x[THOST_FTDC_FTEN_ItemFund-50]
	_ = x[THOST_FTDC_FTEN_Company-51]
	_ = x[THOST_FTDC_FTEN_InnerTransfer-52]
}

const _TThostFtdcFundTypeEnType_name = "Bank DepositPaymentFeeBrokerage AdjInternal Transfer"

var _TThostFtdcFundTypeEnType_index = [...]uint8{0, 12, 22, 35, 52}

func (i TThostFtdcFundTypeEnType) String() string {
	i -= 49
	if i >= TThostFtdcFundTypeEnType(len(_TThostFtdcFundTypeEnType_index)-1) {
		return "TThostFtdcFundTypeEnType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundTypeEnType_name[_TThostFtdcFundTypeEnType_index[i]:_TThostFtdcFundTypeEnType_index[i+1]]
}
