// Code generated by "stringer -type TThostFtdcSaveStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SSS_UnSaveData-48]
	_ = x[THOST_FTDC_SSS_SaveDatad-49]
}

const _TThostFtdcSaveStatusType_name = "归档未完成归档完成"

var _TThostFtdcSaveStatusType_index = [...]uint8{0, 15, 27}

func (i TThostFtdcSaveStatusType) String() string {
	i -= 48
	if i >= TThostFtdcSaveStatusType(len(_TThostFtdcSaveStatusType_index)-1) {
		return "TThostFtdcSaveStatusType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSaveStatusType_name[_TThostFtdcSaveStatusType_index[i]:_TThostFtdcSaveStatusType_index[i+1]]
}
