// Code generated by "stringer -type TThostFtdcMatchTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OTC_MT_DV01-49]
	_ = x[THOST_FTDC_OTC_MT_ParValue-50]
}

const _TThostFtdcMatchTypeType_name = "基点价值面值"

var _TThostFtdcMatchTypeType_index = [...]uint8{0, 12, 18}

func (i TThostFtdcMatchTypeType) String() string {
	i -= 49
	if i >= TThostFtdcMatchTypeType(len(_TThostFtdcMatchTypeType_index)-1) {
		return "TThostFtdcMatchTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcMatchTypeType_name[_TThostFtdcMatchTypeType_index[i]:_TThostFtdcMatchTypeType_index[i+1]]
}
