// Code generated by "stringer -type TThostFtdcBrokerTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BT_Trade-48]
	_ = x[THOST_FTDC_BT_TradeSettle-49]
}

const _TThostFtdcBrokerTypeType_name = "交易会员交易结算会员"

var _TThostFtdcBrokerTypeType_index = [...]uint8{0, 12, 30}

func (i TThostFtdcBrokerTypeType) String() string {
	i -= 48
	if i >= TThostFtdcBrokerTypeType(len(_TThostFtdcBrokerTypeType_index)-1) {
		return "TThostFtdcBrokerTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcBrokerTypeType_name[_TThostFtdcBrokerTypeType_index[i]:_TThostFtdcBrokerTypeType_index[i+1]]
}
