// Code generated by "stringer -type TThostFtdcDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_D_Buy-48]
	_ = x[THOST_FTDC_D_Sell-49]
}

const _TThostFtdcDirectionType_name = "买卖"

var _TThostFtdcDirectionType_index = [...]uint8{0, 3, 6}

func (i TThostFtdcDirectionType) String() string {
	i -= 48
	if i >= TThostFtdcDirectionType(len(_TThostFtdcDirectionType_index)-1) {
		return "TThostFtdcDirectionType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcDirectionType_name[_TThostFtdcDirectionType_index[i]:_TThostFtdcDirectionType_index[i+1]]
}
