// Code generated by "stringer -type TThostFtdcInstMarginCalIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IMID_BothSide-49]
	_ = x[THOST_FTDC_IMID_MMSA-50]
	_ = x[THOST_FTDC_IMID_SPMM-51]
}

const _TThostFtdcInstMarginCalIDType_name = "标准算法收取双边单向大边新组保SPMM"

var _TThostFtdcInstMarginCalIDType_index = [...]uint8{0, 24, 36, 49}

func (i TThostFtdcInstMarginCalIDType) String() string {
	i -= 49
	if i >= TThostFtdcInstMarginCalIDType(len(_TThostFtdcInstMarginCalIDType_index)-1) {
		return "TThostFtdcInstMarginCalIDType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcInstMarginCalIDType_name[_TThostFtdcInstMarginCalIDType_index[i]:_TThostFtdcInstMarginCalIDType_index[i+1]]
}
