// Code generated by "stringer -type TThostFtdcSyncTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SYNT_OneOffSync-48]
	_ = x[THOST_FTDC_SYNT_TimerSync-49]
	_ = x[THOST_FTDC_SYNT_TimerFullSync-50]
}

const _TThostFtdcSyncTypeType_name = "一次同步定时同步定时完全同步"

var _TThostFtdcSyncTypeType_index = [...]uint8{0, 12, 24, 42}

func (i TThostFtdcSyncTypeType) String() string {
	i -= 48
	if i >= TThostFtdcSyncTypeType(len(_TThostFtdcSyncTypeType_index)-1) {
		return "TThostFtdcSyncTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcSyncTypeType_name[_TThostFtdcSyncTypeType_index[i]:_TThostFtdcSyncTypeType_index[i+1]]
}
