// Code generated by "stringer -type TThostFtdcOffsetFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OF_Open-48]
	_ = x[THOST_FTDC_OF_Close-49]
	_ = x[THOST_FTDC_OF_ForceClose-50]
	_ = x[THOST_FTDC_OF_CloseToday-51]
	_ = x[THOST_FTDC_OF_CloseYesterday-52]
	_ = x[THOST_FTDC_OF_ForceOff-53]
	_ = x[THOST_FTDC_OF_LocalForceClose-54]
}

const _TThostFtdcOffsetFlagType_name = "开仓平仓强平平今平昨强减本地强平"

var _TThostFtdcOffsetFlagType_index = [...]uint8{0, 6, 12, 18, 24, 30, 36, 48}

func (i TThostFtdcOffsetFlagType) String() string {
	i -= 48
	if i >= TThostFtdcOffsetFlagType(len(_TThostFtdcOffsetFlagType_index)-1) {
		return "TThostFtdcOffsetFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcOffsetFlagType_name[_TThostFtdcOffsetFlagType_index[i]:_TThostFtdcOffsetFlagType_index[i+1]]
}
