// Code generated by "stringer -type TThostFtdcRiskNotifyMethodType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RNM_System-48]
	_ = x[THOST_FTDC_RNM_SMS-49]
	_ = x[THOST_FTDC_RNM_EMail-50]
	_ = x[THOST_FTDC_RNM_Manual-51]
}

const _TThostFtdcRiskNotifyMethodType_name = "系统通知短信通知邮件通知人工通知"

var _TThostFtdcRiskNotifyMethodType_index = [...]uint8{0, 12, 24, 36, 48}

func (i TThostFtdcRiskNotifyMethodType) String() string {
	i -= 48
	if i >= TThostFtdcRiskNotifyMethodType(len(_TThostFtdcRiskNotifyMethodType_index)-1) {
		return "TThostFtdcRiskNotifyMethodType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcRiskNotifyMethodType_name[_TThostFtdcRiskNotifyMethodType_index[i]:_TThostFtdcRiskNotifyMethodType_index[i+1]]
}
