// Code generated by "stringer -type TThostFtdcReturnPatternType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RP_ByVolume-49]
	_ = x[THOST_FTDC_RP_ByFeeOnHand-50]
}

const _TThostFtdcReturnPatternType_name = "按成交手数按留存手续费"

var _TThostFtdcReturnPatternType_index = [...]uint8{0, 15, 33}

func (i TThostFtdcReturnPatternType) String() string {
	i -= 49
	if i >= TThostFtdcReturnPatternType(len(_TThostFtdcReturnPatternType_index)-1) {
		return "TThostFtdcReturnPatternType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcReturnPatternType_name[_TThostFtdcReturnPatternType_index[i]:_TThostFtdcReturnPatternType_index[i+1]]
}
