// Code generated by "stringer -type TThostFtdcSystemParamIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SPI_InvestorIDMinLength-49]
	_ = x[THOST_FTDC_SPI_AccountIDMinLength-50]
	_ = x[THOST_FTDC_SPI_UserRightLogon-51]
	_ = x[THOST_FTDC_SPI_SettlementBillTrade-52]
	_ = x[THOST_FTDC_SPI_TradingCode-53]
	_ = x[THOST_FTDC_SPI_CheckFund-54]
	_ = x[THOST_FTDC_SPI_CommModelRight-55]
	_ = x[THOST_FTDC_SPI_MarginModelRight-57]
	_ = x[THOST_FTDC_SPI_IsStandardActive-56]
	_ = x[THOST_FTDC_SPI_UploadSettlementFile-85]
	_ = x[THOST_FTDC_SPI_DownloadCSRCFile-68]
	_ = x[THOST_FTDC_SPI_SettlementBillFile-83]
	_ = x[THOST_FTDC_SPI_CSRCOthersFile-67]
	_ = x[THOST_FTDC_SPI_InvestorPhoto-80]
	_ = x[THOST_FTDC_SPI_CSRCData-82]
	_ = x[THOST_FTDC_SPI_InvestorPwdModel-73]
	_ = x[THOST_FTDC_SPI_CFFEXInvestorSettleFile-70]
	_ = x[THOST_FTDC_SPI_InvestorIDType-97]
	_ = x[THOST_FTDC_SPI_FreezeMaxReMain-114]
	_ = x[THOST_FTDC_SPI_IsSync-65]
	_ = x[THOST_FTDC_SPI_RelieveOpenLimit-79]
	_ = x[THOST_FTDC_SPI_IsStandardFreeze-88]
	_ = x[THOST_FTDC_SPI_CZCENormalProductHedge-66]
}

const (
	_TThostFtdcSystemParamIDType_name_0 = "投资者代码最小长度投资者帐号代码最小长度投资者开户默认登录权限投资者交易结算单成交汇总方式统一开户更新交易编码方式结算是否判断存在未复核的出入金和分项资金是否启用手续费模板数据权限是否规范用户才能激活是否启用保证金率模板数据权限"
	_TThostFtdcSystemParamIDType_name_1 = "手续费相关操作实时上场开关郑商所是否开放所有品种套保交易证监会文件标识上报保证金监控中心文件路径"
	_TThostFtdcSystemParamIDType_name_2 = "投资者中金所结算文件下载路径"
	_TThostFtdcSystemParamIDType_name_3 = "开户密码录入方式"
	_TThostFtdcSystemParamIDType_name_4 = "解除开仓权限限制投资者照片路径"
	_TThostFtdcSystemParamIDType_name_5 = "全结经纪公司上传文件路径生成的结算单文件路径"
	_TThostFtdcSystemParamIDType_name_6 = "上传的交易所结算文件路径"
	_TThostFtdcSystemParamIDType_name_7 = "是否规范用户才能休眠"
	_TThostFtdcSystemParamIDType_name_8 = "投资者代码编码方式"
	_TThostFtdcSystemParamIDType_name_9 = "休眠户最高权益"
)

var (
	_TThostFtdcSystemParamIDType_index_0 = [...]uint16{0, 27, 60, 93, 135, 171, 231, 270, 300, 342}
	_TThostFtdcSystemParamIDType_index_1 = [...]uint8{0, 39, 84, 105, 144}
	_TThostFtdcSystemParamIDType_index_4 = [...]uint8{0, 24, 45}
	_TThostFtdcSystemParamIDType_index_5 = [...]uint8{0, 36, 66}
)

func (i TThostFtdcSystemParamIDType) String() string {
	switch {
	case 49 <= i && i <= 57:
		i -= 49
		return _TThostFtdcSystemParamIDType_name_0[_TThostFtdcSystemParamIDType_index_0[i]:_TThostFtdcSystemParamIDType_index_0[i+1]]
	case 65 <= i && i <= 68:
		i -= 65
		return _TThostFtdcSystemParamIDType_name_1[_TThostFtdcSystemParamIDType_index_1[i]:_TThostFtdcSystemParamIDType_index_1[i+1]]
	case i == 70:
		return _TThostFtdcSystemParamIDType_name_2
	case i == 73:
		return _TThostFtdcSystemParamIDType_name_3
	case 79 <= i && i <= 80:
		i -= 79
		return _TThostFtdcSystemParamIDType_name_4[_TThostFtdcSystemParamIDType_index_4[i]:_TThostFtdcSystemParamIDType_index_4[i+1]]
	case 82 <= i && i <= 83:
		i -= 82
		return _TThostFtdcSystemParamIDType_name_5[_TThostFtdcSystemParamIDType_index_5[i]:_TThostFtdcSystemParamIDType_index_5[i+1]]
	case i == 85:
		return _TThostFtdcSystemParamIDType_name_6
	case i == 88:
		return _TThostFtdcSystemParamIDType_name_7
	case i == 97:
		return _TThostFtdcSystemParamIDType_name_8
	case i == 114:
		return _TThostFtdcSystemParamIDType_name_9
	default:
		return "TThostFtdcSystemParamIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
