// Code generated by "stringer -type TThostFtdcSecuAccTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SAT_AccountID-49]
	_ = x[THOST_FTDC_SAT_CardID-50]
	_ = x[THOST_FTDC_SAT_SHStockholderID-51]
	_ = x[THOST_FTDC_SAT_SZStockholderID-52]
}

const _TThostFtdcSecuAccTypeType_name = "资金帐号资金卡号上海股东帐号深圳股东帐号"

var _TThostFtdcSecuAccTypeType_index = [...]uint8{0, 12, 24, 42, 60}

func (i TThostFtdcSecuAccTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcSecuAccTypeType_index)-1 {
		return "TThostFtdcSecuAccTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcSecuAccTypeType_name[_TThostFtdcSecuAccTypeType_index[idx]:_TThostFtdcSecuAccTypeType_index[idx+1]]
}
