// Code generated by "stringer -type TThostFtdcBanlanceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BLT_CurrentMoney-48]
	_ = x[THOST_FTDC_BLT_UsableMoney-49]
	_ = x[THOST_FTDC_BLT_FetchableMoney-50]
	_ = x[THOST_FTDC_BLT_FreezeMoney-51]
}

const _TThostFtdcBanlanceTypeType_name = "当前余额可用余额可取余额冻结余额"

var _TThostFtdcBanlanceTypeType_index = [...]uint8{0, 12, 24, 36, 48}

func (i TThostFtdcBanlanceTypeType) String() string {
	i -= 48
	if i >= TThostFtdcBanlanceTypeType(len(_TThostFtdcBanlanceTypeType_index)-1) {
		return "TThostFtdcBanlanceTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcBanlanceTypeType_name[_TThostFtdcBanlanceTypeType_index[i]:_TThostFtdcBanlanceTypeType_index[i+1]]
}
