// Code generated by "stringer -type TThostFtdcReturnLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RL_Level1-49]
	_ = x[THOST_FTDC_RL_Level2-50]
	_ = x[THOST_FTDC_RL_Level3-51]
	_ = x[THOST_FTDC_RL_Level4-52]
	_ = x[THOST_FTDC_RL_Level5-53]
	_ = x[THOST_FTDC_RL_Level6-54]
	_ = x[THOST_FTDC_RL_Level7-55]
	_ = x[THOST_FTDC_RL_Level8-56]
	_ = x[THOST_FTDC_RL_Level9-57]
}

const _TThostFtdcReturnLevelType_name = "级别1级别2级别3级别4级别5级别6级别7级别8级别9"

var _TThostFtdcReturnLevelType_index = [...]uint8{0, 7, 14, 21, 28, 35, 42, 49, 56, 63}

func (i TThostFtdcReturnLevelType) String() string {
	i -= 49
	if i >= TThostFtdcReturnLevelType(len(_TThostFtdcReturnLevelType_index)-1) {
		return "TThostFtdcReturnLevelType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcReturnLevelType_name[_TThostFtdcReturnLevelType_index[i]:_TThostFtdcReturnLevelType_index[i+1]]
}
