// Code generated by "stringer -type TThostFtdcSysSettlementStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SS_NonActive-49]
	_ = x[THOST_FTDC_SS_Startup-50]
	_ = x[THOST_FTDC_SS_Operating-51]
	_ = x[THOST_FTDC_SS_Settlement-52]
	_ = x[THOST_FTDC_SS_SettlementFinished-53]
}

const _TThostFtdcSysSettlementStatusType_name = "不活跃启动操作结算结算完成"

var _TThostFtdcSysSettlementStatusType_index = [...]uint8{0, 9, 15, 21, 27, 39}

func (i TThostFtdcSysSettlementStatusType) String() string {
	i -= 49
	if i >= TThostFtdcSysSettlementStatusType(len(_TThostFtdcSysSettlementStatusType_index)-1) {
		return "TThostFtdcSysSettlementStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcSysSettlementStatusType_name[_TThostFtdcSysSettlementStatusType_index[i]:_TThostFtdcSysSettlementStatusType_index[i+1]]
}
