// Code generated by "stringer -type TThostFtdcApplyTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_APPT_NotStrikeNum-52]
}

const _TThostFtdcApplyTypeType_name = "不执行数量"

var _TThostFtdcApplyTypeType_index = [...]uint8{0, 15}

func (i TThostFtdcApplyTypeType) String() string {
	i -= 52
	if i >= TThostFtdcApplyTypeType(len(_TThostFtdcApplyTypeType_index)-1) {
		return "TThostFtdcApplyTypeType(" + strconv.FormatInt(int64(i+52), 10) + ")"
	}
	return _TThostFtdcApplyTypeType_name[_TThostFtdcApplyTypeType_index[i]:_TThostFtdcApplyTypeType_index[i+1]]
}
