// Code generated by "stringer -type TThostFtdcBankAcountOriginType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BAO_ByAccProperty-48]
	_ = x[THOST_FTDC_BAO_ByFBTransfer-49]
}

const _TThostFtdcBankAcountOriginType_name = "手工录入银期转账"

var _TThostFtdcBankAcountOriginType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcBankAcountOriginType) String() string {
	i -= 48
	if i >= TThostFtdcBankAcountOriginType(len(_TThostFtdcBankAcountOriginType_index)-1) {
		return "TThostFtdcBankAcountOriginType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcBankAcountOriginType_name[_TThostFtdcBankAcountOriginType_index[i]:_TThostFtdcBankAcountOriginType_index[i+1]]
}
