// Code generated by "stringer -type TThostFtdcHasTrusteeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_HT_Yes-49]
	_ = x[THOST_FTDC_HT_No-48]
}

const _TThostFtdcHasTrusteeType_name = "没有有"

var _TThostFtdcHasTrusteeType_index = [...]uint8{0, 6, 9}

func (i TThostFtdcHasTrusteeType) String() string {
	i -= 48
	if i >= TThostFtdcHasTrusteeType(len(_TThostFtdcHasTrusteeType_index)-1) {
		return "TThostFtdcHasTrusteeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcHasTrusteeType_name[_TThostFtdcHasTrusteeType_index[i]:_TThostFtdcHasTrusteeType_index[i+1]]
}
