// Code generated by "stringer -type TThostFtdcLastFragmentType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_LF_Yes-48]
	_ = x[THOST_FTDC_LF_No-49]
}

const _TThostFtdcLastFragmentType_name = "是最后分片不是最后分片"

var _TThostFtdcLastFragmentType_index = [...]uint8{0, 15, 33}

func (i TThostFtdcLastFragmentType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcLastFragmentType_index)-1 {
		return "TThostFtdcLastFragmentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcLastFragmentType_name[_TThostFtdcLastFragmentType_index[idx]:_TThostFtdcLastFragmentType_index[idx+1]]
}
