// Code generated by "stringer -type TThostFtdcAPIProductClassType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_APC_FutureSingle-49]
	_ = x[THOST_FTDC_APC_OptionSingle-50]
	_ = x[THOST_FTDC_APC_Futures-51]
	_ = x[THOST_FTDC_APC_Options-52]
	_ = x[THOST_FTDC_APC_TradingComb-53]
	_ = x[THOST_FTDC_APC_UnTradingComb-54]
	_ = x[THOST_FTDC_APC_AllTrading-55]
	_ = x[THOST_FTDC_APC_All-56]
}

const _TThostFtdcAPIProductClassType_name = "期货单一合约期权单一合约可交易期货(含期货组合和期货单一合约)可交易期权(含期权组合和期权单一合约)可下单套利组合可申请的组合（可以申请的组合合约 包含可以交易的合约）所有可以交易合约所有合约（包含不能交易合约 慎用）"

var _TThostFtdcAPIProductClassType_index = [...]uint16{0, 18, 36, 89, 142, 163, 242, 266, 315}

func (i TThostFtdcAPIProductClassType) String() string {
	i -= 49
	if i >= TThostFtdcAPIProductClassType(len(_TThostFtdcAPIProductClassType_index)-1) {
		return "TThostFtdcAPIProductClassType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcAPIProductClassType_name[_TThostFtdcAPIProductClassType_index[i]:_TThostFtdcAPIProductClassType_index[i+1]]
}
