// Code generated by "stringer -type TThostFtdcRightParamTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RPT_Freeze-49]
	_ = x[THOST_FTDC_RPT_FreezeActive-50]
	_ = x[THOST_FTDC_RPT_OpenLimit-51]
	_ = x[THOST_FTDC_RPT_RelieveOpenLimit-52]
}

const _TThostFtdcRightParamTypeType_name = "休眠户激活休眠户开仓权限限制解除开仓权限限制"

var _TThostFtdcRightParamTypeType_index = [...]uint8{0, 9, 24, 42, 66}

func (i TThostFtdcRightParamTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcRightParamTypeType_index)-1 {
		return "TThostFtdcRightParamTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcRightParamTypeType_name[_TThostFtdcRightParamTypeType_index[idx]:_TThostFtdcRightParamTypeType_index[idx+1]]
}
