// Code generated by "stringer -type TThostFtdcFileTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FUT_Settlement-48]
	_ = x[THOST_FTDC_FUT_Check-49]
}

const _TThostFtdcFileTypeType_name = "结算核对"

var _TThostFtdcFileTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcFileTypeType) String() string {
	i -= 48
	if i >= TThostFtdcFileTypeType(len(_TThostFtdcFileTypeType_index)-1) {
		return "TThostFtdcFileTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcFileTypeType_name[_TThostFtdcFileTypeType_index[i]:_TThostFtdcFileTypeType_index[i+1]]
}
