// Code generated by "stringer -type TThostFtdcFundIOTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FIOT_FundIO-49]
	_ = x[THOST_FTDC_FIOT_Transfer-50]
	_ = x[THOST_FTDC_FIOT_SwapCurrency-51]
}

const _TThostFtdcFundIOTypeType_name = "出入金银期转帐银期换汇"

var _TThostFtdcFundIOTypeType_index = [...]uint8{0, 9, 21, 33}

func (i TThostFtdcFundIOTypeType) String() string {
	i -= 49
	if i >= TThostFtdcFundIOTypeType(len(_TThostFtdcFundIOTypeType_index)-1) {
		return "TThostFtdcFundIOTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFundIOTypeType_name[_TThostFtdcFundIOTypeType_index[i]:_TThostFtdcFundIOTypeType_index[i+1]]
}
