// Code generated by "stringer -type TThostFtdcProductTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PTE_Futures-49]
	_ = x[THOST_FTDC_PTE_Options-50]
}

const _TThostFtdcProductTypeType_name = "期货期权"

var _TThostFtdcProductTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcProductTypeType) String() string {
	i -= 49
	if i >= TThostFtdcProductTypeType(len(_TThostFtdcProductTypeType_index)-1) {
		return "TThostFtdcProductTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcProductTypeType_name[_TThostFtdcProductTypeType_index[i]:_TThostFtdcProductTypeType_index[i+1]]
}
