// Code generated by "stringer -type TThostFtdcPriceSourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PSRC_LastPrice-48]
	_ = x[THOST_FTDC_PSRC_Buy-49]
	_ = x[THOST_FTDC_PSRC_Sell-50]
	_ = x[THOST_FTDC_PSRC_OTC-51]
}

const _TThostFtdcPriceSourceType_name = "前成交价买委托价卖委托价场外成交价"

var _TThostFtdcPriceSourceType_index = [...]uint8{0, 12, 24, 36, 51}

func (i TThostFtdcPriceSourceType) String() string {
	i -= 48
	if i >= TThostFtdcPriceSourceType(len(_TThostFtdcPriceSourceType_index)-1) {
		return "TThostFtdcPriceSourceType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcPriceSourceType_name[_TThostFtdcPriceSourceType_index[i]:_TThostFtdcPriceSourceType_index[i+1]]
}
