// Code generated by "stringer -type TThostFtdcApplyTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_APPT_NotStrikeNum-52]
}

const _TThostFtdcApplyTypeType_name = "不执行数量"

var _TThostFtdcApplyTypeType_index = [...]uint8{0, 15}

func (i TThostFtdcApplyTypeType) String() string {
	idx := int(i) - 52
	if i < 52 || idx >= len(_TThostFtdcApplyTypeType_index)-1 {
		return "TThostFtdcApplyTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcApplyTypeType_name[_TThostFtdcApplyTypeType_index[idx]:_TThostFtdcApplyTypeType_index[idx+1]]
}
