// Code generated by "stringer -type TThostFtdcHandlePositionAlgoIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_HPA_Base-49]
	_ = x[THOST_FTDC_HPA_DCE-50]
	_ = x[THOST_FTDC_HPA_CZCE-51]
}

const _TThostFtdcHandlePositionAlgoIDType_name = "基本大连商品交易所郑州商品交易所"

var _TThostFtdcHandlePositionAlgoIDType_index = [...]uint8{0, 6, 27, 48}

func (i TThostFtdcHandlePositionAlgoIDType) String() string {
	i -= 49
	if i >= TThostFtdcHandlePositionAlgoIDType(len(_TThostFtdcHandlePositionAlgoIDType_index)-1) {
		return "TThostFtdcHandlePositionAlgoIDType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcHandlePositionAlgoIDType_name[_TThostFtdcHandlePositionAlgoIDType_index[i]:_TThostFtdcHandlePositionAlgoIDType_index[i+1]]
}
