// Code generated by "stringer -type TThostFtdcForQuoteStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FQST_Submitted-97]
	_ = x[THOST_FTDC_FQST_Accepted-98]
	_ = x[THOST_FTDC_FQST_Rejected-99]
}

const _TThostFtdcForQuoteStatusType_name = "已经提交已经接受已经被拒绝"

var _TThostFtdcForQuoteStatusType_index = [...]uint8{0, 12, 24, 39}

func (i TThostFtdcForQuoteStatusType) String() string {
	i -= 97
	if i >= TThostFtdcForQuoteStatusType(len(_TThostFtdcForQuoteStatusType_index)-1) {
		return "TThostFtdcForQuoteStatusType(" + strconv.FormatInt(int64(i+97), 10) + ")"
	}
	return _TThostFtdcForQuoteStatusType_name[_TThostFtdcForQuoteStatusType_index[i]:_TThostFtdcForQuoteStatusType_index[i+1]]
}
