// Code generated by "stringer -type TThostFtdcFBTTransferDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBTTD_FromBankToFuture-49]
	_ = x[THOST_FTDC_FBTTD_FromFutureToBank-50]
}

const _TThostFtdcFBTTransferDirectionType_name = "入金，银行转期货出金，期货转银行"

var _TThostFtdcFBTTransferDirectionType_index = [...]uint8{0, 24, 48}

func (i TThostFtdcFBTTransferDirectionType) String() string {
	i -= 49
	if i >= TThostFtdcFBTTransferDirectionType(len(_TThostFtdcFBTTransferDirectionType_index)-1) {
		return "TThostFtdcFBTTransferDirectionType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcFBTTransferDirectionType_name[_TThostFtdcFBTTransferDirectionType_index[i]:_TThostFtdcFBTTransferDirectionType_index[i+1]]
}
