// Code generated by "stringer -type TThostFtdcInitSettlementType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SIS_UnInitialize-48]
	_ = x[THOST_FTDC_SIS_Initialize-49]
	_ = x[THOST_FTDC_SIS_Initialized-50]
}

const _TThostFtdcInitSettlementType_name = "结算初始化未开始结算初始化中结算初始化完成"

var _TThostFtdcInitSettlementType_index = [...]uint8{0, 24, 42, 63}

func (i TThostFtdcInitSettlementType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcInitSettlementType_index)-1 {
		return "TThostFtdcInitSettlementType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcInitSettlementType_name[_TThostFtdcInitSettlementType_index[idx]:_TThostFtdcInitSettlementType_index[idx+1]]
}
