// Code generated by "stringer -type TThostFtdcAlgorithmType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AG_All-49]
	_ = x[THOST_FTDC_AG_OnlyLost-50]
	_ = x[THOST_FTDC_AG_OnlyGain-51]
	_ = x[THOST_FTDC_AG_None-52]
}

const _TThostFtdcAlgorithmType_name = "浮盈浮亏都计算浮盈不计，浮亏计浮盈计，浮亏不计浮盈浮亏都不计算"

var _TThostFtdcAlgorithmType_index = [...]uint8{0, 21, 45, 69, 93}

func (i TThostFtdcAlgorithmType) String() string {
	i -= 49
	if i >= TThostFtdcAlgorithmType(len(_TThostFtdcAlgorithmType_index)-1) {
		return "TThostFtdcAlgorithmType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcAlgorithmType_name[_TThostFtdcAlgorithmType_index[i]:_TThostFtdcAlgorithmType_index[i+1]]
}
