// Code generated by "stringer -type TThostFtdcPublishStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PS_None-49]
	_ = x[THOST_FTDC_PS_Publishing-50]
	_ = x[THOST_FTDC_PS_Published-51]
	_ = x[THOST_FTDC_PS_tradeable-49]
	_ = x[THOST_FTDC_PS_untradeable-50]
}

const _TThostFtdcPublishStatusType_name = "未发布正在发布已发布"

var _TThostFtdcPublishStatusType_index = [...]uint8{0, 9, 21, 30}

func (i TThostFtdcPublishStatusType) String() string {
	i -= 49
	if i >= TThostFtdcPublishStatusType(len(_TThostFtdcPublishStatusType_index)-1) {
		return "TThostFtdcPublishStatusType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcPublishStatusType_name[_TThostFtdcPublishStatusType_index[i]:_TThostFtdcPublishStatusType_index[i+1]]
}
