// Code generated by "stringer -type TThostFtdcInvestorRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IR_All-49]
	_ = x[THOST_FTDC_IR_Group-50]
	_ = x[THOST_FTDC_IR_Single-51]
}

const _TThostFtdcInvestorRangeType_name = "所有投资者组单一投资者"

var _TThostFtdcInvestorRangeType_index = [...]uint8{0, 6, 18, 33}

func (i TThostFtdcInvestorRangeType) String() string {
	i -= 49
	if i >= TThostFtdcInvestorRangeType(len(_TThostFtdcInvestorRangeType_index)-1) {
		return "TThostFtdcInvestorRangeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcInvestorRangeType_name[_TThostFtdcInvestorRangeType_index[i]:_TThostFtdcInvestorRangeType_index[i+1]]
}
