// Code generated by "stringer -type TThostFtdcClientRegionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CR_Domestic-49]
	_ = x[THOST_FTDC_CR_GMT-50]
	_ = x[THOST_FTDC_CR_Foreign-51]
}

const _TThostFtdcClientRegionType_name = "国内客户港澳台客户国外客户"

var _TThostFtdcClientRegionType_index = [...]uint8{0, 12, 27, 39}

func (i TThostFtdcClientRegionType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcClientRegionType_index)-1 {
		return "TThostFtdcClientRegionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcClientRegionType_name[_TThostFtdcClientRegionType_index[idx]:_TThostFtdcClientRegionType_index[idx+1]]
}
