// Code generated by "stringer -type TThostFtdcCmbTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ZCECT_SPZ-48]
	_ = x[THOST_FTDC_ZCECT_SPD-49]
	_ = x[THOST_FTDC_ZCECT_IPS-50]
	_ = x[THOST_FTDC_ZCECT_BUL-51]
	_ = x[THOST_FTDC_ZCECT_BER-52]
	_ = x[THOST_FTDC_ZCECT_BLT-53]
	_ = x[THOST_FTDC_ZCECT_BRT-54]
	_ = x[THOST_FTDC_ZCECT_STD-55]
	_ = x[THOST_FTDC_ZCECT_STG-56]
	_ = x[THOST_FTDC_ZCECT_PRT-57]
}

const _TThostFtdcCmbTypeType_name = "SPZSPDIPSBULBERBLTBRTSTDSTGPRT"

var _TThostFtdcCmbTypeType_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30}

func (i TThostFtdcCmbTypeType) String() string {
	i -= 48
	if i >= TThostFtdcCmbTypeType(len(_TThostFtdcCmbTypeType_index)-1) {
		return "TThostFtdcCmbTypeType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcCmbTypeType_name[_TThostFtdcCmbTypeType_index[i]:_TThostFtdcCmbTypeType_index[i+1]]
}
