// Code generated by "stringer -type TThostFtdcExecResultType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OER_NoExec-110]
	_ = x[THOST_FTDC_OER_Canceled-99]
	_ = x[THOST_FTDC_OER_OK-48]
	_ = x[THOST_FTDC_OER_NoPosition-49]
	_ = x[THOST_FTDC_OER_NoDeposit-50]
	_ = x[THOST_FTDC_OER_NoParticipant-51]
	_ = x[THOST_FTDC_OER_NoClient-52]
	_ = x[THOST_FTDC_OER_NoInstrument-54]
	_ = x[THOST_FTDC_OER_NoRight-55]
	_ = x[THOST_FTDC_OER_InvalidVolume-56]
	_ = x[THOST_FTDC_OER_NoEnoughHistoryTrade-57]
	_ = x[THOST_FTDC_OER_Unknown-97]
}

const (
	_TThostFtdcExecResultType_name_0 = "执行成功期权持仓不够资金不够会员不存在客户不存在"
	_TThostFtdcExecResultType_name_1 = "合约不存在没有执行权限不合理的数量没有足够的历史成交"
	_TThostFtdcExecResultType_name_2 = "未知"
	_TThostFtdcExecResultType_name_3 = "已经取消"
	_TThostFtdcExecResultType_name_4 = "没有执行"
)

var (
	_TThostFtdcExecResultType_index_0 = [...]uint8{0, 12, 30, 42, 57, 72}
	_TThostFtdcExecResultType_index_1 = [...]uint8{0, 15, 33, 51, 78}
)

func (i TThostFtdcExecResultType) String() string {
	switch {
	case 48 <= i && i <= 52:
		i -= 48
		return _TThostFtdcExecResultType_name_0[_TThostFtdcExecResultType_index_0[i]:_TThostFtdcExecResultType_index_0[i+1]]
	case 54 <= i && i <= 57:
		i -= 54
		return _TThostFtdcExecResultType_name_1[_TThostFtdcExecResultType_index_1[i]:_TThostFtdcExecResultType_index_1[i+1]]
	case i == 97:
		return _TThostFtdcExecResultType_name_2
	case i == 99:
		return _TThostFtdcExecResultType_name_3
	case i == 110:
		return _TThostFtdcExecResultType_name_4
	default:
		return "TThostFtdcExecResultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
