// Code generated by "stringer -type TThostFtdcTradeSourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TSRC_NORMAL-48]
	_ = x[THOST_FTDC_TSRC_QUERY-49]
}

const _TThostFtdcTradeSourceType_name = "来自交易所普通回报来自查询"

var _TThostFtdcTradeSourceType_index = [...]uint8{0, 27, 39}

func (i TThostFtdcTradeSourceType) String() string {
	i -= 48
	if i >= TThostFtdcTradeSourceType(len(_TThostFtdcTradeSourceType_index)-1) {
		return "TThostFtdcTradeSourceType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcTradeSourceType_name[_TThostFtdcTradeSourceType_index[i]:_TThostFtdcTradeSourceType_index[i+1]]
}
