// Code generated by "stringer -type TThostFtdcOpenLimitControlLevelType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PLCL_None-48]
	_ = x[THOST_FTDC_PLCL_Product-49]
	_ = x[THOST_FTDC_PLCL_Inst-50]
}

const _TThostFtdcOpenLimitControlLevelType_name = "不控制产品级别合约级别"

var _TThostFtdcOpenLimitControlLevelType_index = [...]uint8{0, 9, 21, 33}

func (i TThostFtdcOpenLimitControlLevelType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcOpenLimitControlLevelType_index)-1 {
		return "TThostFtdcOpenLimitControlLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcOpenLimitControlLevelType_name[_TThostFtdcOpenLimitControlLevelType_index[idx]:_TThostFtdcOpenLimitControlLevelType_index[idx+1]]
}
