// Code generated by "stringer -type TThostFtdcOrganTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OT_Bank-49]
	_ = x[THOST_FTDC_OT_Future-50]
	_ = x[THOST_FTDC_OT_PlateForm-57]
}

const (
	_TThostFtdcOrganTypeType_name_0 = "银行代理交易前置"
	_TThostFtdcOrganTypeType_name_1 = "银期转帐平台管理"
)

var (
	_TThostFtdcOrganTypeType_index_0 = [...]uint8{0, 12, 24}
)

func (i TThostFtdcOrganTypeType) String() string {
	switch {
	case 49 <= i && i <= 50:
		i -= 49
		return _TThostFtdcOrganTypeType_name_0[_TThostFtdcOrganTypeType_index_0[i]:_TThostFtdcOrganTypeType_index_0[i+1]]
	case i == 57:
		return _TThostFtdcOrganTypeType_name_1
	default:
		return "TThostFtdcOrganTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
