// Code generated by "stringer -type TThostFtdcOptionsTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CP_CallOptions-49]
	_ = x[THOST_FTDC_CP_PutOptions-50]
}

const _TThostFtdcOptionsTypeType_name = "看涨看跌"

var _TThostFtdcOptionsTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcOptionsTypeType) String() string {
	i -= 49
	if i >= TThostFtdcOptionsTypeType(len(_TThostFtdcOptionsTypeType_index)-1) {
		return "TThostFtdcOptionsTypeType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcOptionsTypeType_name[_TThostFtdcOptionsTypeType_index[i]:_TThostFtdcOptionsTypeType_index[i+1]]
}
