// Code generated by "stringer -type TThostFtdcBrokerRepealFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BRORF_BrokerNotNeedRepeal-48]
	_ = x[THOST_FTDC_BRORF_BrokerWaitingRepeal-49]
	_ = x[THOST_FTDC_BRORF_BrokerBeenRepealed-50]
}

const _TThostFtdcBrokerRepealFlagType_name = "期商无需自动冲正期商待自动冲正期商已自动冲正"

var _TThostFtdcBrokerRepealFlagType_index = [...]uint8{0, 24, 45, 66}

func (i TThostFtdcBrokerRepealFlagType) String() string {
	i -= 48
	if i >= TThostFtdcBrokerRepealFlagType(len(_TThostFtdcBrokerRepealFlagType_index)-1) {
		return "TThostFtdcBrokerRepealFlagType(" + strconv.FormatInt(int64(i+48), 10) + ")"
	}
	return _TThostFtdcBrokerRepealFlagType_name[_TThostFtdcBrokerRepealFlagType_index[i]:_TThostFtdcBrokerRepealFlagType_index[i+1]]
}
