// Code generated by "stringer -type TThostFtdcAccountSettlementParamIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ASPI_BaseMargin-49]
	_ = x[THOST_FTDC_ASPI_LowestInterest-50]
}

const _TThostFtdcAccountSettlementParamIDType_name = "基础保证金最低权益标准"

var _TThostFtdcAccountSettlementParamIDType_index = [...]uint8{0, 15, 33}

func (i TThostFtdcAccountSettlementParamIDType) String() string {
	i -= 49
	if i >= TThostFtdcAccountSettlementParamIDType(len(_TThostFtdcAccountSettlementParamIDType_index)-1) {
		return "TThostFtdcAccountSettlementParamIDType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcAccountSettlementParamIDType_name[_TThostFtdcAccountSettlementParamIDType_index[i]:_TThostFtdcAccountSettlementParamIDType_index[i+1]]
}
