// Code generated by "stringer -type TThostFtdcByGroupType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BG_Investor-50]
	_ = x[THOST_FTDC_BG_Group-49]
}

const _TThostFtdcByGroupType_name = "按类统计按投资者统计"

var _TThostFtdcByGroupType_index = [...]uint8{0, 12, 30}

func (i TThostFtdcByGroupType) String() string {
	i -= 49
	if i >= TThostFtdcByGroupType(len(_TThostFtdcByGroupType_index)-1) {
		return "TThostFtdcByGroupType(" + strconv.FormatInt(int64(i+49), 10) + ")"
	}
	return _TThostFtdcByGroupType_name[_TThostFtdcByGroupType_index[i]:_TThostFtdcByGroupType_index[i+1]]
}
