// Code generated by "stringer -type TThostFtdcCombinationTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_COMBT_Future-48]
	_ = x[THOST_FTDC_COMBT_BUL-49]
	_ = x[THOST_FTDC_COMBT_BER-50]
	_ = x[THOST_FTDC_COMBT_STD-51]
	_ = x[THOST_FTDC_COMBT_STG-52]
	_ = x[THOST_FTDC_COMBT_PRT-53]
	_ = x[THOST_FTDC_COMBT_CAS-54]
	_ = x[THOST_FTDC_COMBT_OPL-55]
	_ = x[THOST_FTDC_COMBT_BFO-56]
	_ = x[THOST_FTDC_COMBT_BLS-57]
	_ = x[THOST_FTDC_COMBT_BES-97]
}

const (
	_TThostFtdcCombinationTypeType_name_0 = "期货组合垂直价差BUL垂直价差BER跨式组合宽跨式组合备兑组合时间价差组合期权对锁组合买备兑组合买入期权垂直价差组合"
	_TThostFtdcCombinationTypeType_name_1 = "卖出期权垂直价差组合"
)

var (
	_TThostFtdcCombinationTypeType_index_0 = [...]uint8{0, 12, 27, 42, 54, 69, 81, 99, 117, 132, 162}
)

func (i TThostFtdcCombinationTypeType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcCombinationTypeType_name_0[_TThostFtdcCombinationTypeType_index_0[i]:_TThostFtdcCombinationTypeType_index_0[i+1]]
	case i == 97:
		return _TThostFtdcCombinationTypeType_name_1
	default:
		return "TThostFtdcCombinationTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
