// Code generated by "stringer -type TThostFtdcInvestorSettlementParamIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ISPI_MortgageRatio-52]
	_ = x[THOST_FTDC_ISPI_MarginWay-53]
	_ = x[THOST_FTDC_ISPI_BillDeposit-57]
}

const (
	_TThostFtdcInvestorSettlementParamIDType_name_0 = "质押比例保证金算法"
	_TThostFtdcInvestorSettlementParamIDType_name_1 = "结算单结存是否包含质押"
)

var (
	_TThostFtdcInvestorSettlementParamIDType_index_0 = [...]uint8{0, 12, 27}
)

func (i TThostFtdcInvestorSettlementParamIDType) String() string {
	switch {
	case 52 <= i && i <= 53:
		i -= 52
		return _TThostFtdcInvestorSettlementParamIDType_name_0[_TThostFtdcInvestorSettlementParamIDType_index_0[i]:_TThostFtdcInvestorSettlementParamIDType_index_0[i+1]]
	case i == 57:
		return _TThostFtdcInvestorSettlementParamIDType_name_1
	default:
		return "TThostFtdcInvestorSettlementParamIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
