// Code generated by "stringer -type TThostFtdcActionTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ACTP_Exec-49]
	_ = x[THOST_FTDC_ACTP_Abandon-50]
}

const _TThostFtdcActionTypeType_name = "执行放弃"

var _TThostFtdcActionTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcActionTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcActionTypeType_index)-1 {
		return "TThostFtdcActionTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcActionTypeType_name[_TThostFtdcActionTypeType_index[idx]:_TThostFtdcActionTypeType_index[idx+1]]
}
