// Code generated by "stringer -type TThostFtdcActionDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ACD_Add-49]
	_ = x[THOST_FTDC_ACD_Del-50]
	_ = x[THOST_FTDC_ACD_Upd-51]
}

const _TThostFtdcActionDirectionType_name = "增加删除更新"

var _TThostFtdcActionDirectionType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcActionDirectionType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcActionDirectionType_index)-1 {
		return "TThostFtdcActionDirectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcActionDirectionType_name[_TThostFtdcActionDirectionType_index[idx]:_TThostFtdcActionDirectionType_index[idx+1]]
}
