// Code generated by "stringer -type TThostFtdcUserRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UR_All-48]
	_ = x[THOST_FTDC_UR_Single-49]
}

const _TThostFtdcUserRangeType_name = "所有单一操作员"

var _TThostFtdcUserRangeType_index = [...]uint8{0, 6, 21}

func (i TThostFtdcUserRangeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcUserRangeType_index)-1 {
		return "TThostFtdcUserRangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcUserRangeType_name[_TThostFtdcUserRangeType_index[idx]:_TThostFtdcUserRangeType_index[idx+1]]
}
