// Code generated by "stringer -type TThostFtdcDeliveryModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DM_CashDeliv-49]
	_ = x[THOST_FTDC_DM_CommodityDeliv-50]
}

const _TThostFtdcDeliveryModeType_name = "现金交割实物交割"

var _TThostFtdcDeliveryModeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcDeliveryModeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcDeliveryModeType_index)-1 {
		return "TThostFtdcDeliveryModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcDeliveryModeType_name[_TThostFtdcDeliveryModeType_index[idx]:_TThostFtdcDeliveryModeType_index[idx+1]]
}
