// Code generated by "stringer -type TThostFtdcForceCloseReasonType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FCC_NotForceClose-48]
	_ = x[THOST_FTDC_FCC_LackDeposit-49]
	_ = x[THOST_FTDC_FCC_ClientOverPositionLimit-50]
	_ = x[THOST_FTDC_FCC_MemberOverPositionLimit-51]
	_ = x[THOST_FTDC_FCC_NotMultiple-52]
	_ = x[THOST_FTDC_FCC_Violation-53]
	_ = x[THOST_FTDC_FCC_Other-54]
	_ = x[THOST_FTDC_FCC_PersonDeliv-55]
	_ = x[THOST_FTDC_FCC_Notverifycapital-56]
	_ = x[THOST_FTDC_FCC_LocalLackDeposit-57]
	_ = x[THOST_FTDC_FCC_LocalViolationNocheck-97]
	_ = x[THOST_FTDC_FCC_LocalViolation-98]
}

const (
	_TThostFtdcForceCloseReasonType_name_0 = "非强平资金不足客户超仓会员超仓持仓非整数倍违规其它自然人临近交割本地强平资金不足忽略敞口本地强平资金不足"
	_TThostFtdcForceCloseReasonType_name_1 = "本地强平违规持仓忽略敞口本地强平违规持仓"
)

var (
	_TThostFtdcForceCloseReasonType_index_0 = [...]uint8{0, 9, 21, 33, 45, 63, 69, 75, 96, 132, 156}
	_TThostFtdcForceCloseReasonType_index_1 = [...]uint8{0, 36, 60}
)

func (i TThostFtdcForceCloseReasonType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcForceCloseReasonType_name_0[_TThostFtdcForceCloseReasonType_index_0[i]:_TThostFtdcForceCloseReasonType_index_0[i+1]]
	case 97 <= i && i <= 98:
		i -= 97
		return _TThostFtdcForceCloseReasonType_name_1[_TThostFtdcForceCloseReasonType_index_1[i]:_TThostFtdcForceCloseReasonType_index_1[i+1]]
	default:
		return "TThostFtdcForceCloseReasonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
