// Code generated by "stringer -type TThostFtdcPersonTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PST_Order-49]
	_ = x[THOST_FTDC_PST_Open-50]
	_ = x[THOST_FTDC_PST_Fund-51]
	_ = x[THOST_FTDC_PST_Settlement-52]
	_ = x[THOST_FTDC_PST_Company-53]
	_ = x[THOST_FTDC_PST_Corporation-54]
	_ = x[THOST_FTDC_PST_LinkMan-55]
	_ = x[THOST_FTDC_PST_Ledger-56]
	_ = x[THOST_FTDC_PST_Trustee-57]
	_ = x[THOST_FTDC_PST_TrusteeCorporation-65]
	_ = x[THOST_FTDC_PST_TrusteeOpen-66]
	_ = x[THOST_FTDC_PST_TrusteeContact-67]
	_ = x[THOST_FTDC_PST_ForeignerRefer-68]
	_ = x[THOST_FTDC_PST_CorporationRefer-69]
}

const (
	_TThostFtdcPersonTypeType_name_0 = "指定下单人开户授权人资金调拨人结算单确认人法人法人代表投资者联系人分户管理资产负责人托（保）管人"
	_TThostFtdcPersonTypeType_name_1 = "托（保）管机构法人代表托（保）管机构开户授权人托（保）管机构联系人境外自然人参考证件法人代表参考证件"
)

var (
	_TThostFtdcPersonTypeType_index_0 = [...]uint8{0, 15, 30, 45, 63, 69, 81, 99, 126, 144}
	_TThostFtdcPersonTypeType_index_1 = [...]uint8{0, 33, 69, 99, 126, 150}
)

func (i TThostFtdcPersonTypeType) String() string {
	switch {
	case 49 <= i && i <= 57:
		i -= 49
		return _TThostFtdcPersonTypeType_name_0[_TThostFtdcPersonTypeType_index_0[i]:_TThostFtdcPersonTypeType_index_0[i+1]]
	case 65 <= i && i <= 69:
		i -= 65
		return _TThostFtdcPersonTypeType_name_1[_TThostFtdcPersonTypeType_index_1[i]:_TThostFtdcPersonTypeType_index_1[i+1]]
	default:
		return "TThostFtdcPersonTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
