// Code generated by "stringer -type TThostFtdcExchangeSettlementParamIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ESPI_MortgageRatio-49]
	_ = x[THOST_FTDC_ESPI_OtherFundItem-50]
	_ = x[THOST_FTDC_ESPI_OtherFundImport-51]
	_ = x[THOST_FTDC_ESPI_CFFEXMinPrepa-54]
	_ = x[THOST_FTDC_ESPI_CZCESettlementType-55]
	_ = x[THOST_FTDC_ESPI_ExchDelivFeeMode-57]
	_ = x[THOST_FTDC_ESPI_DelivFeeMode-48]
	_ = x[THOST_FTDC_ESPI_CZCEComMarginType-65]
	_ = x[THOST_FTDC_ESPI_DceComMarginType-66]
	_ = x[THOST_FTDC_ESPI_OptOutDisCountRate-97]
	_ = x[THOST_FTDC_ESPI_OptMiniGuarantee-98]
}

const (
	_TThostFtdcExchangeSettlementParamIDType_name_0 = "投资者交割手续费收取方式质押比例分项资金导入项分项资金入交易所出入金"
	_TThostFtdcExchangeSettlementParamIDType_name_1 = "中金所开户最低可用金额郑商所结算方式"
	_TThostFtdcExchangeSettlementParamIDType_name_2 = "交易所交割手续费收取方式"
	_TThostFtdcExchangeSettlementParamIDType_name_3 = "郑商所组合持仓保证金收取方式大商所套利保证金是否优惠"
	_TThostFtdcExchangeSettlementParamIDType_name_4 = "虚值期权保证金优惠比率最低保障系数"
)

var (
	_TThostFtdcExchangeSettlementParamIDType_index_0 = [...]uint8{0, 36, 48, 69, 102}
	_TThostFtdcExchangeSettlementParamIDType_index_1 = [...]uint8{0, 33, 54}
	_TThostFtdcExchangeSettlementParamIDType_index_3 = [...]uint8{0, 42, 78}
	_TThostFtdcExchangeSettlementParamIDType_index_4 = [...]uint8{0, 33, 51}
)

func (i TThostFtdcExchangeSettlementParamIDType) String() string {
	switch {
	case 48 <= i && i <= 51:
		i -= 48
		return _TThostFtdcExchangeSettlementParamIDType_name_0[_TThostFtdcExchangeSettlementParamIDType_index_0[i]:_TThostFtdcExchangeSettlementParamIDType_index_0[i+1]]
	case 54 <= i && i <= 55:
		i -= 54
		return _TThostFtdcExchangeSettlementParamIDType_name_1[_TThostFtdcExchangeSettlementParamIDType_index_1[i]:_TThostFtdcExchangeSettlementParamIDType_index_1[i+1]]
	case i == 57:
		return _TThostFtdcExchangeSettlementParamIDType_name_2
	case 65 <= i && i <= 66:
		i -= 65
		return _TThostFtdcExchangeSettlementParamIDType_name_3[_TThostFtdcExchangeSettlementParamIDType_index_3[i]:_TThostFtdcExchangeSettlementParamIDType_index_3[i+1]]
	case 97 <= i && i <= 98:
		i -= 97
		return _TThostFtdcExchangeSettlementParamIDType_name_4[_TThostFtdcExchangeSettlementParamIDType_index_4[i]:_TThostFtdcExchangeSettlementParamIDType_index_4[i+1]]
	default:
		return "TThostFtdcExchangeSettlementParamIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
