// Code generated by "stringer -type TThostFtdcFileFormatType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FFT_Txt-48]
	_ = x[THOST_FTDC_FFT_Zip-49]
	_ = x[THOST_FTDC_FFT_DBF-50]
}

const _TThostFtdcFileFormatType_name = "文本文件(.txt)压缩文件(.zip)DBF文件(.dbf)"

var _TThostFtdcFileFormatType_index = [...]uint8{0, 18, 36, 51}

func (i TThostFtdcFileFormatType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcFileFormatType_index)-1 {
		return "TThostFtdcFileFormatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcFileFormatType_name[_TThostFtdcFileFormatType_index[idx]:_TThostFtdcFileFormatType_index[idx+1]]
}
