// Code generated by "stringer -type TThostFtdcAmlDateTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AMLDT_DrawDay-48]
	_ = x[THOST_FTDC_AMLDT_TouchDay-49]
}

const _TThostFtdcAmlDateTypeType_name = "检查日期发生日期"

var _TThostFtdcAmlDateTypeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcAmlDateTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcAmlDateTypeType_index)-1 {
		return "TThostFtdcAmlDateTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcAmlDateTypeType_name[_TThostFtdcAmlDateTypeType_index[idx]:_TThostFtdcAmlDateTypeType_index[idx+1]]
}
