// Code generated by "stringer -type TThostFtdcApplyOperateIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AOID_OpenInvestor-49]
	_ = x[THOST_FTDC_AOID_ModifyIDCard-50]
	_ = x[THOST_FTDC_AOID_ModifyNoIDCard-51]
	_ = x[THOST_FTDC_AOID_ApplyTradingCode-52]
	_ = x[THOST_FTDC_AOID_CancelTradingCode-53]
	_ = x[THOST_FTDC_AOID_CancelInvestor-54]
	_ = x[THOST_FTDC_AOID_FreezeAccount-56]
	_ = x[THOST_FTDC_AOID_ActiveFreezeAccount-57]
}

const (
	_TThostFtdcApplyOperateIDType_name_0 = "开户修改身份信息修改一般信息申请交易编码撤销交易编码销户"
	_TThostFtdcApplyOperateIDType_name_1 = "账户休眠激活休眠账户"
)

var (
	_TThostFtdcApplyOperateIDType_index_0 = [...]uint8{0, 6, 24, 42, 60, 78, 84}
	_TThostFtdcApplyOperateIDType_index_1 = [...]uint8{0, 12, 30}
)

func (i TThostFtdcApplyOperateIDType) String() string {
	switch {
	case 49 <= i && i <= 54:
		i -= 49
		return _TThostFtdcApplyOperateIDType_name_0[_TThostFtdcApplyOperateIDType_index_0[i]:_TThostFtdcApplyOperateIDType_index_0[i+1]]
	case 56 <= i && i <= 57:
		i -= 56
		return _TThostFtdcApplyOperateIDType_name_1[_TThostFtdcApplyOperateIDType_index_1[i]:_TThostFtdcApplyOperateIDType_index_1[i+1]]
	default:
		return "TThostFtdcApplyOperateIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
