// Code generated by "stringer -type TThostFtdcOptionRoyaltyPriceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ORPT_PreSettlementPrice-49]
	_ = x[THOST_FTDC_ORPT_OpenPrice-52]
	_ = x[THOST_FTDC_ORPT_MaxPreSettlementPrice-53]
}

const (
	_TThostFtdcOptionRoyaltyPriceTypeType_name_0 = "昨结算价"
	_TThostFtdcOptionRoyaltyPriceTypeType_name_1 = "开仓价最新价与昨结算价较大值"
)

var (
	_TThostFtdcOptionRoyaltyPriceTypeType_index_1 = [...]uint8{0, 9, 42}
)

func (i TThostFtdcOptionRoyaltyPriceTypeType) String() string {
	switch {
	case i == 49:
		return _TThostFtdcOptionRoyaltyPriceTypeType_name_0
	case 52 <= i && i <= 53:
		i -= 52
		return _TThostFtdcOptionRoyaltyPriceTypeType_name_1[_TThostFtdcOptionRoyaltyPriceTypeType_index_1[i]:_TThostFtdcOptionRoyaltyPriceTypeType_index_1[i+1]]
	default:
		return "TThostFtdcOptionRoyaltyPriceTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
