// Code generated by "stringer -type TThostFtdcDceCombinationTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DCECOMBT_SPL-48]
	_ = x[THOST_FTDC_DCECOMBT_OPL-49]
	_ = x[THOST_FTDC_DCECOMBT_SP-50]
	_ = x[THOST_FTDC_DCECOMBT_SPC-51]
	_ = x[THOST_FTDC_DCECOMBT_BLS-52]
	_ = x[THOST_FTDC_DCECOMBT_BES-53]
	_ = x[THOST_FTDC_DCECOMBT_CAS-54]
	_ = x[THOST_FTDC_DCECOMBT_STD-55]
	_ = x[THOST_FTDC_DCECOMBT_STG-56]
	_ = x[THOST_FTDC_DCECOMBT_BFO-57]
	_ = x[THOST_FTDC_DCECOMBT_SFO-97]
}

const (
	_TThostFtdcDceCombinationTypeType_name_0 = "期货对锁组合期权对锁组合期货跨期组合期货跨品种组合买入期权垂直价差组合卖出期权垂直价差组合期权日历价差组合期权跨式组合期权宽跨式组合买入期货期权组合"
	_TThostFtdcDceCombinationTypeType_name_1 = "卖出期货期权组合"
)

var (
	_TThostFtdcDceCombinationTypeType_index_0 = [...]uint8{0, 18, 36, 54, 75, 105, 135, 159, 177, 198, 222}
)

func (i TThostFtdcDceCombinationTypeType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcDceCombinationTypeType_name_0[_TThostFtdcDceCombinationTypeType_index_0[i]:_TThostFtdcDceCombinationTypeType_index_0[i+1]]
	case i == 97:
		return _TThostFtdcDceCombinationTypeType_name_1
	default:
		return "TThostFtdcDceCombinationTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
