// Code generated by "stringer -type TThostFtdcEnumBoolType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EBL_False-48]
	_ = x[THOST_FTDC_EBL_True-49]
}

const _TThostFtdcEnumBoolType_name = "falsetrue"

var _TThostFtdcEnumBoolType_index = [...]uint8{0, 5, 9}

func (i TThostFtdcEnumBoolType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcEnumBoolType_index)-1 {
		return "TThostFtdcEnumBoolType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcEnumBoolType_name[_TThostFtdcEnumBoolType_index[idx]:_TThostFtdcEnumBoolType_index[idx+1]]
}
