// Code generated by "stringer -type TThostFtdcTGSessionQryStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TGQS_QryIdle-49]
	_ = x[THOST_FTDC_TGQS_QryBusy-50]
}

const _TThostFtdcTGSessionQryStatusType_name = "查询状态空闲查询状态频繁"

var _TThostFtdcTGSessionQryStatusType_index = [...]uint8{0, 18, 36}

func (i TThostFtdcTGSessionQryStatusType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcTGSessionQryStatusType_index)-1 {
		return "TThostFtdcTGSessionQryStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcTGSessionQryStatusType_name[_TThostFtdcTGSessionQryStatusType_index[idx]:_TThostFtdcTGSessionQryStatusType_index[idx+1]]
}
