// Code generated by "stringer -type TThostFtdcPositionDateTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PDT_UseHistory-49]
	_ = x[THOST_FTDC_PDT_NoUseHistory-50]
}

const _TThostFtdcPositionDateTypeType_name = "使用历史持仓不使用历史持仓"

var _TThostFtdcPositionDateTypeType_index = [...]uint8{0, 18, 39}

func (i TThostFtdcPositionDateTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcPositionDateTypeType_index)-1 {
		return "TThostFtdcPositionDateTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcPositionDateTypeType_name[_TThostFtdcPositionDateTypeType_index[idx]:_TThostFtdcPositionDateTypeType_index[idx+1]]
}
