// Code generated by "stringer -type TThostFtdcTransferTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TT_BankToFuture-48]
	_ = x[THOST_FTDC_TT_FutureToBank-49]
}

const _TThostFtdcTransferTypeType_name = "银行转期货期货转银行"

var _TThostFtdcTransferTypeType_index = [...]uint8{0, 15, 30}

func (i TThostFtdcTransferTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcTransferTypeType_index)-1 {
		return "TThostFtdcTransferTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcTransferTypeType_name[_TThostFtdcTransferTypeType_index[idx]:_TThostFtdcTransferTypeType_index[idx+1]]
}
