// Code generated by "stringer -type TThostFtdcReserveOpenAccStasType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ROAST_Processing-48]
	_ = x[THOST_FTDC_ROAST_Cancelled-49]
	_ = x[THOST_FTDC_ROAST_Opened-50]
	_ = x[THOST_FTDC_ROAST_Invalid-51]
}

const _TThostFtdcReserveOpenAccStasType_name = "等待处理中已撤销已开户无效请求"

var _TThostFtdcReserveOpenAccStasType_index = [...]uint8{0, 15, 24, 33, 45}

func (i TThostFtdcReserveOpenAccStasType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcReserveOpenAccStasType_index)-1 {
		return "TThostFtdcReserveOpenAccStasType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcReserveOpenAccStasType_name[_TThostFtdcReserveOpenAccStasType_index[idx]:_TThostFtdcReserveOpenAccStasType_index[idx+1]]
}
