// Code generated by "stringer -type TThostFtdcCFMMCKeyKindType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CFMMCKK_REQUEST-82]
	_ = x[THOST_FTDC_CFMMCKK_AUTO-65]
	_ = x[THOST_FTDC_CFMMCKK_MANUAL-77]
}

const (
	_TThostFtdcCFMMCKeyKindType_name_0 = "CFMMC自动更新"
	_TThostFtdcCFMMCKeyKindType_name_1 = "CFMMC手动更新"
	_TThostFtdcCFMMCKeyKindType_name_2 = "主动请求更新"
)

func (i TThostFtdcCFMMCKeyKindType) String() string {
	switch {
	case i == 65:
		return _TThostFtdcCFMMCKeyKindType_name_0
	case i == 77:
		return _TThostFtdcCFMMCKeyKindType_name_1
	case i == 82:
		return _TThostFtdcCFMMCKeyKindType_name_2
	default:
		return "TThostFtdcCFMMCKeyKindType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
