// Code generated by "stringer -type TThostFtdcTransferStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TRFS_Normal-48]
	_ = x[THOST_FTDC_TRFS_Repealed-49]
}

const _TThostFtdcTransferStatusType_name = "正常被冲正"

var _TThostFtdcTransferStatusType_index = [...]uint8{0, 6, 15}

func (i TThostFtdcTransferStatusType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcTransferStatusType_index)-1 {
		return "TThostFtdcTransferStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcTransferStatusType_name[_TThostFtdcTransferStatusType_index[idx]:_TThostFtdcTransferStatusType_index[idx+1]]
}
