// Code generated by "stringer -type TThostFtdcBrokerFunctionCodeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BFC_ForceUserLogout-49]
	_ = x[THOST_FTDC_BFC_UserPasswordUpdate-50]
	_ = x[THOST_FTDC_BFC_SyncBrokerData-51]
	_ = x[THOST_FTDC_BFC_BachSyncBrokerData-52]
	_ = x[THOST_FTDC_BFC_OrderInsert-53]
	_ = x[THOST_FTDC_BFC_OrderAction-54]
	_ = x[THOST_FTDC_BFC_AllQuery-55]
	_ = x[THOST_FTDC_BFC_log-97]
	_ = x[THOST_FTDC_BFC_BaseQry-98]
	_ = x[THOST_FTDC_BFC_TradeQry-99]
	_ = x[THOST_FTDC_BFC_Trade-100]
	_ = x[THOST_FTDC_BFC_Virement-101]
	_ = x[THOST_FTDC_BFC_Risk-102]
	_ = x[THOST_FTDC_BFC_Session-103]
	_ = x[THOST_FTDC_BFC_RiskNoticeCtl-104]
	_ = x[THOST_FTDC_BFC_RiskNotice-105]
	_ = x[THOST_FTDC_BFC_BrokerDeposit-106]
	_ = x[THOST_FTDC_BFC_QueryFund-107]
	_ = x[THOST_FTDC_BFC_QueryOrder-108]
	_ = x[THOST_FTDC_BFC_QueryTrade-109]
	_ = x[THOST_FTDC_BFC_QueryPosition-110]
	_ = x[THOST_FTDC_BFC_QueryMarketData-111]
	_ = x[THOST_FTDC_BFC_QueryUserEvent-112]
	_ = x[THOST_FTDC_BFC_QueryRiskNotify-113]
	_ = x[THOST_FTDC_BFC_QueryFundChange-114]
	_ = x[THOST_FTDC_BFC_QueryInvestor-115]
	_ = x[THOST_FTDC_BFC_QueryTradingCode-116]
	_ = x[THOST_FTDC_BFC_ForceClose-117]
	_ = x[THOST_FTDC_BFC_PressTest-118]
	_ = x[THOST_FTDC_BFC_RemainCalc-119]
	_ = x[THOST_FTDC_BFC_NetPositionInd-120]
	_ = x[THOST_FTDC_BFC_RiskPredict-121]
	_ = x[THOST_FTDC_BFC_DataExport-122]
	_ = x[THOST_FTDC_BFC_RiskTargetSetup-65]
	_ = x[THOST_FTDC_BFC_MarketDataWarn-66]
	_ = x[THOST_FTDC_BFC_QryBizNotice-67]
	_ = x[THOST_FTDC_BFC_CfgBizNotice-68]
	_ = x[THOST_FTDC_BFC_SyncOTP-69]
	_ = x[THOST_FTDC_BFC_SendBizNotice-70]
	_ = x[THOST_FTDC_BFC_CfgRiskLevelStd-71]
	_ = x[THOST_FTDC_BFC_TbCommand-72]
	_ = x[THOST_FTDC_BFC_DeleteOrder-74]
	_ = x[THOST_FTDC_BFC_ParkedOrderInsert-75]
	_ = x[THOST_FTDC_BFC_ParkedOrderAction-76]
	_ = x[THOST_FTDC_BFC_ExecOrderNoCheck-77]
	_ = x[THOST_FTDC_BFC_Designate-78]
	_ = x[THOST_FTDC_BFC_StockDisposal-79]
	_ = x[THOST_FTDC_BFC_BrokerDepositWarn-81]
	_ = x[THOST_FTDC_BFC_CoverWarn-83]
	_ = x[THOST_FTDC_BFC_PreExecOrder-84]
	_ = x[THOST_FTDC_BFC_ExecOrderRisk-80]
	_ = x[THOST_FTDC_BFC_PosiLimitWarn-85]
	_ = x[THOST_FTDC_BFC_QryPosiLimit-86]
	_ = x[THOST_FTDC_BFC_FBSign-87]
	_ = x[THOST_FTDC_BFC_FBAccount-88]
	_ = x[THOST_FTDC_BFC_RcvSMSCode-89]
}

const (
	_TThostFtdcBrokerFunctionCodeType_name_0 = "强制用户登出变更用户口令同步经纪公司数据批量同步经纪公司数据报单插入报单操作全部查询"
	_TThostFtdcBrokerFunctionCodeType_name_1 = "风控指标设置行情预警业务通知查询业务通知模板设置同步动态令牌发送业务通知风险级别标准设置交易终端应急功能"
	_TThostFtdcBrokerFunctionCodeType_name_2 = "删除未知单预埋报单插入预埋报单操作资金不够仍允许行权指定证券处置行权交收风险席位资金预警"
	_TThostFtdcBrokerFunctionCodeType_name_3 = "备兑不足预警行权试算持仓限额预警持仓限额查询银期签到签退银期签约解约接收短信验证码"
	_TThostFtdcBrokerFunctionCodeType_name_4 = "系统功能：登入登出修改密码等基本查询：查询基础数据，如合约，交易所等常量交易查询：如查成交，委托交易功能：报单，撤单银期转账风险监控查询管理：查询会话，踢人等风控通知控制风控通知发送察看经纪公司资金权限资金查询报单查询成交查询持仓查询行情查询用户事件查询风险通知查询出入金查询投资者信息查询交易编码查询强平压力测试权益反算净持仓保证金指标风险预算数据导出"
)

var (
	_TThostFtdcBrokerFunctionCodeType_index_0 = [...]uint8{0, 18, 36, 60, 90, 102, 114, 126}
	_TThostFtdcBrokerFunctionCodeType_index_1 = [...]uint8{0, 18, 30, 48, 72, 90, 108, 132, 156}
	_TThostFtdcBrokerFunctionCodeType_index_2 = [...]uint8{0, 15, 33, 51, 78, 84, 96, 114, 132}
	_TThostFtdcBrokerFunctionCodeType_index_3 = [...]uint8{0, 18, 30, 48, 66, 84, 102, 123}
	_TThostFtdcBrokerFunctionCodeType_index_4 = [...]uint16{0, 42, 108, 144, 174, 186, 198, 237, 255, 273, 303, 315, 327, 339, 351, 363, 381, 399, 414, 435, 453, 459, 471, 483, 507, 519, 531}
)

func (i TThostFtdcBrokerFunctionCodeType) String() string {
	switch {
	case 49 <= i && i <= 55:
		i -= 49
		return _TThostFtdcBrokerFunctionCodeType_name_0[_TThostFtdcBrokerFunctionCodeType_index_0[i]:_TThostFtdcBrokerFunctionCodeType_index_0[i+1]]
	case 65 <= i && i <= 72:
		i -= 65
		return _TThostFtdcBrokerFunctionCodeType_name_1[_TThostFtdcBrokerFunctionCodeType_index_1[i]:_TThostFtdcBrokerFunctionCodeType_index_1[i+1]]
	case 74 <= i && i <= 81:
		i -= 74
		return _TThostFtdcBrokerFunctionCodeType_name_2[_TThostFtdcBrokerFunctionCodeType_index_2[i]:_TThostFtdcBrokerFunctionCodeType_index_2[i+1]]
	case 83 <= i && i <= 89:
		i -= 83
		return _TThostFtdcBrokerFunctionCodeType_name_3[_TThostFtdcBrokerFunctionCodeType_index_3[i]:_TThostFtdcBrokerFunctionCodeType_index_3[i+1]]
	case 97 <= i && i <= 122:
		i -= 97
		return _TThostFtdcBrokerFunctionCodeType_name_4[_TThostFtdcBrokerFunctionCodeType_index_4[i]:_TThostFtdcBrokerFunctionCodeType_index_4[i+1]]
	default:
		return "TThostFtdcBrokerFunctionCodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
