// Code generated by "stringer -type TThostFtdcSettlementBillTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ST_Day-48]
	_ = x[THOST_FTDC_ST_Month-49]
}

const _TThostFtdcSettlementBillTypeType_name = "日报月报"

var _TThostFtdcSettlementBillTypeType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcSettlementBillTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcSettlementBillTypeType_index)-1 {
		return "TThostFtdcSettlementBillTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcSettlementBillTypeType_name[_TThostFtdcSettlementBillTypeType_index[idx]:_TThostFtdcSettlementBillTypeType_index[idx+1]]
}
