// Code generated by "stringer -type TThostFtdcDirectionEnType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DEN_Buy-48]
	_ = x[THOST_FTDC_DEN_Sell-49]
}

const _TThostFtdcDirectionEnType_name = "BuySell"

var _TThostFtdcDirectionEnType_index = [...]uint8{0, 3, 7}

func (i TThostFtdcDirectionEnType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcDirectionEnType_index)-1 {
		return "TThostFtdcDirectionEnType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcDirectionEnType_name[_TThostFtdcDirectionEnType_index[idx]:_TThostFtdcDirectionEnType_index[idx+1]]
}
