// Code generated by "stringer -type TThostFtdcDCEUploadFileNameType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DUFN_DUFN_O-79]
	_ = x[THOST_FTDC_DUFN_DUFN_T-84]
	_ = x[THOST_FTDC_DUFN_DUFN_P-80]
	_ = x[THOST_FTDC_DUFN_DUFN_F-70]
	_ = x[THOST_FTDC_DUFN_DUFN_C-67]
	_ = x[THOST_FTDC_DUFN_DUFN_D-68]
	_ = x[THOST_FTDC_DUFN_DUFN_M-77]
	_ = x[THOST_FTDC_DUFN_DUFN_S-83]
}

const (
	_TThostFtdcDCEUploadFileNameType_name_0 = "^\\d{8}_优惠组合持仓明细表^\\d{8}_持仓明细表"
	_TThostFtdcDCEUploadFileNameType_name_1 = "^\\d{8}_资金结算表"
	_TThostFtdcDCEUploadFileNameType_name_2 = "^\\d{8}_保证金参数表"
	_TThostFtdcDCEUploadFileNameType_name_3 = "^\\d{8}_dl_\\d{3}^\\d{8}_持仓表"
	_TThostFtdcDCEUploadFileNameType_name_4 = "^\\d{8}_期权执行表^\\d{8}_成交表"
)

var (
	_TThostFtdcDCEUploadFileNameType_index_0 = [...]uint8{0, 34, 56}
	_TThostFtdcDCEUploadFileNameType_index_3 = [...]uint8{0, 15, 31}
	_TThostFtdcDCEUploadFileNameType_index_4 = [...]uint8{0, 22, 38}
)

func (i TThostFtdcDCEUploadFileNameType) String() string {
	switch {
	case 67 <= i && i <= 68:
		i -= 67
		return _TThostFtdcDCEUploadFileNameType_name_0[_TThostFtdcDCEUploadFileNameType_index_0[i]:_TThostFtdcDCEUploadFileNameType_index_0[i+1]]
	case i == 70:
		return _TThostFtdcDCEUploadFileNameType_name_1
	case i == 77:
		return _TThostFtdcDCEUploadFileNameType_name_2
	case 79 <= i && i <= 80:
		i -= 79
		return _TThostFtdcDCEUploadFileNameType_name_3[_TThostFtdcDCEUploadFileNameType_index_3[i]:_TThostFtdcDCEUploadFileNameType_index_3[i+1]]
	case 83 <= i && i <= 84:
		i -= 83
		return _TThostFtdcDCEUploadFileNameType_name_4[_TThostFtdcDCEUploadFileNameType_index_4[i]:_TThostFtdcDCEUploadFileNameType_index_4[i+1]]
	default:
		return "TThostFtdcDCEUploadFileNameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
