// Code generated by "stringer -type TThostFtdcCFFEXUploadFileNameType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CFUFN_SUFN_T-84]
	_ = x[THOST_FTDC_CFUFN_SUFN_P-80]
	_ = x[THOST_FTDC_CFUFN_SUFN_F-70]
	_ = x[THOST_FTDC_CFUFN_SUFN_S-83]
}

const (
	_TThostFtdcCFFEXUploadFileNameType_name_0 = "^\\d{4}_SG\\d{1}_\\d{8}_\\d{1}_Capital"
	_TThostFtdcCFFEXUploadFileNameType_name_1 = "^\\d{4}_SG\\d{1}_\\d{8}_\\d{1}_SettlementDetail"
	_TThostFtdcCFFEXUploadFileNameType_name_2 = "^\\d{4}_SG\\d{1}_\\d{8}_\\d{1}_OptionExec^\\d{4}_SG\\d{1}_\\d{8}_\\d{1}_Trade"
)

var (
	_TThostFtdcCFFEXUploadFileNameType_index_2 = [...]uint8{0, 37, 69}
)

func (i TThostFtdcCFFEXUploadFileNameType) String() string {
	switch {
	case i == 70:
		return _TThostFtdcCFFEXUploadFileNameType_name_0
	case i == 80:
		return _TThostFtdcCFFEXUploadFileNameType_name_1
	case 83 <= i && i <= 84:
		i -= 83
		return _TThostFtdcCFFEXUploadFileNameType_name_2[_TThostFtdcCFFEXUploadFileNameType_index_2[i]:_TThostFtdcCFFEXUploadFileNameType_index_2[i+1]]
	default:
		return "TThostFtdcCFFEXUploadFileNameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
