// Code generated by "stringer -type TThostFtdcExchangeConnectStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ECS_NoConnection-49]
	_ = x[THOST_FTDC_ECS_QryInstrumentSent-50]
	_ = x[THOST_FTDC_ECS_GotInformation-57]
}

const (
	_TThostFtdcExchangeConnectStatusType_name_0 = "没有任何连接已经发出合约查询请求"
	_TThostFtdcExchangeConnectStatusType_name_1 = "已经获取信息"
)

var (
	_TThostFtdcExchangeConnectStatusType_index_0 = [...]uint8{0, 18, 48}
)

func (i TThostFtdcExchangeConnectStatusType) String() string {
	switch {
	case 49 <= i && i <= 50:
		i -= 49
		return _TThostFtdcExchangeConnectStatusType_name_0[_TThostFtdcExchangeConnectStatusType_index_0[i]:_TThostFtdcExchangeConnectStatusType_index_0[i+1]]
	case i == 57:
		return _TThostFtdcExchangeConnectStatusType_name_1
	default:
		return "TThostFtdcExchangeConnectStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
