// Code generated by "stringer -type TThostFtdcProdChangeFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PCF_None-48]
	_ = x[THOST_FTDC_PCF_OnlyFrozen-49]
	_ = x[THOST_FTDC_PCF_PositionChange-50]
}

const _TThostFtdcProdChangeFlagType_name = "持仓量和冻结量均无变化持仓量无变化，冻结量有变化持仓量有变化"

var _TThostFtdcProdChangeFlagType_index = [...]uint8{0, 33, 72, 90}

func (i TThostFtdcProdChangeFlagType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcProdChangeFlagType_index)-1 {
		return "TThostFtdcProdChangeFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcProdChangeFlagType_name[_TThostFtdcProdChangeFlagType_index[idx]:_TThostFtdcProdChangeFlagType_index[idx+1]]
}
