// Code generated by "stringer -type TThostFtdcCurrExDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CED_Settlement-48]
	_ = x[THOST_FTDC_CED_Sale-49]
}

const _TThostFtdcCurrExDirectionType_name = "结汇售汇"

var _TThostFtdcCurrExDirectionType_index = [...]uint8{0, 6, 12}

func (i TThostFtdcCurrExDirectionType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcCurrExDirectionType_index)-1 {
		return "TThostFtdcCurrExDirectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcCurrExDirectionType_name[_TThostFtdcCurrExDirectionType_index[idx]:_TThostFtdcCurrExDirectionType_index[idx+1]]
}
