// Code generated by "stringer -type TThostFtdcUserEventTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_UET_Login-49]
	_ = x[THOST_FTDC_UET_Logout-50]
	_ = x[THOST_FTDC_UET_Trading-51]
	_ = x[THOST_FTDC_UET_TradingError-52]
	_ = x[THOST_FTDC_UET_UpdatePassword-53]
	_ = x[THOST_FTDC_UET_Authenticate-54]
	_ = x[THOST_FTDC_UET_SubmitSysInfo-55]
	_ = x[THOST_FTDC_UET_Transfer-56]
	_ = x[THOST_FTDC_UET_Other-57]
	_ = x[THOST_FTDC_UET_UpdateTradingAccountPassword-97]
}

const (
	_TThostFtdcUserEventTypeType_name_0 = "登录登出CTP校验通过CTP校验失败修改密码客户端认证终端信息上报转账其他"
	_TThostFtdcUserEventTypeType_name_1 = "修改资金密码"
)

var (
	_TThostFtdcUserEventTypeType_index_0 = [...]uint8{0, 6, 12, 27, 42, 54, 69, 87, 93, 99}
)

func (i TThostFtdcUserEventTypeType) String() string {
	switch {
	case 49 <= i && i <= 57:
		i -= 49
		return _TThostFtdcUserEventTypeType_name_0[_TThostFtdcUserEventTypeType_index_0[i]:_TThostFtdcUserEventTypeType_index_0[i+1]]
	case i == 97:
		return _TThostFtdcUserEventTypeType_name_1
	default:
		return "TThostFtdcUserEventTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
