// Code generated by "stringer -type TThostFtdcAllWithoutTradeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AWT_Enable-48]
	_ = x[THOST_FTDC_AWT_Disable-50]
	_ = x[THOST_FTDC_AWT_NoHoldEnable-51]
}

const (
	_TThostFtdcAllWithoutTradeType_name_0 = "无仓无成交不受可提比例限制"
	_TThostFtdcAllWithoutTradeType_name_1 = "受可提比例限制无仓不受可提比例限制"
)

var (
	_TThostFtdcAllWithoutTradeType_index_1 = [...]uint8{0, 21, 51}
)

func (i TThostFtdcAllWithoutTradeType) String() string {
	switch {
	case i == 48:
		return _TThostFtdcAllWithoutTradeType_name_0
	case 50 <= i && i <= 51:
		i -= 50
		return _TThostFtdcAllWithoutTradeType_name_1[_TThostFtdcAllWithoutTradeType_index_1[i]:_TThostFtdcAllWithoutTradeType_index_1[i+1]]
	default:
		return "TThostFtdcAllWithoutTradeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
