// Code generated by "stringer -type TThostFtdcOrderStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OST_AllTraded-48]
	_ = x[THOST_FTDC_OST_PartTradedQueueing-49]
	_ = x[THOST_FTDC_OST_PartTradedNotQueueing-50]
	_ = x[THOST_FTDC_OST_NoTradeQueueing-51]
	_ = x[THOST_FTDC_OST_NoTradeNotQueueing-52]
	_ = x[THOST_FTDC_OST_Canceled-53]
	_ = x[THOST_FTDC_OST_Unknown-97]
	_ = x[THOST_FTDC_OST_NotTouched-98]
	_ = x[THOST_FTDC_OST_Touched-99]
}

const (
	_TThostFtdcOrderStatusType_name_0 = "全部成交部分成交还在队列中部分成交不在队列中未成交还在队列中未成交不在队列中撤单"
	_TThostFtdcOrderStatusType_name_1 = "未知尚未触发已触发"
)

var (
	_TThostFtdcOrderStatusType_index_0 = [...]uint8{0, 12, 39, 66, 90, 114, 120}
	_TThostFtdcOrderStatusType_index_1 = [...]uint8{0, 6, 18, 27}
)

func (i TThostFtdcOrderStatusType) String() string {
	switch {
	case 48 <= i && i <= 53:
		i -= 48
		return _TThostFtdcOrderStatusType_name_0[_TThostFtdcOrderStatusType_index_0[i]:_TThostFtdcOrderStatusType_index_0[i+1]]
	case 97 <= i && i <= 99:
		i -= 97
		return _TThostFtdcOrderStatusType_name_1[_TThostFtdcOrderStatusType_index_1[i]:_TThostFtdcOrderStatusType_index_1[i+1]]
	default:
		return "TThostFtdcOrderStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
