// Code generated by "stringer -type TThostFtdcBillHedgeFlagType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BHF_Speculation-49]
	_ = x[THOST_FTDC_BHF_Arbitrage-50]
	_ = x[THOST_FTDC_BHF_Hedge-51]
}

const _TThostFtdcBillHedgeFlagType_name = "投机套利套保"

var _TThostFtdcBillHedgeFlagType_index = [...]uint8{0, 6, 12, 18}

func (i TThostFtdcBillHedgeFlagType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcBillHedgeFlagType_index)-1 {
		return "TThostFtdcBillHedgeFlagType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcBillHedgeFlagType_name[_TThostFtdcBillHedgeFlagType_index[idx]:_TThostFtdcBillHedgeFlagType_index[idx+1]]
}
