// Code generated by "stringer -type TThostFtdcBrokerTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BT_Trade-48]
	_ = x[THOST_FTDC_BT_TradeSettle-49]
	_ = x[THOST_FTDC_BT_Request-49]
	_ = x[THOST_FTDC_BT_Response-50]
	_ = x[THOST_FTDC_BT_Notice-51]
	_ = x[THOST_FTDC_BT_Profit-48]
	_ = x[THOST_FTDC_BT_Loss-49]
	_ = x[THOST_FTDC_BT_Other-90]
}

const (
	_TThostFtdcBrokerTypeType_name_0 = "交易会员交易结算会员应答通知"
	_TThostFtdcBrokerTypeType_name_1 = "其他"
)

var (
	_TThostFtdcBrokerTypeType_index_0 = [...]uint8{0, 12, 30, 36, 42}
)

func (i TThostFtdcBrokerTypeType) String() string {
	switch {
	case 48 <= i && i <= 51:
		i -= 48
		return _TThostFtdcBrokerTypeType_name_0[_TThostFtdcBrokerTypeType_index_0[i]:_TThostFtdcBrokerTypeType_index_0[i+1]]
	case i == 90:
		return _TThostFtdcBrokerTypeType_name_1
	default:
		return "TThostFtdcBrokerTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
