// Code generated by "stringer -type TThostFtdcRiskNotifyStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RNS_NotGen-48]
	_ = x[THOST_FTDC_RNS_Generated-49]
	_ = x[THOST_FTDC_RNS_SendError-50]
	_ = x[THOST_FTDC_RNS_SendOk-51]
	_ = x[THOST_FTDC_RNS_Received-52]
	_ = x[THOST_FTDC_RNS_Confirmed-53]
}

const _TThostFtdcRiskNotifyStatusType_name = "未生成已生成未发送发送失败已发送未接收已接收未确认已确认"

var _TThostFtdcRiskNotifyStatusType_index = [...]uint8{0, 9, 27, 39, 57, 75, 84}

func (i TThostFtdcRiskNotifyStatusType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcRiskNotifyStatusType_index)-1 {
		return "TThostFtdcRiskNotifyStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcRiskNotifyStatusType_name[_TThostFtdcRiskNotifyStatusType_index[idx]:_TThostFtdcRiskNotifyStatusType_index[idx+1]]
}
