// Code generated by "stringer -type TThostFtdcAddrSrvModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ASM_Trade-48]
	_ = x[THOST_FTDC_ASM_MarketData-49]
	_ = x[THOST_FTDC_ASM_Other-50]
}

const _TThostFtdcAddrSrvModeType_name = "交易地址行情地址其他"

var _TThostFtdcAddrSrvModeType_index = [...]uint8{0, 12, 24, 30}

func (i TThostFtdcAddrSrvModeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcAddrSrvModeType_index)-1 {
		return "TThostFtdcAddrSrvModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcAddrSrvModeType_name[_TThostFtdcAddrSrvModeType_index[idx]:_TThostFtdcAddrSrvModeType_index[idx+1]]
}
