// Code generated by "stringer -type TThostFtdcVirBankAccTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VBAT_BankBook-49]
	_ = x[THOST_FTDC_VBAT_BankCard-50]
	_ = x[THOST_FTDC_VBAT_CreditCard-51]
}

const _TThostFtdcVirBankAccTypeType_name = "存折储蓄卡信用卡"

var _TThostFtdcVirBankAccTypeType_index = [...]uint8{0, 6, 15, 24}

func (i TThostFtdcVirBankAccTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcVirBankAccTypeType_index)-1 {
		return "TThostFtdcVirBankAccTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcVirBankAccTypeType_name[_TThostFtdcVirBankAccTypeType_index[idx]:_TThostFtdcVirBankAccTypeType_index[idx+1]]
}
