// Code generated by "stringer -type TThostFtdcAmTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AMT_Bank-49]
	_ = x[THOST_FTDC_AMT_Securities-50]
	_ = x[THOST_FTDC_AMT_Fund-51]
	_ = x[THOST_FTDC_AMT_Insurance-52]
	_ = x[THOST_FTDC_AMT_Trust-53]
	_ = x[THOST_FTDC_AMT_Other-57]
}

const (
	_TThostFtdcAmTypeType_name_0 = "银行证券公司基金公司保险公司信托公司"
	_TThostFtdcAmTypeType_name_1 = "其他"
)

var (
	_TThostFtdcAmTypeType_index_0 = [...]uint8{0, 6, 18, 30, 42, 54}
)

func (i TThostFtdcAmTypeType) String() string {
	switch {
	case 49 <= i && i <= 53:
		i -= 49
		return _TThostFtdcAmTypeType_name_0[_TThostFtdcAmTypeType_index_0[i]:_TThostFtdcAmTypeType_index_0[i+1]]
	case i == 57:
		return _TThostFtdcAmTypeType_name_1
	default:
		return "TThostFtdcAmTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
