// Code generated by "stringer -type TThostFtdcGiveUpDataSourceType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_GUDS_Gen-48]
	_ = x[THOST_FTDC_GUDS_Hand-49]
}

const _TThostFtdcGiveUpDataSourceType_name = "系统生成手工添加"

var _TThostFtdcGiveUpDataSourceType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcGiveUpDataSourceType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcGiveUpDataSourceType_index)-1 {
		return "TThostFtdcGiveUpDataSourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcGiveUpDataSourceType_name[_TThostFtdcGiveUpDataSourceType_index[idx]:_TThostFtdcGiveUpDataSourceType_index[idx+1]]
}
