// Code generated by "stringer -type TThostFtdcProductClassType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PC_Futures-49]
	_ = x[THOST_FTDC_PC_Options-50]
	_ = x[THOST_FTDC_PC_Combination-51]
	_ = x[THOST_FTDC_PC_Spot-52]
	_ = x[THOST_FTDC_PC_EFP-53]
	_ = x[THOST_FTDC_PC_SpotOption-54]
	_ = x[THOST_FTDC_PC_TAS-55]
	_ = x[THOST_FTDC_PC_MI-73]
}

const (
	_TThostFtdcProductClassType_name_0 = "期货期货期权组合即期期转现现货期权TAS合约"
	_TThostFtdcProductClassType_name_1 = "金属指数"
)

var (
	_TThostFtdcProductClassType_index_0 = [...]uint8{0, 6, 18, 24, 30, 39, 51, 60}
)

func (i TThostFtdcProductClassType) String() string {
	switch {
	case 49 <= i && i <= 55:
		i -= 49
		return _TThostFtdcProductClassType_name_0[_TThostFtdcProductClassType_index_0[i]:_TThostFtdcProductClassType_index_0[i+1]]
	case i == 73:
		return _TThostFtdcProductClassType_name_1
	default:
		return "TThostFtdcProductClassType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
