// Code generated by "stringer -type TThostFtdcTradeTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TRDT_SplitCombination-35]
	_ = x[THOST_FTDC_TRDT_Common-48]
	_ = x[THOST_FTDC_TRDT_OptionsExecution-49]
	_ = x[THOST_FTDC_TRDT_OTC-50]
	_ = x[THOST_FTDC_TRDT_EFPDerived-51]
	_ = x[THOST_FTDC_TRDT_CombinationDerived-52]
	_ = x[THOST_FTDC_TRDT_BlockTrade-53]
}

const (
	_TThostFtdcTradeTypeType_name_0 = "组合持仓拆分为单一持仓,初始化不应包含该类型的持仓"
	_TThostFtdcTradeTypeType_name_1 = "普通成交期权执行OTC成交期转现衍生成交组合衍生成交大宗交易成交"
)

var (
	_TThostFtdcTradeTypeType_index_1 = [...]uint8{0, 12, 24, 33, 54, 72, 90}
)

func (i TThostFtdcTradeTypeType) String() string {
	switch {
	case i == 35:
		return _TThostFtdcTradeTypeType_name_0
	case 48 <= i && i <= 53:
		i -= 48
		return _TThostFtdcTradeTypeType_name_1[_TThostFtdcTradeTypeType_index_1[i]:_TThostFtdcTradeTypeType_index_1[i+1]]
	default:
		return "TThostFtdcTradeTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
