// Code generated by "stringer -type TThostFtdcFileBusinessCodeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBC_Others-48]
	_ = x[THOST_FTDC_FBC_TransferDetails-49]
	_ = x[THOST_FTDC_FBC_CustAccStatus-50]
	_ = x[THOST_FTDC_FBC_AccountTradeDetails-51]
	_ = x[THOST_FTDC_FBC_FutureAccountChangeInfoDetails-52]
	_ = x[THOST_FTDC_FBC_CustMoneyDetail-53]
	_ = x[THOST_FTDC_FBC_CustCancelAccountInfo-54]
	_ = x[THOST_FTDC_FBC_CustMoneyResult-55]
	_ = x[THOST_FTDC_FBC_OthersExceptionResult-56]
	_ = x[THOST_FTDC_FBC_CustInterestNetMoneyDetails-57]
	_ = x[THOST_FTDC_FBC_CustMoneySendAndReceiveDetails-97]
	_ = x[THOST_FTDC_FBC_CorporationMoneyTotal-98]
	_ = x[THOST_FTDC_FBC_MainbodyMoneyTotal-99]
	_ = x[THOST_FTDC_FBC_MainPartMonitorData-100]
	_ = x[THOST_FTDC_FBC_PreparationMoney-101]
	_ = x[THOST_FTDC_FBC_BankMoneyMonitorData-102]
}

const (
	_TThostFtdcFileBusinessCodeType_name_0 = "其他转账交易明细对账客户账户状态对账账户类交易明细对账期货账户信息变更明细对账客户资金台账余额明细对账客户销户结息明细对账客户资金余额对账结果其它对账异常结果文件客户结息净额明细"
	_TThostFtdcFileBusinessCodeType_name_1 = "客户资金交收明细法人存管银行资金交收汇总主体间资金交收汇总总分平衡监管数据存管银行备付金余额协办存管银行资金监管数据"
)

var (
	_TThostFtdcFileBusinessCodeType_index_0 = [...]uint16{0, 6, 30, 54, 81, 117, 153, 183, 213, 243, 267}
	_TThostFtdcFileBusinessCodeType_index_1 = [...]uint8{0, 24, 60, 87, 111, 138, 174}
)

func (i TThostFtdcFileBusinessCodeType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcFileBusinessCodeType_name_0[_TThostFtdcFileBusinessCodeType_index_0[i]:_TThostFtdcFileBusinessCodeType_index_0[i+1]]
	case 97 <= i && i <= 102:
		i -= 97
		return _TThostFtdcFileBusinessCodeType_name_1[_TThostFtdcFileBusinessCodeType_index_1[i]:_TThostFtdcFileBusinessCodeType_index_1[i+1]]
	default:
		return "TThostFtdcFileBusinessCodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
