// Code generated by "stringer -type TThostFtdcRCAMSCombinationTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ERComb_BUC-48]
	_ = x[THOST_FTDC_ERComb_BEC-49]
	_ = x[THOST_FTDC_ERComb_BEP-50]
	_ = x[THOST_FTDC_ERComb_BUP-51]
	_ = x[THOST_FTDC_ERComb_CAS-52]
}

const _TThostFtdcRCAMSCombinationTypeType_name = "牛市看涨价差组合熊市看涨价差组合熊市看跌价差组合牛市看跌价差组合日历价差组合"

var _TThostFtdcRCAMSCombinationTypeType_index = [...]uint8{0, 24, 48, 72, 96, 114}

func (i TThostFtdcRCAMSCombinationTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcRCAMSCombinationTypeType_index)-1 {
		return "TThostFtdcRCAMSCombinationTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcRCAMSCombinationTypeType_name[_TThostFtdcRCAMSCombinationTypeType_index[idx]:_TThostFtdcRCAMSCombinationTypeType_index[idx+1]]
}
