// Code generated by "stringer -type TThostFtdcIncludeCloseProfitType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ICP_Include-48]
	_ = x[THOST_FTDC_ICP_NotInclude-50]
}

const (
	_TThostFtdcIncludeCloseProfitType_name_0 = "包含平仓盈利"
	_TThostFtdcIncludeCloseProfitType_name_1 = "不包含平仓盈利"
)

func (i TThostFtdcIncludeCloseProfitType) String() string {
	switch {
	case i == 48:
		return _TThostFtdcIncludeCloseProfitType_name_0
	case i == 50:
		return _TThostFtdcIncludeCloseProfitType_name_1
	default:
		return "TThostFtdcIncludeCloseProfitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
