// Code generated by "stringer -type TThostFtdcBillGenStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_BGS_None-48]
	_ = x[THOST_FTDC_BGS_NoGenerated-49]
	_ = x[THOST_FTDC_BGS_Generated-50]
}

const _TThostFtdcBillGenStatusType_name = "未生成生成中已生成"

var _TThostFtdcBillGenStatusType_index = [...]uint8{0, 9, 18, 27}

func (i TThostFtdcBillGenStatusType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcBillGenStatusType_index)-1 {
		return "TThostFtdcBillGenStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcBillGenStatusType_name[_TThostFtdcBillGenStatusType_index[idx]:_TThostFtdcBillGenStatusType_index[idx+1]]
}
