// Code generated by "stringer -type TThostFtdcRequestTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CONFREQ_ARBI-49]
	_ = x[THOST_FTDC_CONFREQ_HEDGE-50]
}

const _TThostFtdcRequestTypeType_name = "套利套期保值"

var _TThostFtdcRequestTypeType_index = [...]uint8{0, 6, 18}

func (i TThostFtdcRequestTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcRequestTypeType_index)-1 {
		return "TThostFtdcRequestTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcRequestTypeType_name[_TThostFtdcRequestTypeType_index[idx]:_TThostFtdcRequestTypeType_index[idx+1]]
}
