// Code generated by "stringer -type TThostFtdcCombinationTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_COMBT_Future-48]
	_ = x[THOST_FTDC_COMBT_BUL-49]
	_ = x[THOST_FTDC_COMBT_BER-50]
	_ = x[THOST_FTDC_COMBT_STD-51]
	_ = x[THOST_FTDC_COMBT_STG-52]
	_ = x[THOST_FTDC_COMBT_PRT-53]
	_ = x[THOST_FTDC_COMBT_CLD-54]
}

const _TThostFtdcCombinationTypeType_name = "期货组合垂直价差BUL垂直价差BER跨式组合宽跨式组合备兑组合时间价差组合"

var _TThostFtdcCombinationTypeType_index = [...]uint8{0, 12, 27, 42, 54, 69, 81, 99}

func (i TThostFtdcCombinationTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcCombinationTypeType_index)-1 {
		return "TThostFtdcCombinationTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcCombinationTypeType_name[_TThostFtdcCombinationTypeType_index[idx]:_TThostFtdcCombinationTypeType_index[idx+1]]
}
