// Code generated by "stringer -type TThostFtdcInstLifePhaseType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IP_NotStart-48]
	_ = x[THOST_FTDC_IP_Started-49]
	_ = x[THOST_FTDC_IP_Pause-50]
	_ = x[THOST_FTDC_IP_Expired-51]
}

const _TThostFtdcInstLifePhaseType_name = "未上市上市停牌到期"

var _TThostFtdcInstLifePhaseType_index = [...]uint8{0, 9, 15, 21, 27}

func (i TThostFtdcInstLifePhaseType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcInstLifePhaseType_index)-1 {
		return "TThostFtdcInstLifePhaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcInstLifePhaseType_name[_TThostFtdcInstLifePhaseType_index[idx]:_TThostFtdcInstLifePhaseType_index[idx+1]]
}
