// Code generated by "stringer -type TThostFtdcLinkStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_LS_Connected-49]
	_ = x[THOST_FTDC_LS_Disconnected-50]
}

const _TThostFtdcLinkStatusType_name = "已经连接没有连接"

var _TThostFtdcLinkStatusType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcLinkStatusType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcLinkStatusType_index)-1 {
		return "TThostFtdcLinkStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcLinkStatusType_name[_TThostFtdcLinkStatusType_index[idx]:_TThostFtdcLinkStatusType_index[idx+1]]
}
