// Code generated by "stringer -type TThostFtdcSysOperTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SoT_UpdatePassword-48]
	_ = x[THOST_FTDC_SoT_UserDepartment-49]
	_ = x[THOST_FTDC_SoT_RoleManager-50]
	_ = x[THOST_FTDC_SoT_RoleFunction-51]
	_ = x[THOST_FTDC_SoT_BaseParam-52]
	_ = x[THOST_FTDC_SoT_SetUserID-53]
	_ = x[THOST_FTDC_SoT_SetUserRole-54]
	_ = x[THOST_FTDC_SoT_UserIpRestriction-55]
	_ = x[THOST_FTDC_SoT_DepartmentManager-56]
	_ = x[THOST_FTDC_SoT_DepartmentCopy-57]
	_ = x[THOST_FTDC_SoT_Tradingcode-65]
	_ = x[THOST_FTDC_SoT_InvestorStatus-66]
	_ = x[THOST_FTDC_SoT_InvestorAuthority-67]
	_ = x[THOST_FTDC_SoT_PropertySet-68]
	_ = x[THOST_FTDC_SoT_ReSetInvestorPasswd-69]
	_ = x[THOST_FTDC_SoT_InvestorPersonalityInfo-70]
}

const (
	_TThostFtdcSysOperTypeType_name_0 = "修改操作员密码操作员组织架构关系角色管理角色功能设置基础参数设置设置操作员用户角色设置用户IP限制组织架构管理组织架构向查询分类复制"
	_TThostFtdcSysOperTypeType_name_1 = "交易编码管理投资者状态维护投资者权限管理属性设置重置投资者密码投资者个性信息维护"
)

var (
	_TThostFtdcSysOperTypeType_index_0 = [...]uint8{0, 21, 48, 60, 78, 96, 111, 129, 143, 161, 194}
	_TThostFtdcSysOperTypeType_index_1 = [...]uint8{0, 18, 39, 60, 72, 93, 120}
)

func (i TThostFtdcSysOperTypeType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcSysOperTypeType_name_0[_TThostFtdcSysOperTypeType_index_0[i]:_TThostFtdcSysOperTypeType_index_0[i+1]]
	case 65 <= i && i <= 70:
		i -= 65
		return _TThostFtdcSysOperTypeType_name_1[_TThostFtdcSysOperTypeType_index_1[i]:_TThostFtdcSysOperTypeType_index_1[i+1]]
	default:
		return "TThostFtdcSysOperTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
