// Code generated by "stringer -type TThostFtdcFBTTradeCodeEnumType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FTC_BankLaunchBankToBroker-49]
	_ = x[THOST_FTDC_FTC_BrokerLaunchBankToBroker-50]
	_ = x[THOST_FTDC_FTC_BankLaunchBrokerToBank-51]
	_ = x[THOST_FTDC_FTC_BrokerLaunchBrokerToBank-52]
}

const _TThostFtdcFBTTradeCodeEnumType_name = "银行发起银行转期货期货发起银行转期货银行发起期货转银行期货发起期货转银行"

var _TThostFtdcFBTTradeCodeEnumType_index = [...]uint8{0, 27, 54, 81, 108}

func (i TThostFtdcFBTTradeCodeEnumType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcFBTTradeCodeEnumType_index)-1 {
		return "TThostFtdcFBTTradeCodeEnumType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcFBTTradeCodeEnumType_name[_TThostFtdcFBTTradeCodeEnumType_index[idx]:_TThostFtdcFBTTradeCodeEnumType_index[idx+1]]
}
