// Code generated by "stringer -type TThostFtdcCzceCombinationTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CZCECOMBT_SPZ-48]
	_ = x[THOST_FTDC_CZCECOMBT_SPD-49]
	_ = x[THOST_FTDC_CZCECOMBT_IPS-50]
	_ = x[THOST_FTDC_CZCECOMBT_BUL-51]
	_ = x[THOST_FTDC_CZCECOMBT_BER-52]
	_ = x[THOST_FTDC_CZCECOMBT_BLT-53]
	_ = x[THOST_FTDC_CZCECOMBT_BRT-54]
	_ = x[THOST_FTDC_CZCECOMBT_STD-55]
	_ = x[THOST_FTDC_CZCECOMBT_STG-56]
	_ = x[THOST_FTDC_CZCECOMBT_PRT-57]
}

const _TThostFtdcCzceCombinationTypeType_name = "期货对锁期货跨期期货跨品种看涨期权垂直价差看跌期权垂直价差看涨期权水平价差看跌期权水平价差期权跨式组合期权宽跨式组合备兑"

var _TThostFtdcCzceCombinationTypeType_index = [...]uint8{0, 12, 24, 39, 63, 87, 111, 135, 153, 174, 180}

func (i TThostFtdcCzceCombinationTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcCzceCombinationTypeType_index)-1 {
		return "TThostFtdcCzceCombinationTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcCzceCombinationTypeType_name[_TThostFtdcCzceCombinationTypeType_index[idx]:_TThostFtdcCzceCombinationTypeType_index[idx+1]]
}
