// Code generated by "stringer -type TThostFtdcExportFileTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_EFT_CSV-48]
	_ = x[THOST_FTDC_EFT_EXCEL-49]
	_ = x[THOST_FTDC_EFT_DBF-50]
}

const _TThostFtdcExportFileTypeType_name = "CSVExcelDBF"

var _TThostFtdcExportFileTypeType_index = [...]uint8{0, 3, 8, 11}

func (i TThostFtdcExportFileTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcExportFileTypeType_index)-1 {
		return "TThostFtdcExportFileTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcExportFileTypeType_name[_TThostFtdcExportFileTypeType_index[idx]:_TThostFtdcExportFileTypeType_index[idx+1]]
}
