// Code generated by "stringer -type TThostFtdcMKActionModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_MKAM_Product-49]
	_ = x[THOST_FTDC_MKAM_OrderRef-50]
}

const _TThostFtdcMKActionModeType_name = "产品OrderRef"

var _TThostFtdcMKActionModeType_index = [...]uint8{0, 6, 14}

func (i TThostFtdcMKActionModeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcMKActionModeType_index)-1 {
		return "TThostFtdcMKActionModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcMKActionModeType_name[_TThostFtdcMKActionModeType_index[idx]:_TThostFtdcMKActionModeType_index[idx+1]]
}
