// Code generated by "stringer -type TThostFtdcInstrumentStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IS_BeforeTrading-48]
	_ = x[THOST_FTDC_IS_NoTrading-49]
	_ = x[THOST_FTDC_IS_Continous-50]
	_ = x[THOST_FTDC_IS_AuctionOrdering-51]
	_ = x[THOST_FTDC_IS_AuctionBalance-52]
	_ = x[THOST_FTDC_IS_AuctionMatch-53]
	_ = x[THOST_FTDC_IS_Closed-54]
}

const _TThostFtdcInstrumentStatusType_name = "开盘前非交易连续交易集合竞价报单集合竞价价格平衡集合竞价撮合收盘"

var _TThostFtdcInstrumentStatusType_index = [...]uint8{0, 9, 18, 30, 48, 72, 90, 96}

func (i TThostFtdcInstrumentStatusType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcInstrumentStatusType_index)-1 {
		return "TThostFtdcInstrumentStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcInstrumentStatusType_name[_TThostFtdcInstrumentStatusType_index[idx]:_TThostFtdcInstrumentStatusType_index[idx+1]]
}
