// Code generated by "stringer -type TThostFtdcDepartmentRangeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DR_All-49]
	_ = x[THOST_FTDC_DR_Group-50]
	_ = x[THOST_FTDC_DR_Single-51]
}

const _TThostFtdcDepartmentRangeType_name = "所有组织架构单一投资者"

var _TThostFtdcDepartmentRangeType_index = [...]uint8{0, 6, 18, 33}

func (i TThostFtdcDepartmentRangeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcDepartmentRangeType_index)-1 {
		return "TThostFtdcDepartmentRangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcDepartmentRangeType_name[_TThostFtdcDepartmentRangeType_index[idx]:_TThostFtdcDepartmentRangeType_index[idx+1]]
}
