// Code generated by "stringer -type TThostFtdcTradeParamIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TPID_EncryptionStandard-69]
	_ = x[THOST_FTDC_TPID_RiskMode-82]
	_ = x[THOST_FTDC_TPID_RiskModeGlobal-71]
	_ = x[THOST_FTDC_TPID_modeEncode-80]
	_ = x[THOST_FTDC_TPID_tickMode-84]
	_ = x[THOST_FTDC_TPID_SingleUserSessionMaxNum-83]
	_ = x[THOST_FTDC_TPID_LoginFailMaxNum-76]
	_ = x[THOST_FTDC_TPID_IsAuthForce-65]
	_ = x[THOST_FTDC_TPID_IsPosiFreeze-70]
	_ = x[THOST_FTDC_TPID_IsPosiLimit-77]
	_ = x[THOST_FTDC_TPID_ForQuoteTimeInterval-81]
	_ = x[THOST_FTDC_TPID_IsFuturePosiLimit-66]
	_ = x[THOST_FTDC_TPID_IsFutureOrderFreq-67]
	_ = x[THOST_FTDC_TPID_IsExecOrderProfit-72]
}

const (
	_TThostFtdcTradeParamIDType_name_0 = "是否强制认证是否期货限仓是否期货下单频率限制"
	_TThostFtdcTradeParamIDType_name_1 = "系统加密算法是否冻结证券持仓系统风险算法是否全局 0-否 1-是行权冻结是否计算盈利"
	_TThostFtdcTradeParamIDType_name_2 = "最大连续登录失败数是否限仓"
	_TThostFtdcTradeParamIDType_name_3 = "密码加密算法郑商所询价时间间隔系统风险算法用户最大会话数价格小数位数参数"
)

var (
	_TThostFtdcTradeParamIDType_index_0 = [...]uint8{0, 18, 36, 66}
	_TThostFtdcTradeParamIDType_index_1 = [...]uint8{0, 18, 42, 84, 114}
	_TThostFtdcTradeParamIDType_index_2 = [...]uint8{0, 27, 39}
	_TThostFtdcTradeParamIDType_index_3 = [...]uint8{0, 18, 45, 63, 84, 108}
)

func (i TThostFtdcTradeParamIDType) String() string {
	switch {
	case 65 <= i && i <= 67:
		i -= 65
		return _TThostFtdcTradeParamIDType_name_0[_TThostFtdcTradeParamIDType_index_0[i]:_TThostFtdcTradeParamIDType_index_0[i+1]]
	case 69 <= i && i <= 72:
		i -= 69
		return _TThostFtdcTradeParamIDType_name_1[_TThostFtdcTradeParamIDType_index_1[i]:_TThostFtdcTradeParamIDType_index_1[i+1]]
	case 76 <= i && i <= 77:
		i -= 76
		return _TThostFtdcTradeParamIDType_name_2[_TThostFtdcTradeParamIDType_index_2[i]:_TThostFtdcTradeParamIDType_index_2[i+1]]
	case 80 <= i && i <= 84:
		i -= 80
		return _TThostFtdcTradeParamIDType_name_3[_TThostFtdcTradeParamIDType_index_3[i]:_TThostFtdcTradeParamIDType_index_3[i+1]]
	default:
		return "TThostFtdcTradeParamIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
