// Code generated by "stringer -type TThostFtdcProtocalIDType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PID_FutureProtocal-48]
	_ = x[THOST_FTDC_PID_ICBCProtocal-49]
	_ = x[THOST_FTDC_PID_ABCProtocal-50]
	_ = x[THOST_FTDC_PID_CBCProtocal-51]
	_ = x[THOST_FTDC_PID_CCBProtocal-52]
	_ = x[THOST_FTDC_PID_BOCOMProtocal-53]
	_ = x[THOST_FTDC_PID_FBTPlateFormProtocal-88]
}

const (
	_TThostFtdcProtocalIDType_name_0 = "期商协议工行协议农行协议中国银行协议建行协议交行协议"
	_TThostFtdcProtocalIDType_name_1 = "银期转帐平台协议"
)

var (
	_TThostFtdcProtocalIDType_index_0 = [...]uint8{0, 12, 24, 36, 54, 66, 78}
)

func (i TThostFtdcProtocalIDType) String() string {
	switch {
	case 48 <= i && i <= 53:
		i -= 48
		return _TThostFtdcProtocalIDType_name_0[_TThostFtdcProtocalIDType_index_0[i]:_TThostFtdcProtocalIDType_index_0[i+1]]
	case i == 88:
		return _TThostFtdcProtocalIDType_name_1
	default:
		return "TThostFtdcProtocalIDType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
