// Code generated by "stringer -type TThostFtdcForceCloseReasonType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FCC_NotForceClose-48]
	_ = x[THOST_FTDC_FCC_LackDeposit-49]
	_ = x[THOST_FTDC_FCC_ClientOverPositionLimit-50]
	_ = x[THOST_FTDC_FCC_MemberOverPositionLimit-51]
	_ = x[THOST_FTDC_FCC_NotMultiple-52]
	_ = x[THOST_FTDC_FCC_Violation-53]
	_ = x[THOST_FTDC_FCC_Other-54]
	_ = x[THOST_FTDC_FCC_PersonDeliv-55]
}

const _TThostFtdcForceCloseReasonType_name = "非强平资金不足客户超仓会员超仓持仓非整数倍违规其它自然人临近交割"

var _TThostFtdcForceCloseReasonType_index = [...]uint8{0, 9, 21, 33, 45, 63, 69, 75, 96}

func (i TThostFtdcForceCloseReasonType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcForceCloseReasonType_index)-1 {
		return "TThostFtdcForceCloseReasonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcForceCloseReasonType_name[_TThostFtdcForceCloseReasonType_index[idx]:_TThostFtdcForceCloseReasonType_index[idx+1]]
}
