// Code generated by "stringer -type TThostFtdcIPACLCheckModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_IPAC_IP-73]
	_ = x[THOST_FTDC_IPAC_UserID-85]
}

const (
	_TThostFtdcIPACLCheckModeType_name_0 = "IP模式"
	_TThostFtdcIPACLCheckModeType_name_1 = "UserID模式"
)

func (i TThostFtdcIPACLCheckModeType) String() string {
	switch {
	case i == 73:
		return _TThostFtdcIPACLCheckModeType_name_0
	case i == 85:
		return _TThostFtdcIPACLCheckModeType_name_1
	default:
		return "TThostFtdcIPACLCheckModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
