// Code generated by "stringer -type TThostFtdcOrderPriceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_OPT_AnyPrice-49]
	_ = x[THOST_FTDC_OPT_LimitPrice-50]
	_ = x[THOST_FTDC_OPT_BestPrice-51]
	_ = x[THOST_FTDC_OPT_LastPrice-52]
	_ = x[THOST_FTDC_OPT_LastPricePlusOneTicks-53]
	_ = x[THOST_FTDC_OPT_LastPricePlusTwoTicks-54]
	_ = x[THOST_FTDC_OPT_LastPricePlusThreeTicks-55]
	_ = x[THOST_FTDC_OPT_AskPrice1-56]
	_ = x[THOST_FTDC_OPT_AskPrice1PlusOneTicks-57]
	_ = x[THOST_FTDC_OPT_AskPrice1PlusTwoTicks-65]
	_ = x[THOST_FTDC_OPT_AskPrice1PlusThreeTicks-66]
	_ = x[THOST_FTDC_OPT_BidPrice1-67]
	_ = x[THOST_FTDC_OPT_BidPrice1PlusOneTicks-68]
	_ = x[THOST_FTDC_OPT_BidPrice1PlusTwoTicks-69]
	_ = x[THOST_FTDC_OPT_BidPrice1PlusThreeTicks-70]
	_ = x[THOST_FTDC_OPT_FiveLevelPrice-71]
}

const (
	_TThostFtdcOrderPriceTypeType_name_0 = "任意价限价最优价最新价最新价浮动上浮1个ticks最新价浮动上浮2个ticks最新价浮动上浮3个ticks卖一价卖一价浮动上浮1个ticks"
	_TThostFtdcOrderPriceTypeType_name_1 = "卖一价浮动上浮2个ticks卖一价浮动上浮3个ticks买一价买一价浮动上浮1个ticks买一价浮动上浮2个ticks买一价浮动上浮3个ticks五档价"
)

var (
	_TThostFtdcOrderPriceTypeType_index_0 = [...]uint8{0, 9, 15, 24, 33, 63, 93, 123, 132, 162}
	_TThostFtdcOrderPriceTypeType_index_1 = [...]uint8{0, 30, 60, 69, 99, 129, 159, 168}
)

func (i TThostFtdcOrderPriceTypeType) String() string {
	switch {
	case 49 <= i && i <= 57:
		i -= 49
		return _TThostFtdcOrderPriceTypeType_name_0[_TThostFtdcOrderPriceTypeType_index_0[i]:_TThostFtdcOrderPriceTypeType_index_0[i+1]]
	case 65 <= i && i <= 71:
		i -= 65
		return _TThostFtdcOrderPriceTypeType_name_1[_TThostFtdcOrderPriceTypeType_index_1[i]:_TThostFtdcOrderPriceTypeType_index_1[i+1]]
	default:
		return "TThostFtdcOrderPriceTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
