// Code generated by "stringer -type TThostFtdcFBTUserEventTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_FBTUET_SignIn-48]
	_ = x[THOST_FTDC_FBTUET_FromBankToFuture-49]
	_ = x[THOST_FTDC_FBTUET_FromFutureToBank-50]
	_ = x[THOST_FTDC_FBTUET_OpenAccount-51]
	_ = x[THOST_FTDC_FBTUET_CancelAccount-52]
	_ = x[THOST_FTDC_FBTUET_ChangeAccount-53]
	_ = x[THOST_FTDC_FBTUET_RepealFromBankToFuture-54]
	_ = x[THOST_FTDC_FBTUET_RepealFromFutureToBank-55]
	_ = x[THOST_FTDC_FBTUET_QueryBankAccount-56]
	_ = x[THOST_FTDC_FBTUET_QueryFutureAccount-57]
	_ = x[THOST_FTDC_FBTUET_SignOut-65]
	_ = x[THOST_FTDC_FBTUET_SyncKey-66]
	_ = x[THOST_FTDC_FBTUET_ReserveOpenAccount-67]
	_ = x[THOST_FTDC_FBTUET_CancelReserveOpenAccount-68]
	_ = x[THOST_FTDC_FBTUET_ReserveOpenAccountConfirm-69]
	_ = x[THOST_FTDC_FBTUET_Other-90]
}

const (
	_TThostFtdcFBTUserEventTypeType_name_0 = "签到银行转期货期货转银行开户销户变更银行账户冲正银行转期货冲正期货转银行查询银行账户查询期货账户"
	_TThostFtdcFBTUserEventTypeType_name_1 = "签退密钥同步预约开户撤销预约开户预约开户确认"
	_TThostFtdcFBTUserEventTypeType_name_2 = "其他"
)

var (
	_TThostFtdcFBTUserEventTypeType_index_0 = [...]uint8{0, 6, 21, 36, 42, 48, 66, 87, 108, 126, 144}
	_TThostFtdcFBTUserEventTypeType_index_1 = [...]uint8{0, 6, 18, 30, 48, 66}
)

func (i TThostFtdcFBTUserEventTypeType) String() string {
	switch {
	case 48 <= i && i <= 57:
		i -= 48
		return _TThostFtdcFBTUserEventTypeType_name_0[_TThostFtdcFBTUserEventTypeType_index_0[i]:_TThostFtdcFBTUserEventTypeType_index_0[i+1]]
	case 65 <= i && i <= 69:
		i -= 65
		return _TThostFtdcFBTUserEventTypeType_name_1[_TThostFtdcFBTUserEventTypeType_index_1[i]:_TThostFtdcFBTUserEventTypeType_index_1[i+1]]
	case i == 90:
		return _TThostFtdcFBTUserEventTypeType_name_2
	default:
		return "TThostFtdcFBTUserEventTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
