// Code generated by "stringer -type TThostFtdcVirementTradeCodeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_VTC_BankBankToFuture-49]
	_ = x[THOST_FTDC_VTC_BankFutureToBank-50]
	_ = x[THOST_FTDC_VTC_FutureBankToFuture-51]
	_ = x[THOST_FTDC_VTC_FutureFutureToBank-52]
}

const _TThostFtdcVirementTradeCodeType_name = "银行发起银行资金转期货银行发起期货资金转银行期货发起银行资金转期货期货发起期货资金转银行"

var _TThostFtdcVirementTradeCodeType_index = [...]uint8{0, 33, 66, 99, 132}

func (i TThostFtdcVirementTradeCodeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcVirementTradeCodeType_index)-1 {
		return "TThostFtdcVirementTradeCodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcVirementTradeCodeType_name[_TThostFtdcVirementTradeCodeType_index[idx]:_TThostFtdcVirementTradeCodeType_index[idx+1]]
}
