// Code generated by "stringer -type TThostFtdcFBTPassWordTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PWT_Query-48]
	_ = x[THOST_FTDC_PWT_Fetch-49]
	_ = x[THOST_FTDC_PWT_Transfer-50]
	_ = x[THOST_FTDC_PWT_Trade-51]
}

const _TThostFtdcFBTPassWordTypeType_name = "查询取款转帐交易"

var _TThostFtdcFBTPassWordTypeType_index = [...]uint8{0, 6, 12, 18, 24}

func (i TThostFtdcFBTPassWordTypeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcFBTPassWordTypeType_index)-1 {
		return "TThostFtdcFBTPassWordTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcFBTPassWordTypeType_name[_TThostFtdcFBTPassWordTypeType_index[idx]:_TThostFtdcFBTPassWordTypeType_index[idx+1]]
}
