// Code generated by "stringer -type TThostFtdcProductClassType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PC_Futures-49]
	_ = x[THOST_FTDC_PC_Options-50]
	_ = x[THOST_FTDC_PC_Combination-51]
	_ = x[THOST_FTDC_PC_Spot-52]
	_ = x[THOST_FTDC_PC_EFP-53]
	_ = x[THOST_FTDC_PC_SpotOption-54]
	_ = x[THOST_FTDC_PC_TAS-55]
}

const _TThostFtdcProductClassType_name = "期货期货期权组合即期期转现现货期权TAS合约"

var _TThostFtdcProductClassType_index = [...]uint8{0, 6, 18, 24, 30, 39, 51, 60}

func (i TThostFtdcProductClassType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcProductClassType_index)-1 {
		return "TThostFtdcProductClassType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcProductClassType_name[_TThostFtdcProductClassType_index[idx]:_TThostFtdcProductClassType_index[idx+1]]
}
