// Code generated by "stringer -type TThostFtdcAssetmgrClientTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_AMCT_Person-49]
	_ = x[THOST_FTDC_AMCT_Organ-50]
	_ = x[THOST_FTDC_AMCT_SpecialOrgan-52]
}

const (
	_TThostFtdcAssetmgrClientTypeType_name_0 = "个人资管客户单位资管客户"
	_TThostFtdcAssetmgrClientTypeType_name_1 = "特殊单位资管客户"
)

var (
	_TThostFtdcAssetmgrClientTypeType_index_0 = [...]uint8{0, 18, 36}
)

func (i TThostFtdcAssetmgrClientTypeType) String() string {
	switch {
	case 49 <= i && i <= 50:
		i -= 49
		return _TThostFtdcAssetmgrClientTypeType_name_0[_TThostFtdcAssetmgrClientTypeType_index_0[i]:_TThostFtdcAssetmgrClientTypeType_index_0[i+1]]
	case i == 52:
		return _TThostFtdcAssetmgrClientTypeType_name_1
	default:
		return "TThostFtdcAssetmgrClientTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
