// Code generated by "stringer -type TThostFtdcOptionRoyaltyPriceTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_ORPT_PreSettlementPrice-49]
	_ = x[THOST_FTDC_ORPT_OpenPrice-52]
}

const (
	_TThostFtdcOptionRoyaltyPriceTypeType_name_0 = "昨结算价"
	_TThostFtdcOptionRoyaltyPriceTypeType_name_1 = "开仓价"
)

func (i TThostFtdcOptionRoyaltyPriceTypeType) String() string {
	switch {
	case i == 49:
		return _TThostFtdcOptionRoyaltyPriceTypeType_name_0
	case i == 52:
		return _TThostFtdcOptionRoyaltyPriceTypeType_name_1
	default:
		return "TThostFtdcOptionRoyaltyPriceTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
