// Code generated by "stringer -type TThostFtdcConnectModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_CM_ShortConnect-48]
	_ = x[THOST_FTDC_CM_LongConnect-49]
}

const _TThostFtdcConnectModeType_name = "短连接长连接"

var _TThostFtdcConnectModeType_index = [...]uint8{0, 9, 18}

func (i TThostFtdcConnectModeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcConnectModeType_index)-1 {
		return "TThostFtdcConnectModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcConnectModeType_name[_TThostFtdcConnectModeType_index[idx]:_TThostFtdcConnectModeType_index[idx+1]]
}
