// Code generated by "stringer -type TThostFtdcTradingRightType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_TR_Allow-48]
	_ = x[THOST_FTDC_TR_CloseOnly-49]
	_ = x[THOST_FTDC_TR_Forbidden-50]
}

const _TThostFtdcTradingRightType_name = "可以交易只能平仓不能交易"

var _TThostFtdcTradingRightType_index = [...]uint8{0, 12, 24, 36}

func (i TThostFtdcTradingRightType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcTradingRightType_index)-1 {
		return "TThostFtdcTradingRightType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcTradingRightType_name[_TThostFtdcTradingRightType_index[idx]:_TThostFtdcTradingRightType_index[idx+1]]
}
