// Code generated by "stringer -type TThostFtdcStatModeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_SM_Non-48]
	_ = x[THOST_FTDC_SM_Instrument-49]
	_ = x[THOST_FTDC_SM_Product-50]
	_ = x[THOST_FTDC_SM_Investor-51]
	_ = x[THOST_FTDC_SM_Normal-49]
	_ = x[THOST_FTDC_SM_Emerge-50]
	_ = x[THOST_FTDC_SM_Restore-51]
}

const _TThostFtdcStatModeType_name = "----按合约统计按产品统计按投资者统计"

var _TThostFtdcStatModeType_index = [...]uint8{0, 4, 19, 34, 52}

func (i TThostFtdcStatModeType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcStatModeType_index)-1 {
		return "TThostFtdcStatModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcStatModeType_name[_TThostFtdcStatModeType_index[idx]:_TThostFtdcStatModeType_index[idx+1]]
}
