// Code generated by "stringer -type TThostFtdcPosiDirectionType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_PD_Net-49]
	_ = x[THOST_FTDC_PD_Long-50]
	_ = x[THOST_FTDC_PD_Short-51]
}

const _TThostFtdcPosiDirectionType_name = "净多头空头"

var _TThostFtdcPosiDirectionType_index = [...]uint8{0, 3, 9, 15}

func (i TThostFtdcPosiDirectionType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcPosiDirectionType_index)-1 {
		return "TThostFtdcPosiDirectionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcPosiDirectionType_name[_TThostFtdcPosiDirectionType_index[idx]:_TThostFtdcPosiDirectionType_index[idx+1]]
}
