// Code generated by "stringer -type TThostFtdcDeliveryTypeType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_DT_HandDeliv-49]
	_ = x[THOST_FTDC_DT_PersonDeliv-50]
}

const _TThostFtdcDeliveryTypeType_name = "手工交割到期交割"

var _TThostFtdcDeliveryTypeType_index = [...]uint8{0, 12, 24}

func (i TThostFtdcDeliveryTypeType) String() string {
	idx := int(i) - 49
	if i < 49 || idx >= len(_TThostFtdcDeliveryTypeType_index)-1 {
		return "TThostFtdcDeliveryTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcDeliveryTypeType_name[_TThostFtdcDeliveryTypeType_index[idx]:_TThostFtdcDeliveryTypeType_index[idx+1]]
}
