// Code generated by "stringer -type TThostFtdcRiskUserEventType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RUE_ExportData-48]
}

const _TThostFtdcRiskUserEventType_name = "导出数据"

var _TThostFtdcRiskUserEventType_index = [...]uint8{0, 12}

func (i TThostFtdcRiskUserEventType) String() string {
	idx := int(i) - 48
	if i < 48 || idx >= len(_TThostFtdcRiskUserEventType_index)-1 {
		return "TThostFtdcRiskUserEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TThostFtdcRiskUserEventType_name[_TThostFtdcRiskUserEventType_index[idx]:_TThostFtdcRiskUserEventType_index[idx+1]]
}
