// Code generated by "stringer -type TThostFtdcRequestStatusType -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[THOST_FTDC_RS_Submitted-97]
	_ = x[THOST_FTDC_RS_Canceled-99]
	_ = x[THOST_FTDC_RS_DELETE-48]
	_ = x[THOST_FTDC_RS_HANGUP-49]
	_ = x[THOST_FTDC_RS_ACTIVATE-50]
	_ = x[THOST_FTDC_RS_All-49]
	_ = x[THOST_FTDC_RS_ByProduct-50]
}

const (
	_TThostFtdcRequestStatusType_name_0 = "删除挂起激活"
	_TThostFtdcRequestStatusType_name_1 = "已经提交"
	_TThostFtdcRequestStatusType_name_2 = "已经撤销"
)

var (
	_TThostFtdcRequestStatusType_index_0 = [...]uint8{0, 6, 12, 18}
)

func (i TThostFtdcRequestStatusType) String() string {
	switch {
	case 48 <= i && i <= 50:
		i -= 48
		return _TThostFtdcRequestStatusType_name_0[_TThostFtdcRequestStatusType_index_0[i]:_TThostFtdcRequestStatusType_index_0[i+1]]
	case i == 97:
		return _TThostFtdcRequestStatusType_name_1
	case i == 99:
		return _TThostFtdcRequestStatusType_name_2
	default:
		return "TThostFtdcRequestStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
