// Code generated by "stringer -type spanState -linecomment"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpanCreated-0]
	_ = x[SpanPrepared-1]
	_ = x[SpanPrepareFailed-2]
	_ = x[SpanReqSuccess-3]
	_ = x[SpanReqFailed-4]
	_ = x[SpanRspArrived-5]
	_ = x[SpanRspError-6]
	_ = x[SpanRspFinished-7]
	_ = x[SpanBreaked-8]
	_ = x[SpanTimeouted-9]
	_ = x[SpanBreakContinue-10]
}

const _spanState_name = "已创建已就绪准备失败已执行执行失败回执到达回执错误已完成中断超时中断继续"

var _spanState_index = [...]uint8{0, 9, 18, 30, 39, 51, 63, 75, 84, 90, 96, 108}

func (i spanState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_spanState_index)-1 {
		return "spanState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _spanState_name[_spanState_index[idx]:_spanState_index[idx+1]]
}
