// Code generated by "stringer -type mduserState -linecomment types.go"; DO NOT EDIT.

package mduser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Created-0]
	_ = x[Initialized-1]
	_ = x[Connected-2]
	_ = x[Disconnected-3]
	_ = x[LoginSuccess-4]
	_ = x[LoginFailed-5]
	_ = x[LoggedOut-6]
	_ = x[Finalized-7]
}

const _mduserState_name = "已创建已初始化已连接已断连登录成功登录失败已登出已终止"

var _mduserState_index = [...]uint8{0, 9, 21, 30, 39, 51, 63, 72, 81}

func (i mduserState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_mduserState_index)-1 {
		return "mduserState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mduserState_name[_mduserState_index[idx]:_mduserState_index[idx+1]]
}
