// Code generated by "stringer -type traderState -linecomment"; DO NOT EDIT.

package trader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Created-0]
	_ = x[Initialized-1]
	_ = x[Connected-2]
	_ = x[Disconnected-3]
	_ = x[AuthSuccess-4]
	_ = x[AuthFailed-5]
	_ = x[LoginSuccess-6]
	_ = x[LoginFailed-7]
	_ = x[LoggedOut-8]
	_ = x[Finalized-9]
}

const _traderState_name = "已创建已初始化已连接已断连授权成功授权失败登录成功登录失败已登出已终止"

var _traderState_index = [...]uint8{0, 9, 21, 30, 39, 51, 63, 75, 87, 96, 105}

func (i traderState) String() string {
	if i >= traderState(len(_traderState_index)-1) {
		return "traderState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _traderState_name[_traderState_index[i]:_traderState_index[i+1]]
}
